/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FinHealth.framework/FinHealth
 */

@interface FHStatementDetails : NSObject {
    NSDecimalNumber * _creditLimit;
    NSDecimalNumber * _currentBalance;
    NSString * _currentStatementIdentifier;
    bool  _isMonthOne;
    bool  _isMonthZero;
    NSDecimalNumber * _minimumDue;
    NSDecimalNumber * _remainingMinimumPayment;
    NSDecimalNumber * _remainingStatementBalance;
    NSDecimalNumber * _statementBalance;
    NSString * _statementIdentifier;
    NSArray * _transactionPaymentDetails;
    NSArray * _transactionPurchasesDetails;
}

@property (nonatomic, retain) NSDecimalNumber *creditLimit;
@property (nonatomic, retain) NSDecimalNumber *currentBalance;
@property (nonatomic, retain) NSString *currentStatementIdentifier;
@property (nonatomic) bool isMonthOne;
@property (nonatomic) bool isMonthZero;
@property (nonatomic, retain) NSDecimalNumber *minimumDue;
@property (nonatomic, retain) NSDecimalNumber *remainingMinimumPayment;
@property (nonatomic, retain) NSDecimalNumber *remainingStatementBalance;
@property (nonatomic, retain) NSDecimalNumber *statementBalance;
@property (nonatomic, retain) NSString *statementIdentifier;
@property (nonatomic, retain) NSArray *transactionPaymentDetails;
@property (nonatomic, retain) NSArray *transactionPurchasesDetails;

- (void).cxx_destruct;
- (id)creditLimit;
- (id)currentBalance;
- (id)currentStatementIdentifier;
- (bool)isMonthOne;
- (bool)isMonthZero;
- (id)minimumDue;
- (id)remainingMinimumPayment;
- (id)remainingStatementBalance;
- (void)setCreditLimit:(id)arg1;
- (void)setCurrentBalance:(id)arg1;
- (void)setCurrentStatementIdentifier:(id)arg1;
- (void)setIsMonthOne:(bool)arg1;
- (void)setIsMonthZero:(bool)arg1;
- (void)setMinimumDue:(id)arg1;
- (void)setRemainingMinimumPayment:(id)arg1;
- (void)setRemainingStatementBalance:(id)arg1;
- (void)setStatementBalance:(id)arg1;
- (void)setStatementIdentifier:(id)arg1;
- (void)setTransactionPaymentDetails:(id)arg1;
- (void)setTransactionPurchasesDetails:(id)arg1;
- (id)statementBalance;
- (id)statementIdentifier;
- (id)transactionPaymentDetails;
- (id)transactionPurchasesDetails;

@end
