/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AdPlatformsCommon.framework/AdPlatformsCommon
 */

@interface APSystemInternal : NSObject

+ (bool)isAppleInternalInstall;

@end
