/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VectorKit.framework/VectorKit
 */

@interface VKTrafficIncidentFeature : VKTrafficFeature {
    NSString * _crossStreet;
    struct optional<gss::IncidentDataSource> { 
        bool _hasValue; 
        union ValueUnion { 
            unsigned char data[1]; 
            unsigned char type; 
        } _value; 
    }  _dataSource;
    NSDate * _endDate;
    NSString * _info;
    bool  _isNotForDisplay;
    bool  _isOnSelectedRoute;
    NSDate * _lastUpdatedDate;
    GEORestrictionInfo * _restrictionInfo;
    long long  _routeRelevance;
    long long  _significance;
    NSDate * _startDate;
    NSString * _street;
    NSString * _subtitle;
    NSString * _title;
    long long  _type;
    NSString * _uniqueString;
}

@property (nonatomic, readonly) NSString *crossStreet;
@property (nonatomic, readonly) struct optional<gss::IncidentDataSource> { bool x1; union ValueUnion { unsigned char x_2_1_1[1]; unsigned char x_2_1_2; } x2; } dataSource;
@property (nonatomic, readonly) GEOFormattedString *effectiveTimeRange;
@property (nonatomic, readonly) NSDate *endDate;
@property (nonatomic, readonly) GEOFormattedString *formattedSubtitle;
@property (nonatomic, readonly) GEOFormattedString *formattedTitle;
@property (nonatomic, readonly) NSString *info;
@property (nonatomic, readonly) bool isNotForDisplay;
@property (nonatomic) bool isOnSelectedRoute;
@property (nonatomic, readonly) NSDate *lastUpdatedDate;
@property (nonatomic, readonly) NSArray *restrictionDetails;
@property (nonatomic) long long routeRelevance;
@property (nonatomic, readonly) long long significance;
@property (nonatomic, readonly) NSDate *startDate;
@property (nonatomic, readonly) NSString *street;
@property (nonatomic, readonly, copy) NSString *subtitle;
@property (nonatomic, readonly, copy) NSString *title;
@property (nonatomic, readonly) long long type;
@property (nonatomic, readonly) NSString *uniqueString;

+ (long long)incidentTypeForGeoRouteIncident:(id)arg1;
+ (id)stringForIncidentSignificance:(long long)arg1;
+ (id)stringForIncidentType:(long long)arg1;
+ (id)stringForRouteRelevance:(long long)arg1;

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)crossStreet;
- (struct optional<gss::IncidentDataSource> { bool x1; union ValueUnion { unsigned char x_2_1_1[1]; unsigned char x_2_1_2; } x2; })dataSource;
- (void)dealloc;
- (id)effectiveTimeRange;
- (id)endDate;
- (id)formattedSubtitle;
- (id)formattedTitle;
- (bool)hasSameIdentifier:(id)arg1;
- (id)info;
- (id)initWithIncidentData:(const struct Incident { struct GeoCoordinates { struct Longitude { unsigned int x_1_2_1; } x_1_1_1; struct Latitude { unsigned int x_2_2_1; } x_1_1_2; int x_1_1_3; } x1; struct String { struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> { struct __rep { union { struct __long { char *x_1_5_1; unsigned long long x_1_5_2; unsigned long long x_1_5_3; } x_1_4_1; struct __short { BOOL x_2_5_1[23]; struct { unsigned char x_2_6_1; } x_2_5_2; } x_1_4_2; struct __raw { unsigned long long x_3_5_1[3]; } x_1_4_3; } x_1_3_1; } x_1_2_1; } x_2_1_1; } x2; struct String { struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> { struct __rep { union { struct __long { char *x_1_5_1; unsigned long long x_1_5_2; unsigned long long x_1_5_3; } x_1_4_1; struct __short { BOOL x_2_5_1[23]; struct { unsigned char x_2_6_1; } x_2_5_2; } x_1_4_2; struct __raw { unsigned long long x_3_5_1[3]; } x_1_4_3; } x_1_3_1; } x_1_2_1; } x_3_1_1; } x3; }*)arg1 worldPoint:(struct Matrix<double, 3, 1> { double x1[3]; }*)arg2;
- (id)initWithRouteIncident:(id)arg1 routeOffsetInMeters:(unsigned int)arg2 routeRelevance:(long long)arg3 onRoute:(id)arg4;
- (bool)isNotForDisplay;
- (bool)isOnSelectedRoute;
- (id)lastUpdatedDate;
- (void)populateDebugNode:(struct DebugTreeNode { struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> { struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> { struct __rep { union { struct __long { char *x_1_5_1; unsigned long long x_1_5_2; unsigned long long x_1_5_3; } x_1_4_1; struct __short { BOOL x_2_5_1[23]; struct { unsigned char x_2_6_1; } x_2_5_2; } x_1_4_2; struct __raw { unsigned long long x_3_5_1[3]; } x_1_4_3; } x_1_3_1; } x_1_2_1; } x_1_1_1; } x1; struct basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> { struct __compressed_pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::__rep, std::__1::allocator<char>> { struct __rep { union { struct __long { char *x_1_5_1; unsigned long long x_1_5_2; unsigned long long x_1_5_3; } x_1_4_1; struct __short { BOOL x_2_5_1[23]; struct { unsigned char x_2_6_1; } x_2_5_2; } x_1_4_2; struct __raw { unsigned long long x_3_5_1[3]; } x_1_4_3; } x_1_3_1; } x_1_2_1; } x_2_1_1; } x2; }*)arg1;
- (id)restrictionDetails;
- (long long)routeRelevance;
- (void)setIsOnSelectedRoute:(bool)arg1;
- (void)setRouteRelevance:(long long)arg1;
- (long long)significance;
- (id)startDate;
- (id)street;
- (id)subtitle;
- (id)title;
- (long long)type;
- (id)uniqueString;

@end
