/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeUI.framework/HomeUI
 */

@interface HUHomePodServiceDetails : NSObject

+ (id)_homePodDetailsViewControllerForAccessory:(id)arg1 inHome:(id)arg2;
+ (id)_homePodDetailsViewControllerForAccessoryWithMediaRoutingIdentifier:(id)arg1 deviceName:(id)arg2 mediaAccessoryItemType:(long long)arg3;
+ (id)_homePodDetailsViewControllerForHomePodWithUUID:(id)arg1 inHomeWithUUID:(id)arg2 fromHomes:(id)arg3;
+ (id)_homePodDetailsViewControllerForMediaRoutingIdentifier:(id)arg1 deviceName:(id)arg2 mediaAccessoryItemType:(long long)arg3;
+ (id)_homePodSettingsViewControllerForAccessory:(id)arg1 inHome:(id)arg2;
+ (id)_homePodSettingsViewControllerForHomePodWithUUID:(id)arg1 inHomeWithUUID:(id)arg2 fromHomes:(id)arg3;
+ (id)homePodCardForDeviceUUID:(id)arg1 inHomeWithUUID:(id)arg2;
+ (id)homePodCardForMediaRoutingIdentifier:(id)arg1 deviceName:(id)arg2 mediaAccessoryItemType:(long long)arg3;
+ (id)homePodCardWithQuickControlsForDeviceUUID:(id)arg1 inHomeWithUUID:(id)arg2;

@end
