/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitCore.framework/PassKitCore
 */

@interface PKPaymentTransactionMapsLookupResponse : NSObject {
    PKMapsBrand * _brand;
    long long  _fallbackCategory;
    PKMapsMerchant * _merchant;
    CLPlacemark * _placemark;
}

@property (nonatomic, retain) PKMapsBrand *brand;
@property (nonatomic) long long fallbackCategory;
@property (nonatomic, retain) PKMapsMerchant *merchant;
@property (nonatomic, retain) CLPlacemark *placemark;

- (void).cxx_destruct;
- (id)brand;
- (long long)fallbackCategory;
- (id)initWithFallbackCategory:(long long)arg1 merchant:(id)arg2 brand:(id)arg3 placemark:(id)arg4;
- (id)merchant;
- (id)placemark;
- (void)setBrand:(id)arg1;
- (void)setFallbackCategory:(long long)arg1;
- (void)setMerchant:(id)arg1;
- (void)setPlacemark:(id)arg1;

@end
