/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PegasusKit.framework/PegasusKit
 */

@interface PegasusKit.GRPCClient : _TtCs12_SwiftObject {
    void baseURLString;
    void session;
}

@end
