/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.PageRefreshGate : _TtCs12_SwiftObject {
    void appIsForegrounded;
    void isVisible;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  lastOffscreenDate;
    void performRefresh;
    void policy;
    void viewIsVisible;
}

@end
