/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.GameCenterPlayer : _TtCs12_SwiftObject {
    void action;
    void alias;
    void artwork;
    void displayName;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  impressionMetrics;
    void playerId;
    void size;
}

@end
