/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.AdIncident : _TtCs12_SwiftObject {
    void incidentType;
}

@end
