/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.BaseShelfPresenter : AppStoreKit.BasePresenter {
    void activeRequests;
    void incompleteShelfFetches;
    void isFetchingShelves;
}

@end
