/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.FastImpressionFlushGate : _TtCs12_SwiftObject {
    void delayToFlush;
    void onFlush;
    void scheduledFlushTimer;
}

@end
