/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppStoreKit.framework/AppStoreKit
 */

@interface AppStoreKit.AdProcessingPipelineProxy : _TtCs12_SwiftObject {
    void sessionProviding;
}

@end
