/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TipsCore.framework/TipsCore
 */

@interface TPSTileContent : TPSContent

+ (bool)supportsSecureCoding;

- (id)debugDescription;
- (id)initWithDictionary:(id)arg1 metadata:(id)arg2;

@end
