/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MetalPerformanceShadersGraph.framework/MetalPerformanceShadersGraph
 */

@interface MPSGraphExecutableDescriptor : NSObject {
    unsigned long long  _compilerOptions;
    id /* block */  _variableFetchHandler;
}

@property unsigned long long compilerOptions;
@property (copy) id /* block */ variableFetchHandler;

- (void).cxx_destruct;
- (unsigned long long)compilerOptions;
- (id)init;
- (void)setCompilerOptions:(unsigned long long)arg1;
- (void)setVariableFetchHandler:(id /* block */)arg1;
- (id /* block */)variableFetchHandler;

@end
