/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface _TtC10ChronoCoreP33_B57BA582B248C1D823BDF785EF8C4B7C9DebugView : ChronoCore.TouchPassThroughView {
    void animationsDisabled;
    void animationsDisabledView;
    void debugText;
    void debugTextView;
    void isSnapshotting;
    void isSnapshottingView;
}

- (void).cxx_destruct;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)layoutSubviews;

@end
