/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface ChronoCore.DebugOverlayViewController : UIViewController {
    void animationsDisabled;
    void debugText;
    void debugView;
    void isSnapshotting;
}

- (void).cxx_destruct;
- (bool)_canShowWhileLocked;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (void)viewWillAppear:(bool)arg1;

@end
