/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface ChronoCore.ChronodPreferences : _TtCs12_SwiftObject {
    void _lock;
    void _lock_userDefaults;
}

@end
