/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface ChronoCore.ZStackContainerViewController : UIViewController

@property (nonatomic, readonly) bool shouldAutomaticallyForwardAppearanceMethods;

- (bool)_canShowWhileLocked;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)loadView;
- (bool)shouldAutomaticallyForwardAppearanceMethods;

@end
