/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoCore.framework/ChronoCore
 */

@interface ChronoCore.ToolServicesServer : NSObject <BSServiceConnectionListenerDelegate, CHSChronoToolServiceServerInterface> {
    void clientConnections;
    void configurationService;
    void connectionListener;
    void descriptorService;
    void extensionService;
    void keybagMonitor;
    void placeholderCacheManager;
    void queue;
    void snapshotCacheManager;
    void stateCaptureService;
    void subscriptions;
    void taskService;
    void timelineCacheManager;
    void timelineService;
}

- (void).cxx_destruct;
- (void)cacheDescriptorsForBundleIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)disableWakeBudgetForExtensionWithBundleIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)disableWakeBudgetWithCompletion:(id /* block */)arg1;
- (void)extensionInfoForBundleIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)extensionInfoWithCompletion:(id /* block */)arg1;
- (void)fetchStateForItemWithIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)fetchStateWithCompletion:(id /* block */)arg1;
- (id)init;
- (void)listStateCaptureIdentifiersWithCompletion:(id /* block */)arg1;
- (void)listener:(id)arg1 didReceiveConnection:(id)arg2 withContext:(id)arg3;
- (void)reloadTimelinesOfKind:(id)arg1 containedIn:(id)arg2 completion:(id /* block */)arg3;
- (void)resetCaches:(id)arg1 completion:(id /* block */)arg2;
- (void)resetWakeBudgetForExtensionWithBundleIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)resetWakeBudgetWithCompletion:(id /* block */)arg1;
- (void)timelineForWidgetKey:(id)arg1 completion:(id /* block */)arg2;
- (void)wakesRemainingForExtensionWithBundleIdentifier:(id)arg1 completion:(id /* block */)arg2;
- (void)widgetsWithTimelines:(id /* block */)arg1;

@end
