/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitRuntime.framework/SiriKitRuntime
 */

@interface SiriKitRuntime.SiriKitRuntime : _TtCs12_SwiftObject {
    void executionInfo;
    void serviceHelper;
}

@end
