/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BarcodeSupport.framework/BarcodeSupport
 */

@interface BCSShareActionPickerItem : BCSActionPickerItem

- (id)icon;
- (id)label;

@end
