/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourMedia.framework/SeymourMedia
 */

@interface SeymourMedia.MetricPlaybackTracker : _TtCs12_SwiftObject {
    void assetClient;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  catalogWorkout;
    void delegatedPlayback;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  downloadState;
    void eventHub;
    void expectedWorkoutPlaybackPause;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  lastWorkoutPlaybackInfo;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  mediaType;
    void musicIDStartPlaybackInfoMap;
    void networkEvaluator;
    void onInvalidTransition;
    void platform;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  seekBeganMusicTrack;
    void seekBeganMusicTrackPosition;
    void seekBeganOverallPosition;
    void seekBeganTimestamp;
    void seeking;
    void subscriptionToken;
}

- (void)handleAppWillResign;
- (void)handlePlaybackInterrupted;

@end
