/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourMedia.framework/SeymourMedia
 */

@interface SeymourMedia.MediaPlayerObserver : _TtCs12_SwiftObject {
    void eventHub;
    void isSupressingUpdates;
    void lastObservedTime;
    void lastPlayedTime;
    void playbackTimeJumpThreshold;
    void queue;
    void state;
}

- (void)playbackFinished:(id)arg1;

@end
