/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriReferenceResolution.framework/SiriReferenceResolution
 */

@interface SiriReferenceResolution.RRMentionedEvent : _TtCs12_SwiftObject {
    void entities;
    void mentionedAuthor;
}

@end
