/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriReferenceResolution.framework/SiriReferenceResolution
 */

@interface SiriReferenceResolution.SiriReferenceResolutionService : _TtCs12_SwiftObject {
    void eventProcessor;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  logger;
    void resolver;
    void storage;
}

@end
