/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriReferenceResolution.framework/SiriReferenceResolution
 */

@interface SiriReferenceResolution.RRMemoryStorage : _TtCs12_SwiftObject {
    void entities;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  logger;
    void semaphore;
}

@end
