/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriAnalytics.framework/SiriAnalytics
 */

@interface AssistantSiriAnalyticsService : NSObject {
    SiriAnalyticsMessageObserverStream * _postTransformStream;
    NSObject<OS_dispatch_queue> * _queue;
    SiriAnalyticsXPCServiceListener * _siriAnalyticsListener;
    id  _siriAnalyticsObserverHandle;
    SiriAnalyticsTimePeriodBuffer * _storageBuffer;
    <SiriAnalyticsMessageStorage> * _storageProvider;
}

@property (readonly) <SiriAnalyticsObservableMessages> *postTransformationStream;

- (void).cxx_destruct;
- (id)_applyTransformationsToMessage:(id)arg1;
- (id)_applyTransformationsToMessages:(id)arg1;
- (id)initWithQueue:(id)arg1;
- (id)initWithQueue:(id)arg1 storageProvider:(id)arg2;
- (id)postTransformationStream;

@end
