/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriAnalytics.framework/SiriAnalytics
 */

@interface SiriAnalyticsFBFMessageStorageProvider : NSObject <SiriAnalyticsMessageStorage> {
    NSString * _applicationIdentifier;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)initWithApplicationIdentifier:(id)arg1;
- (void)storeMessages:(id)arg1;

@end
