/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoMusicSync.framework/NanoMusicSync
 */

@interface NMSMediaSyncInfoUpdater : NSObject <ATAssetLinkControllerObserver, MTDBExtensionAccessObserver> {
    ATAssetLinkController * _assetLinkController;
    NSObject<OS_dispatch_source> * _currentSyncInfoSynchronizeTimer;
    NSPersistentHistoryToken * _lastToken;
    bool  _observing;
    NSOperationQueue * _queue;
    NSMutableDictionary * _syncInfo;
    NSMutableOrderedSet * _targetsNeedingSyncInfoSynchronize;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSPersistentHistoryToken *lastToken;
@property (readonly) Class superclass;

+ (id)sharedMediaSyncInfoUpdater;

- (void).cxx_destruct;
- (void)_applyUpdatesFromAsset:(id)arg1;
- (bool)_changeContainsRelevantEpisodeChanges:(id)arg1;
- (bool)_didFindRelevantChangesForTransaction:(id)arg1;
- (void)_handleMediaLibraryDidChangeNotification:(id)arg1;
- (void)_handleMediaPinningAudiobooksContentsInvalidatedNotification:(id)arg1;
- (void)_handleMediaPinningMusicContentsInvalidatedNotification:(id)arg1;
- (void)_handleMediaPinningPodcastsContentsInvalidatedNotification:(id)arg1;
- (void)_handleMusicRecommendationsDidUpdateNotification:(id)arg1;
- (void)_handlePersistentStoreRemoteChangeNotification:(id)arg1;
- (id)_lastTokenCachePath;
- (id)_relevantEpisodeProperties;
- (void)_resetPersistentHistoryTokenAndNotifyObservers;
- (void)_setNeedsMediaSyncInfoUpdate;
- (void)assetLinkController:(id)arg1 didEnqueueAsset:(id)arg2;
- (void)assetLinkController:(id)arg1 didFinishAsset:(id)arg2;
- (void)assetLinkController:(id)arg1 didUpdateAsset:(id)arg2;
- (void)assetLinkController:(id)arg1 didUpdateAssetState:(id)arg2;
- (void)beginUpdatingSyncInfo;
- (void)endUpdatingSyncInfo;
- (void)extensionAccessDidChange;
- (id)init;
- (id)lastToken;
- (void)setLastToken:(id)arg1;

@end
