/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CinematicFraming.framework/CinematicFraming
 */

@interface CinematicFramingSession : NSObject {
    PerspectiveDistortionCorrectionSession * _cropSession;
    NSObject<OS_dispatch_queue> * _dataOutputDelegateQueue;
    CinematicDirectorSession * _directorSession;
    struct { 
        int width; 
        int height; 
    }  _outputDimensions;
    struct __CVPixelBufferPool { } * _outputPixelBufferPool;
    unsigned int  _roiHeatMap;
}

@property (nonatomic) int cameraOrientation;
@property (nonatomic, retain) CinematicFramingSessionOptions *options;
@property (nonatomic, readonly) NSArray *roiHeatMapCounts;

- (void).cxx_destruct;
- (struct opaqueCMSampleBuffer { }*)_createSampleBufferFromPixelBuffer:(struct __CVBuffer { }*)arg1 referenceSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg2;
- (void)_updateROIHeatMapCountersWithCropRect:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (int)cameraOrientation;
- (void)dealloc;
- (id)init;
- (id)initWithOutputDimensions:(struct { int x1; int x2; })arg1;
- (id)options;
- (struct __CVBuffer { }*)processPixelBuffer:(struct __CVBuffer { }*)arg1 withMetadata:(id)arg2;
- (int)processPixelBuffer:(struct __CVBuffer { }*)arg1 withMetadata:(id)arg2 outputPixelBuffer:(struct __CVBuffer { }*)arg3;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })processWithMetadata:(id)arg1;
- (void)reset;
- (id)roiHeatMapCounts;
- (void)setCameraOrientation:(int)arg1;
- (void)setOptions:(id)arg1;
- (void)setZoomLevel:(float)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })warpBoundingBoxInFrameCoordinatesToDisplayCoordinates:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (float)zoomLevel;

@end
