/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProductKit.framework/ProductKit
 */

@interface _TtCC10ProductKit7Product18MobileAssetManager : _TtCC10ProductKit7Product12AssetManager {
    void downloadOptions;
}

@end
