/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProductKit.framework/ProductKit
 */

@interface ProductKitCatalog : NSObject {
    ProductKitCatalogInternal * _underlyingObject;
}

@property (nonatomic, readonly) ProductKitCatalogInternal *underlyingObject;

+ (bool)isProductKitURL:(id)arg1;

- (void).cxx_destruct;
- (id)init;
- (void)selectTestingAssetManager;
- (id)underlyingObject;
- (void)updateCatalogWithCompletionHandler:(id /* block */)arg1;
- (void)watchBandFilesForFeatureWithURL:(id)arg1 featureString:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)watchBandImageForFeatureWithURL:(id)arg1 featureString:(id)arg2 completionHandler:(id /* block */)arg3;
- (void)watchBandStringForFeatureWithURL:(id)arg1 featureString:(id)arg2 completionHandler:(id /* block */)arg3;

@end
