/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Transparency.framework/Transparency
 */

@interface KTLogNetworkRequest : TransparencyNetworkRequest {
    NSString * _application;
    NSData * _data;
    bool  _isGET;
    double  _timeout;
    NSURL * _url;
    NSUUID * _uuid;
}

@property (retain) NSString *application;
@property (retain) NSData *data;
@property bool isGET;
@property double timeout;
@property (retain) NSURL *url;
@property (retain) NSUUID *uuid;

+ (bool)addAccountAuthentication:(id)arg1 error:(id*)arg2;
+ (void)addDeviceAuthentication:(id)arg1 signature:(id)arg2 timestamp:(id)arg3 certs:(id)arg4;

- (void).cxx_destruct;
- (id)application;
- (id)createGETRequestForURL:(id)arg1 timeout:(double)arg2 error:(id*)arg3;
- (id)createPOSTRequestForURL:(id)arg1 timeout:(double)arg2 contents:(id)arg3 authentication:(id)arg4 completionHandler:(id /* block */)arg5;
- (void)createRequestForAuthentication:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)data;
- (id)initGETWithURL:(id)arg1 application:(id)arg2;
- (id)initPOSTWithURL:(id)arg1 data:(id)arg2 uuid:(id)arg3 application:(id)arg4;
- (bool)isGET;
- (void)setApplication:(id)arg1;
- (void)setData:(id)arg1;
- (void)setIsGET:(bool)arg1;
- (void)setTimeout:(double)arg1;
- (void)setUrl:(id)arg1;
- (void)setUuid:(id)arg1;
- (double)timeout;
- (id)url;
- (id)uuid;

@end
