/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Transparency.framework/Transparency
 */

@interface TransparencyAuthentication : NSObject {
    struct __SecKey { } * _bik;
    NSArray * _certificates;
    bool  _isSupported;
    NSObject<OS_dispatch_group> * _issuanceGroup;
    NSObject<OS_dispatch_queue> * _issuanceQueue;
    NSDate * _lastLocalFetchTime;
    bool  _outstandingRemoteFetchSignal;
    NSObject<OS_dispatch_workloop> * _workloop;
}

@property struct __SecKey { }*bik;
@property (retain) NSArray *certificates;
@property bool isSupported;
@property (retain) NSObject<OS_dispatch_group> *issuanceGroup;
@property (retain) NSObject<OS_dispatch_queue> *issuanceQueue;
@property (retain) NSDate *lastLocalFetchTime;
@property bool outstandingRemoteFetchSignal;
@property (retain) NSObject<OS_dispatch_workloop> *workloop;

- (void).cxx_destruct;
- (struct __SecKey { }*)bik;
- (id)certificates;
- (void)dealloc;
- (void)deviceIdentityIssuerCert:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)initWithWorkloop:(id)arg1;
- (bool)isSupported;
- (id)issuanceGroup;
- (id)issuanceQueue;
- (void)issueCert:(bool)arg1 completionHandler:(id /* block */)arg2;
- (id)lastLocalFetchTime;
- (bool)outstandingRemoteFetchSignal;
- (void)setBik:(struct __SecKey { }*)arg1;
- (void)setCertificates:(id)arg1;
- (void)setIsSupported:(bool)arg1;
- (void)setIssuanceGroup:(id)arg1;
- (void)setIssuanceQueue:(id)arg1;
- (void)setLastLocalFetchTime:(id)arg1;
- (void)setOutstandingRemoteFetchSignal:(bool)arg1;
- (void)setWorkloop:(id)arg1;
- (void)signData:(id)arg1 fetchNow:(bool)arg2 completionHandler:(id /* block */)arg3;
- (void)signData:(id)arg1 key:(struct __SecKey { }*)arg2 certs:(id)arg3 completionHandler:(id /* block */)arg4;
- (void)signDataWithTimestamp:(id)arg1 fetchNow:(bool)arg2 completionHandler:(id /* block */)arg3;
- (id)workloop;

@end
