/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PodcastsFoundation.framework/PodcastsFoundation
 */

@interface MTServerPodcast : PodcastsFoundation.ServerPodcastBase {
    void episodes;
}

- (void).cxx_destruct;
- (id)toFeed;

@end
