/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.TagFeedViewerEventHandler : _TtCs12_SwiftObject {
    void channelUpsellManager;
    void delegate;
    void interactor;
    void router;
    void tracker;
}

@end
