/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.FeatureAvailability : _TtCs12_SwiftObject <TSFeatureAvailabilityType> {
    void featureAvailabilityProvider;
}

@property (nonatomic, readonly) bool allowInAppMessages;
@property (nonatomic, readonly) bool allowSharingAlways;
@property (nonatomic, readonly) bool allowStateRestorationOniPhone;
@property (nonatomic, readonly) bool appleMagazineContent;
@property (nonatomic, readonly) bool narrativeAudio;
@property (nonatomic, readonly) bool searchFeaturedStoriesEnabled;
@property (nonatomic, readonly) bool searchInExplicitViewEnabled;
@property (nonatomic, readonly) bool useContinueReading;
@property (nonatomic, readonly) bool useFlexiblePaywall;
@property (nonatomic, readonly) bool useNewsArticleSearch;

- (bool)allowInAppMessages;
- (bool)allowSharingAlways;
- (bool)allowStateRestorationOniPhone;
- (bool)appleMagazineContent;
- (bool)narrativeAudio;
- (bool)searchFeaturedStoriesEnabled;
- (bool)searchInExplicitViewEnabled;
- (bool)useContinueReading;
- (bool)useFlexiblePaywall;
- (bool)useNewsArticleSearch;

@end
