/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.ContinueReadingEligibilityProcessor : _TtCs12_SwiftObject {
    void featureAvailability;
    void headlineService;
    void readingHistory;
    void subscriptionList;
}

@end
