/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI2.framework/NewsUI2
 */

@interface NewsUI2.MyMagazinesGridModelLoader : _TtCs12_SwiftObject {
    void $__lazy_storage_$_lazyInitializingPromise;
    void _sort;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  activity;
    void delegate;
    void issueModelFactory;
    void issueService;
    void store;
    void tagService;
}

@end
