/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Preferences.framework/Preferences
 */

@interface PSAnalytics : NSObject

+ (void)trackingStateOfRequestForSpecificApp:(bool)arg1 view:(id)arg2;

@end
