/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ProactiveContextClient.framework/ProactiveContextClient
 */

@interface ATXModeCalendarFeaturizer : NSObject <ATXModeFeaturizer> {
    <ATXModeFeaturizerDelegate> * _delegate;
    NSHashTable * _timers;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <ATXModeFeaturizerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_addTimerForDate:(id)arg1;
- (void)_eventsDidChange:(id)arg1;
- (id)_fetchEventsForDay;
- (bool)_hasAnyEventsIn:(id)arg1 now:(id)arg2;
- (bool)_isLikelyAWorkCalendar:(id)arg1;
- (void)_setFeaturesForEventsCurrentlyIn:(id)arg1 now:(id)arg2 featureSet:(id)arg3;
- (void)beginListening;
- (void)dealloc;
- (id)delegate;
- (id)init;
- (id)provideFeatures;
- (void)setDelegate:(id)arg1;
- (void)stopListening;

@end
