/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PromotedContent.framework/PromotedContent
 */

@interface PromotedContent.SearchLandingPageRepresentation : APPCContentRepresentation {
    void adamId;
    void clientRequestId;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  iAdId;
    void impressionId;
    void installAttribution;
    void journeyRelayAdGroupId;
    void journeyRelayCampaignId;
    void metadata;
    void parentAppCheckEnabled;
    void rank;
    void storeFront;
    void storeFrontLocale;
    void timeToDisplay;
}

- (void).cxx_destruct;

@end
