/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface _MPCDebugOverlayItemView : UIView {
    UIImageView * _image;
    MPCDebugOverlayItem * _item;
    UILabel * _label;
    UILabel * _text;
}

@property (nonatomic, readonly) MPCDebugOverlayItem *item;

- (void).cxx_destruct;
- (id)description;
- (id)initWithOverlayItem:(id)arg1;
- (id)item;
- (void)layoutSubviews;
- (struct CGSize { double x1; double x2; })sizeThatFits:(struct CGSize { double x1; double x2; })arg1;

@end
