/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface MPCDebugOverlayArtworkToken : NSObject <MPArtworkDataSourceVisualIdenticality> {
    MPArtworkCatalog * _baseArtworkCatalog;
    NSArray * _overlayItems;
}

@property (nonatomic, readonly) MPArtworkCatalog *baseArtworkCatalog;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) NSArray *overlayItems;
@property (readonly) Class superclass;

+ (id)tokenWithCatalog:(id)arg1 overlayItems:(id)arg2;

- (void).cxx_destruct;
- (id)_init;
- (id)baseArtworkCatalog;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)overlayItems;
- (id)stringRepresentation;

@end
