/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface MPCDebugOverlayItem : NSObject {
    MPCDebugOverlayItemDisplay * _fullDisplay;
    MPCDebugOverlayItemDisplay * _shortDisplay;
}

@property (nonatomic, readonly) MPCDebugOverlayItemDisplay *fullDisplay;
@property (nonatomic, readonly) MPCDebugOverlayItemDisplay *shortDisplay;

+ (id)itemWithFullDisplay:(id)arg1;
+ (id)itemWithShortDisplay:(id)arg1;
+ (id)itemWithShortDisplay:(id)arg1 fullDisplay:(id)arg2;

- (void).cxx_destruct;
- (id)_init;
- (id)description;
- (id)fullDisplay;
- (id)shortDisplay;

@end
