/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface MPCModelGenericAVItemLocalFileLoadOperation : MPAsyncOperation {
    MPCModelGenericAVItemAssetLoadProperties * _assetLoadProperties;
    bool  _requirePreferredAssetQuality;
    id /* block */  _responseHandler;
}

@property (nonatomic, retain) MPCModelGenericAVItemAssetLoadProperties *assetLoadProperties;
@property (nonatomic) bool requirePreferredAssetQuality;
@property (nonatomic, copy) id /* block */ responseHandler;

- (void).cxx_destruct;
- (long long)_loadedAudioAssetTypeForFileAsset:(id)arg1;
- (id)assetLoadProperties;
- (void)execute;
- (bool)isHLSFileAsset:(id)arg1;
- (bool)requirePreferredAssetQuality;
- (id /* block */)responseHandler;
- (void)setAssetLoadProperties:(id)arg1;
- (void)setRequirePreferredAssetQuality:(bool)arg1;
- (void)setResponseHandler:(id /* block */)arg1;

@end
