/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface MPCPlayerAudioRoute : NSObject <MPCPlaybackEngineEventPayloadValueJSONConvertible, NSCopying> {
    bool  _isSpatializationEnabled;
    NSString * _name;
    MPNowPlayingInfoAudioRoute * _nowPlayingAudioRoute;
    bool  _supportsSpatialization;
    long long  _type;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSDictionary *dictionaryRepresentation;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSString *humanDescription;
@property (nonatomic, readonly) bool isDeviceSpeaker;
@property (nonatomic, readonly) bool isSpatializationEnabled;
@property (nonatomic, readonly, copy) NSString *name;
@property (nonatomic, readonly) MPNowPlayingInfoAudioRoute *nowPlayingAudioRoute;
@property (readonly) Class superclass;
@property (nonatomic, readonly) bool supportsSpatialization;
@property (nonatomic, readonly) long long type;

+ (id)payloadValueFromJSONValue:(id)arg1;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (id)humanDescription;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithNowPlayingInfoAudioRoute:(id)arg1;
- (id)initWithRoute:(id)arg1 headTrackedSpatialAudioEnabled:(bool)arg2;
- (bool)isDeviceSpeaker;
- (bool)isSpatializationEnabled;
- (id)mpc_jsonValue;
- (id)name;
- (id)nowPlayingAudioRoute;
- (bool)supportsSpatialization;
- (long long)type;

@end
