/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaPlaybackCore.framework/MediaPlaybackCore
 */

@interface MPCPlayerItemConfigurator : NSObject <MPAVRoutingControllerDelegate, MPMediaControlsSpatialAudioControllerDelegate> {
    MPCModelGenericAVItem * _currenItem;
    long long  _defaultEQPresetType;
    MPCPlaybackEngine * _playbackEngine;
    MPAVRoutingController * _routingController;
    MPMediaControlsSpatialAudioController * _spatialAudioController;
    <MFPlaybackStackController><MFQueueManagement> * _stackController;
    MPCMediaFoundationTranslator * _translator;
    NSObject<OS_dispatch_source> * _userDefaultsDebouncer;
}

@property (nonatomic, readonly) MPCModelGenericAVItem *currenItem;
@property (nonatomic, readonly) MPCPlayerAudioRoute *currentAudioRoute;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) long long defaultEQPresetType;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) MPCPlaybackEngine *playbackEngine;
@property (nonatomic, readonly) MPAVRoutingController *routingController;
@property (nonatomic, readonly) MPMediaControlsSpatialAudioController *spatialAudioController;
@property (nonatomic, readonly) <MFPlaybackStackController><MFQueueManagement> *stackController;
@property (readonly) Class superclass;
@property (nonatomic, readonly) MPCMediaFoundationTranslator *translator;
@property (nonatomic, retain) NSObject<OS_dispatch_source> *userDefaultsDebouncer;

- (void).cxx_destruct;
- (id)_HLSMetadataForAsset:(id)arg1 error:(id*)arg2;
- (id)_audioFormatsDictionaryWithHLSMetadata:(id)arg1;
- (id)_audioFormatsDictionaryWithHLSMetadataFromAsset:(id)arg1 error:(id*)arg2;
- (void)_playbackUserDefaultsEQPresetDidChangeNotification:(id)arg1;
- (void)_preferredResolutionDidChange:(id)arg1;
- (void)_setupNotifications;
- (void)_setupPlayer;
- (void)_setupQueueItemForHLSPlayback:(id)arg1 error:(id*)arg2;
- (void)_setupRoutingController;
- (void)_setupSpatialAudioController;
- (void)_updatePreferredAudioFormatIfRequiredForItem:(id)arg1 route:(id)arg2;
- (void)configureQueuePlayerItem:(id)arg1 error:(id*)arg2;
- (id)currenItem;
- (id)currentAudioRoute;
- (id)currentItem;
- (void)dealloc;
- (long long)defaultEQPresetType;
- (id)initWithPlaybackEngine:(id)arg1 stackController:(id)arg2 translator:(id)arg3;
- (void)mediaControlsSpatialAudioController:(id)arg1 didChangeHeadTrackedSpatialAudioEnabled:(bool)arg2;
- (id)playbackEngine;
- (void)processAudioQualityChanges;
- (id)routingController;
- (void)routingController:(id)arg1 pickedRoutesDidChange:(id)arg2;
- (void)setDefaultEQPresetType:(long long)arg1;
- (void)setUserDefaultsDebouncer:(id)arg1;
- (void)setupDefaultsDebouncer;
- (id)spatialAudioController;
- (id)stackController;
- (void)tearDownDefaultsDebouncer;
- (id)translator;
- (void)updatePlayerConfiguration;
- (id)userDefaultsDebouncer;

@end
