/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFCompactPlatterViewController : UIViewController <UIGestureRecognizerDelegate, UIScrollViewDelegate, WFCompactPlatterPresentation, WFCompactPlatterSizingDelegate> {
    UIViewController * _contentViewController;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _gestureOriginFrame;
    struct CGPoint { 
        double x; 
        double y; 
    }  _gestureTranslation;
    struct CGSize { 
        double width; 
        double height; 
    }  _minimumPlatterSize;
    UIPanGestureRecognizer * _panGesture;
    <WFCompactPlatterContentContainer> * _platterContentContainer;
    bool  _platterHeightAnimationsDisabled;
    WFCompactPlatterView * _platterView;
    UIScrollView * _scrollView;
    WFCompactPlatterTransitioningDelegate * _wf_transitioningDelegate;
}

@property (nonatomic, retain) UIViewController *contentViewController;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } gestureOriginFrame;
@property (nonatomic) struct CGPoint { double x1; double x2; } gestureTranslation;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool isInteractingWithPlatter;
@property (nonatomic) struct CGSize { double x1; double x2; } minimumPlatterSize;
@property (nonatomic, retain) UIPanGestureRecognizer *panGesture;
@property (nonatomic) <WFCompactPlatterContentContainer> *platterContentContainer;
@property (nonatomic) bool platterHeightAnimationsDisabled;
@property (nonatomic, readonly) WFCompactPlatterView *platterView;
@property (nonatomic) UIScrollView *scrollView;
@property (readonly) Class superclass;
@property (nonatomic, retain) WFCompactPlatterTransitioningDelegate *wf_transitioningDelegate;

- (void).cxx_destruct;
- (bool)_canShowWhileLocked;
- (bool)allowsInteractiveDismissal;
- (void)animateInteractive:(bool)arg1 animationBlock:(id /* block */)arg2 completion:(id /* block */)arg3;
- (double)contentHeightForWidth:(double)arg1 withMaximumVisibleHeight:(double)arg2;
- (id)contentViewController;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })gestureOriginFrame;
- (bool)gestureRecognizerShouldBegin:(id)arg1;
- (struct CGPoint { double x1; double x2; })gestureTranslation;
- (void)handlePan:(id)arg1;
- (id)init;
- (void)invalidateContentSize;
- (void)invalidatePlatterSize;
- (bool)isInteractingWithPlatter;
- (void)loadView;
- (double)maximumExpectedVisibleContentHeight;
- (struct CGSize { double x1; double x2; })minimumPlatterSize;
- (id)panGesture;
- (id)platterContentContainer;
- (bool)platterHeightAnimationsDisabled;
- (double)platterHeightForWidth:(double)arg1 withMaximumHeight:(double)arg2;
- (void)platterInteractionDidBegin;
- (void)platterInteractionDidFinish;
- (void)platterInteractionRequestedDismissal;
- (id)platterView;
- (void)platterViewDidInvalidateSize:(id)arg1;
- (void)scrollToTopAnimated:(bool)arg1;
- (id)scrollView;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setContentViewController:(id)arg1;
- (void)setGestureOriginFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setGestureTranslation:(struct CGPoint { double x1; double x2; })arg1;
- (void)setMinimumPlatterSize:(struct CGSize { double x1; double x2; })arg1;
- (void)setPanGesture:(id)arg1;
- (void)setPlatterContentContainer:(id)arg1;
- (void)setPlatterHeightAnimationsDisabled:(bool)arg1;
- (void)setScrollView:(id)arg1;
- (void)setTransitioningDelegate:(id)arg1;
- (void)setWf_transitioningDelegate:(id)arg1;
- (void)systemLayoutFittingSizeDidChangeForChildContentContainer:(id)arg1;
- (void)updateContentSizeAndPlatterPosition;
- (void)updatePlatterPosition;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)wf_transitioningDelegate;

@end
