/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowUI.framework/WorkflowUI
 */

@interface WFSingleStepHomeScreenShortcutCompletionDialogViewController : WFCompactDialogViewController {
    NSTimer * _timer;
}

@property (nonatomic, retain) NSTimer *timer;

- (void).cxx_destruct;
- (bool)allowsInteractiveDismissal;
- (void)loadView;
- (void)platterInteractionDidBegin;
- (void)platterInteractionDidFinish;
- (id)responseForInteractiveDismissal;
- (void)setTimer:(id)arg1;
- (void)startTimer;
- (id)timer;
- (void)viewDidAppear:(bool)arg1;

@end
