/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NearField.framework/NearField
 */

@interface NFDigitalCarKeySession : NFSession <NFContactlessPaymentSessionCallbacks, NFSessionDelegate, SESDCKSessionDelegate> {
    NFApplet * _activeApplet;
    NSString * _activeKey;
    NSDictionary * _appletsById;
    bool  _cardEmulationStarted;
    NFApplet * _defaultApplet;
    NSData * _deferredAuthData;
    <NFDigitalCarKeySessionDelegate> * _delegate;
    bool  _fieldNotificationSent;
    SESDCKSession * _sesdSession;
}

@property (readonly) NFApplet *activeApplet;
@property (readonly) NSString *activeKey;
@property (nonatomic, retain) NSDictionary *appletsById;
@property bool cardEmulationStarted;
@property (readonly, copy) NSString *debugDescription;
@property (readonly) NFApplet *defaultApplet;
@property (retain) NSData *deferredAuthData;
@property <NFDigitalCarKeySessionDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (nonatomic) bool fieldNotificationSent;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long rkeSessionState;
@property (nonatomic, retain) SESDCKSession *sesdSession;
@property (readonly) Class superclass;
@property (nonatomic, readonly) bool supportsSecureRanging;
@property (nonatomic, readonly) NSDictionary *vehicleState;

- (void).cxx_destruct;
- (id)_getAppletsFromNFCD;
- (id)activateWithToken:(id)arg1;
- (id)activeApplet;
- (id)activeKey;
- (id)allApplets;
- (id)appletWithIdentifier:(id)arg1;
- (id)appletsById;
- (id)cancelRKEAction:(unsigned long long)arg1;
- (bool)cardEmulationStarted;
- (id)createSessionHandoffToken:(id*)arg1;
- (id)defaultApplet;
- (id)deferredAuthData;
- (id)delegate;
- (void)didDetectField:(bool)arg1;
- (void)didDetectFieldNotification:(id)arg1;
- (void)didEndTransaction:(id)arg1;
- (void)didEndUnexpectedly;
- (void)didExpireTransactionForApplet:(id)arg1;
- (void)didExpressModeStateChange:(unsigned int)arg1 withObject:(id)arg2;
- (void)didFailDeferredAuthorization;
- (void)didFelicaStateChange:(id)arg1;
- (void)didReceiveActivityTimeout:(id)arg1;
- (void)didReceivePendingServerRequest;
- (void)didSelectApplet:(id)arg1;
- (void)didStartSession:(id)arg1;
- (void)didStartTransaction:(id)arg1;
- (void)endSession;
- (void)endSessionWithCompletion:(id /* block */)arg1;
- (bool)fieldNotificationSent;
- (id)getRKEActionsInProgress;
- (bool)getSignedMessage:(id)arg1 authorization:(id)arg2 reply:(id /* block */)arg3;
- (void)handleSessionResumed;
- (void)handleSessionSuspended:(id)arg1;
- (id)init;
- (unsigned long long)rkeSessionState;
- (bool)sendPassthroughMessage:(id)arg1 reply:(id /* block */)arg2;
- (id)sendRKEAction:(unsigned long long)arg1 authorization:(id)arg2;
- (id)sendRKEActions:(id)arg1 authorization:(id)arg2;
- (bool)sendSignedPassthroughMessage:(id)arg1 authorization:(id)arg2 reply:(id /* block */)arg3;
- (void)sesSession:(id)arg1 event:(id)arg2;
- (id)sesdSession;
- (bool)setActiveApplet:(id)arg1 key:(id)arg2 outError:(id*)arg3;
- (void)setAppletsById:(id)arg1;
- (id)setAuthorization:(id)arg1;
- (void)setCardEmulationStarted:(bool)arg1;
- (void)setDeferredAuthData:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setFieldNotificationSent:(bool)arg1;
- (void)setSesdSession:(id)arg1;
- (bool)startCardEmulationAuthorization:(id)arg1 deferred:(bool)arg2 error:(id*)arg3;
- (bool)stopCardEmulation:(id*)arg1;
- (bool)supportsSecureRanging;
- (id)vehicleState;

@end
