/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VoiceTriggerUI.framework/VoiceTriggerUI
 */

@interface VTUIVoiceSelectionProximityView : VTUIProximityView <VTUIVoiceSelectionContaining> {
    bool  _allowsRandomVoiceSelection;
    UIButton * _chooseRandomVoiceButton;
    NSArray * _constraints;
    VTUIProximityContainerView * _containerView;
    UIView * _contentView;
    UIButton * _continueButton;
    UIButton * _dismissButton;
    UIView * _footerView;
    SUICOrbView * _orbView;
    UILabel * _titleLabel;
    VTUIStyle * _vtStyle;
}

@property (nonatomic, retain) UIButton *chooseRandomVoiceButton;
@property (nonatomic, retain) NSArray *constraints;
@property (nonatomic, retain) UIButton *continueButton;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) UIButton *dismissButton;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_setupConstraintsToSize:(struct CGSize { double x1; double x2; })arg1;
- (void)_setupContentWithTitle:(id)arg1;
- (void)animateOrbViewToOffWithCompletion:(id /* block */)arg1;
- (id)chooseRandomVoiceButton;
- (id)constraints;
- (id)continueButton;
- (void)dealloc;
- (id)dismissButton;
- (id)initWithTitle:(id)arg1 allowsRandomVoiceSelection:(bool)arg2;
- (struct CGSize { double x1; double x2; })intrinsicContentSize;
- (void)setChooseRandomVoiceButton:(id)arg1;
- (void)setConstraints:(id)arg1;
- (void)setContentView:(id)arg1;
- (void)setContinueButton:(id)arg1;
- (void)setDismissButton:(id)arg1;
- (void)setInputPowerLevel:(float)arg1;
- (void)setOutputPowerLevel:(float)arg1;
- (void)setShouldHideCompactBackgroundCardView:(bool)arg1;
- (id)viewConstraints;

@end
