/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/Vision.framework/Vision
 */

@interface VNRecognizeDocumentElementsRequestConfiguration : VNImageBasedRequestConfiguration {
    VNRecognizeDocumentElementsRequestElementConfiguration * _machineReadableCodeElements;
    VNRecognizeDocumentElementsRequestElementConfiguration * _textElements;
}

@property (readonly) VNRecognizeDocumentElementsRequestElementConfiguration *machineReadableCodeElements;
@property (readonly) VNRecognizeDocumentElementsRequestElementConfiguration *textElements;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initWithRequestClass:(Class)arg1;
- (id)machineReadableCodeElements;
- (id)textElements;

@end
