/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriUICardKitProviderSupport.framework/SiriUICardKitProviderSupport
 */

@interface SCKPMessageCardSectionAttachmentView : UIView {
    UIImageView * _imageView;
    LPLinkView * _linkView;
}

@property (retain) UIImageView *imageView;
@property (retain) LPLinkView *linkView;

- (void).cxx_destruct;
- (void)_loadAttachmentFromFileURL:(id)arg1;
- (void)_loadRemoteURL:(id)arg1;
- (void)_loadURL:(id)arg1;
- (id)_thumbnailImageForVideoURL:(id)arg1;
- (id)imageView;
- (id)initWithURL:(id)arg1;
- (void)layoutSubviews;
- (id)linkView;
- (void)setImageView:(id)arg1;
- (void)setLinkView:(id)arg1;

@end
