/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsUI.framework/NewsUI
 */

@interface NUSafariViewController : UIViewController <SFSafariViewControllerDelegate> {
    SFSafariViewController * _safariViewController;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) SFSafariViewController *safariViewController;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)initWithURL:(id)arg1;
- (id)safariViewController;
- (id)safariViewController:(id)arg1 excludedActivityTypesForURL:(id)arg2 title:(id)arg3;
- (void)safariViewControllerDidFinish:(id)arg1;
- (void)setPreviewing:(bool)arg1;
- (void)setSafariViewController:(id)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
