/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
 */

@interface SBBannerSourceListenerPresentableViewController : BNBannerSourceListenerPresentableViewController <SBBarSwipeAffordanceObserver, SBUIBannerHomeGestureParticipant> {
    <SBUIBannerHomeGestureContext> * _bannerHomeGestureContext;
    NSMutableArray * _wantsHomeAffordanceActionsAwaitingResponse;
}

@property (nonatomic) <SBUIBannerHomeGestureContext> *bannerHomeGestureContext;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)bannerHomeGestureContext;
- (void)homeGestureOwnershipDidChange:(bool)arg1;
- (void)homeGesturePerformedForBarSwipeAffordanceView:(id)arg1;
- (bool)isDraggingDismissalEnabled;
- (bool)isDraggingInteractionEnabled;
- (void)presentableWillDisappearAsBanner:(id)arg1 withReason:(id)arg2;
- (void)scene:(id)arg1 didReceiveActions:(id)arg2;
- (void)setBannerHomeGestureContext:(id)arg1;
- (void)viewDidLoad;

@end
