/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TrialServer.framework/TrialServer
 */

@interface TRIExperimentBaseTaskGuardedData : NSObject {
    NSMutableArray * dimensions;
    bool  logAsRollout;
    NSMutableArray * metrics;
}

- (void).cxx_destruct;

@end
