/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchAds.framework/SearchAds
 */

@interface ADSearchObject : NSObject {
    double  _SLA;
    NSArray * _advertisements;
    ADDESRecordsManager * _desRecordManager;
    NSString * _deviceRequestID;
    NSError * _error;
    NSArray * _organics;
    NSArray * _organicsIds;
    APOdmlReranker * _reranker;
    NSString * _routingInfoData;
    NSString * _sponsoredSearchRequestData;
    NSString * _userTargetingID;
}

@property (nonatomic) double SLA;
@property (nonatomic, retain) NSArray *advertisements;
@property (nonatomic, retain) ADDESRecordsManager *desRecordManager;
@property (nonatomic, retain) NSString *deviceRequestID;
@property (nonatomic, retain) NSError *error;
@property (nonatomic, retain) NSArray *organics;
@property (nonatomic, retain) NSArray *organicsIds;
@property (nonatomic, retain) APOdmlReranker *reranker;
@property (nonatomic, retain) NSString *routingInfoData;
@property (nonatomic, retain) NSString *sponsoredSearchRequestData;
@property (nonatomic, retain) NSString *userTargetingID;

- (void).cxx_destruct;
- (double)SLA;
- (id)advertisements;
- (id)desRecordManager;
- (id)deviceRequestID;
- (id)error;
- (id)init;
- (id)initWithSponsoredSearchRequestData:(id)arg1 routingInfoData:(id)arg2 deviceRequestID:(id)arg3 userTargetingID:(id)arg4 error:(id)arg5;
- (void)orderedAds:(id /* block */)arg1;
- (id)organics;
- (id)organicsIds;
- (id)reranker;
- (id)routingInfoData;
- (long long)selectAdResponse;
- (void)setAdvertisements:(id)arg1;
- (void)setDesRecordManager:(id)arg1;
- (void)setDeviceRequestID:(id)arg1;
- (void)setError:(id)arg1;
- (void)setOrganics:(id)arg1;
- (void)setOrganicsIds:(id)arg1;
- (void)setReranker:(id)arg1;
- (void)setRoutingInfoData:(id)arg1;
- (void)setSLA:(double)arg1;
- (void)setSponsoredSearchRequestData:(id)arg1;
- (void)setUserTargetingID:(id)arg1;
- (id)sponsoredSearchRequestData;
- (id)userTargetingID;

@end
