/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFAddNewContactAction : WFAction

+ (void)contactFromParameters:(id)arg1 completionHandler:(id /* block */)arg2;
+ (id)userInterfaceProtocol;
+ (id)userInterfaceXPCInterface;

- (void)runAsynchronouslyWithInput:(id)arg1;
- (void)runWithoutUI;

@end
