/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFConvertTimeZoneAction : WFAction

- (void)runAsynchronouslyWithInput:(id)arg1;

@end
