/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFScreenshotAccessResource : WFAccessResource

+ (bool)isSystemResource;

- (unsigned long long)globalLevelStatus;
- (id)icon;
- (id)localizedWorkflowLevelDeniedStatusMessage;
- (id)localizedWorkflowLevelMessageTemplate;
- (id)localizedWorkflowLevelNotDeterminedStatusMessage;
- (id)localizedWorkflowLevelPromptTemplate;
- (id)name;

@end
