/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ActionKit.framework/ActionKit
 */

@interface WFWallpaperModificationAccessResource : WFAccessResource

+ (bool)isSystemResource;

- (unsigned long long)globalLevelStatus;
- (id)localizedAccessResourceErrorString;
- (id)localizedErrorReasonForGlobalLevelStatus:(unsigned long long)arg1;
- (id)localizedImportErrorReasonForGlobalLevelStatus:(unsigned long long)arg1;
- (id)name;
- (id)protectedResourceDescription;
- (unsigned long long)workflowLevelStatus;

@end
