/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServices.framework/AppleMediaServices
 */

@interface AMSCampaignAttributionResult : NSObject {
    ACAccount * _account;
    NSURL * _redirectURL;
}

@property (nonatomic, retain) ACAccount *account;
@property (nonatomic, retain) NSURL *redirectURL;

- (void).cxx_destruct;
- (id)account;
- (id)initWithURL:(id)arg1;
- (id)redirectURL;
- (void)setAccount:(id)arg1;
- (void)setRedirectURL:(id)arg1;

@end
