/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/LinkPresentation.framework/LinkPresentation
 */

@interface LPAudioPlayButtonStyle : NSObject {
    LPAudioPlayButtonTheme * _appleMusicTheme;
    LPAudioPlayButtonTheme * _audioBookTheme;
    LPAudioPlayButtonTheme * _defaultTheme;
    LPAudioPlayButtonTheme * _lyricExcerptTheme;
    LPAudioPlayButtonTheme * _podcastsTheme;
    LPSize * _size;
}

@property (nonatomic, readonly, retain) LPAudioPlayButtonTheme *appleMusicTheme;
@property (nonatomic, readonly, retain) LPAudioPlayButtonTheme *audioBookTheme;
@property (nonatomic, readonly, retain) LPAudioPlayButtonTheme *defaultTheme;
@property (nonatomic, readonly, retain) LPAudioPlayButtonTheme *lyricExcerptTheme;
@property (nonatomic, readonly, retain) LPAudioPlayButtonTheme *podcastsTheme;
@property (nonatomic, retain) LPSize *size;

- (void).cxx_destruct;
- (id)appleMusicTheme;
- (id)audioBookTheme;
- (id)defaultTheme;
- (id)init;
- (id)lyricExcerptTheme;
- (id)podcastsTheme;
- (void)setSize:(id)arg1;
- (id)size;

@end
