/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKFetchDeviceGestaltRequest : CATTaskRequest

+ (bool)supportsSecureCoding;
+ (Class)whitelistedClassForResultObject;

@end
