/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ClassroomKit.framework/ClassroomKit
 */

@interface CRKIDSWaitForAccountReadyOperation : CATOperation {
    NSObject<CRKIDSLocalPrimitives> * _IDSLocalPrimitives;
    NSMutableDictionary * _observedAccountsByLoginID;
    bool  _observingKnownAccountChanges;
    NSString * _sourceAppleID;
}

@property (nonatomic, readonly) NSObject<CRKIDSLocalPrimitives> *IDSLocalPrimitives;
@property (nonatomic, readonly) NSMutableDictionary *observedAccountsByLoginID;
@property (getter=isObservingKnownAccountChanges, nonatomic) bool observingKnownAccountChanges;
@property (nonatomic, readonly, copy) NSString *sourceAppleID;

- (void).cxx_destruct;
- (id)IDSLocalPrimitives;
- (void)beginObservingActiveChangesForAccount:(id)arg1;
- (void)beginObservingKnownAccountChanges;
- (void)cancel;
- (void)endObservingActiveChangesForAccount:(id)arg1;
- (void)endObservingAllAccounts;
- (void)endObservingKnownAccountChanges;
- (id)initWithIDSLocalPrimitives:(id)arg1 sourceAppleID:(id)arg2;
- (bool)isAsynchronous;
- (bool)isObservingKnownAccountChanges;
- (void)knownAccountsDidChange;
- (void)main;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)observedAccountDidChange:(id)arg1;
- (id)observedAccountsByLoginID;
- (void)run;
- (void)setObservingKnownAccountChanges:(bool)arg1;
- (id)sourceAppleID;

@end
