/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/HomeKit.framework/HomeKit
 */

@interface HMAccessorySetupCompletedInfo : NSObject <NSSecureCoding> {
    NSArray * _addedAccessoryUUIDs;
    NSString * _homeUUID;
}

@property (readonly, copy) NSArray *addedAccessoryUUIDs;
@property (readonly, copy) NSString *homeUUID;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)addedAccessoryUUIDs;
- (void)encodeWithCoder:(id)arg1;
- (id)homeUUID;
- (id)initWithCoder:(id)arg1;
- (id)initWithHomeUUID:(id)arg1 addedAccessoryUUIDs:(id)arg2;

@end
