/* Generated by RuntimeBrowser.
 */

@protocol _MFMailCompositionContextDelegate

@required

- (void)didCompleteAutosaveDataFetchForCompositionContext:(_MFMailCompositionContext *)arg1 legacyMessage:(MFMailMessage *)arg2 error:(NSError *)arg3;
- (void)messageDidChangeForCompositionContext:(_MFMailCompositionContext *)arg1 newMessage:(EMMessage *)arg2;

@end
