/* Generated by RuntimeBrowser.
 */

@protocol _SFNavigationBarItemObserver <NSObject>

@optional

- (void)navigationBarItemDidUpdateCustomPlaceholderText:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateFormatButtonSelected:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateMediaStateIcon:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateOverrideBarStyleForSecurityWarning:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateProgressView:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateShowsLockIcon:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateShowsNotSecureAnnotation:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateShowsPageFormatButton:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateShowsReaderButton:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateShowsSearchIndicator:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateShowsStopReloadButtons:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateShowsTranslationButton:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateShowsTranslationIcon:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateStopReloadButtonShowsStop:(_SFNavigationBarItem *)arg1;
- (void)navigationBarItemDidUpdateText:(_SFNavigationBarItem *)arg1;

@end
