/* Generated by RuntimeBrowser.
 */

@protocol AFHomeAccessoryInfoMutating <NSObject>

@required

- (void)setAssistantIdentifier:(NSString *)arg1;
- (void)setModel:(NSString *)arg1;
- (void)setName:(NSString *)arg1;
- (void)setRoomName:(NSString *)arg1;
- (void)setUniqueIdentifier:(NSUUID *)arg1;

@end
