/* Generated by RuntimeBrowser.
 */

@protocol ATXModeEntityScorerProtocol

@required

- (NSArray *)rankedAppsForMode:(unsigned long long)arg1;
- (NSArray *)rankedContactsForMode:(unsigned long long)arg1;
- (void)scoreApps:(NSArray *)arg1 mode:(unsigned long long)arg2;
- (void)scoreContacts:(NSArray *)arg1 mode:(unsigned long long)arg2;

@end
