/* Generated by RuntimeBrowser.
 */

@protocol CATIDSServiceConnectionDataAggregatorDelegate

@required

- (void)connectionDataAggregator:(id <CATIDSServiceConnectionDataAggregator>)arg1 aggregatedData:(NSData *)arg2 withNumber:(unsigned long long)arg3;
- (void)connectionDataAggregator:(id <CATIDSServiceConnectionDataAggregator>)arg1 timedOutWaitingForDataNumbers:(NSArray *)arg2;

@end
