/* Generated by RuntimeBrowser.
 */

@protocol CATIDSServiceConnectionKeepAliveTimerDelegate

@required

- (void)keepAliveTimerCrossedDeathThreshold:(CATIDSServiceConnectionKeepAliveTimer *)arg1;
- (void)keepAliveTimerCrossedWarningThreshold:(CATIDSServiceConnectionKeepAliveTimer *)arg1;

@end
