/* Generated by RuntimeBrowser.
 */

@protocol CKThrottlingCriteria <NSObject>

@optional

- (NSString *)applicationBundleIdentifierForContainerAccess;
- (CKContainerID *)containerID;
- (long long)databaseScope;
- (NSString *)functionName;
- (NSString *)operationGroupName;
- (int)operationType;
- (NSObject<NSFastEnumeration> *)relevantZoneIDs;
- (NSString *)serviceName;

@end
