/* Generated by RuntimeBrowser.
 */

@protocol CKVDatabaseRecord <NSObject>

@required

+ (CKVDatabaseDelete *)databaseDeleteWithOriginApp:(CKVOriginApp *)arg1 itemType:(long long)arg2;
+ (NSString *)genSQLCreateTable;
+ (id)recordFromDatabaseValueRow:(CKVDatabaseValueRow *)arg1;
+ (NSString *)tableName;

- (CKVDatabaseInsert *)databaseInsert;
- (NSUUID *)recordId;

@end
