/* Generated by RuntimeBrowser.
 */

@protocol CKVSearchService

@required

- (NSArray *)matchSpansWithTokenChain:(CKVTokenChain *)arg1;
- (NSArray *)searchFTSWithCriteria:(CKVSearchCriteria *)arg1 error:(id*)arg2;

@end
