/* Generated by RuntimeBrowser.
 */

@protocol DirectionPadValueChangedDelegate <NSObject>

@required

- (GCControllerDirectionPad *)dpad;
- (GCControllerDirectionPad *)dpadDirectionEvent:(GCControllerDirectionPad *)arg1 direction:(unsigned long long)arg2 pressed:(bool)arg3;

@end
