/* Generated by RuntimeBrowser.
 */

@protocol FCUserVectorProvider <NSObject>

@required

- (NTPBVersionedPersonalizationVector *)computePersonalizationVectorWithBaselineAggregate:(id <FCPersonalizationAggregate>)arg1 allAggregates:(NSDictionary *)arg2 options:(long long)arg3;
- (NSSet *)subscribedBundleChannelIDs;

@end
