/* Generated by RuntimeBrowser.
 */

@protocol HDRemoteFeatureAvailabilityProvidingDelegate

@required

- (void)remoteFeatureAvailabilityProvider:(id <HDRemoteFeatureAvailabilityProviding>)arg1 didUpdateAvailabilityForFeatureIdentifier:(NSString *)arg2;

@end
