/* Generated by RuntimeBrowser.
 */

@protocol HDRemoteFeatureAvailabilityProviding

@required

- (<HDRemoteFeatureAvailabilityProvidingDelegate> *)delegate;
- (NSNumber *)isRemoteDisabledForCountryCode:(NSString *)arg1 device:(NRDevice *)arg2 error:(id*)arg3;
- (NSNumber *)isRemoteDisabledOnActivePairedDeviceForCountryCode:(NSString *)arg1 error:(id*)arg2;
- (void)setDelegate:(id <HDRemoteFeatureAvailabilityProvidingDelegate>)arg1;

@end
