/* Generated by RuntimeBrowser.
 */

@protocol HFSoftwareUpdatableItemProtocol <NSObject>

@required

- (NSSet *)accessoriesSupportingSoftwareUpdate;
- (bool)anyAccessorySupportsSoftwareUpdate;
- (NSSet *)availableSoftwareUpdates;

@end
