/* Generated by RuntimeBrowser.
 */

@protocol HMDAccessorySettingsControllerDataSource

@required

- (HMDAccessorySetupMetricDispatcher *)accessorySetupMetricDispatcher;
- (HMDBackingStore *)backingStore;
- (double)homepodSetupLatency;
- (bool)homepodSetupMetricIsAlreadySubmitted;
- (NSArray *)modelsToMakeSettingsForController:(HMDAccessorySettingsController *)arg1 parentUUID:(NSUUID *)arg2;
- (NSArray *)modelsToMigrateSettingsForController:(HMDAccessorySettingsController *)arg1;
- (void)setHomepodSetupLatency:(double)arg1;
- (void)setHomepodSetupMetricIsAlreadySubmitted:(bool)arg1;
- (void)setSetupActivity:(HMFActivity *)arg1;
- (void)setSetupStartTimestamp:(double)arg1;
- (HMFActivity *)setupActivity;
- (double)setupStartTimestamp;

@end
