/* Generated by RuntimeBrowser.
 */

@protocol HMDCoreDuetLogEvent <NSObject>

@required

- (unsigned long long)duetEventType;
- (NSDate *)endDate;
- (NSArray *)eventDataToLog;
- (NSDate *)startDate;

@end
