/* Generated by RuntimeBrowser.
 */

@protocol HMEMessageDatagramServerDataSource <NSObject>

@required

- (bool)server:(HMEMessageDatagramServer *)arg1 isConnectionTerminatingError:(NSError *)arg2;
- (double)server:(HMEMessageDatagramServer *)arg1 timeoutIntervalForConnection:(id <HMEMessageDatagramConnection>)arg2;
- (bool)serverShouldProcessEvents:(HMEMessageDatagramServer *)arg1;
- (<HMETimerProvider> *)serverTimerProvider:(HMEMessageDatagramServer *)arg1;

@end
