/* Generated by RuntimeBrowser.
 */

@protocol HMEMessageDatagramClientDataSource

@required

- (bool)client:(HMEMessageDatagramClient *)arg1 isConnectionTerminatingError:(NSError *)arg2;
- (bool)clientIsEnabled:(HMEMessageDatagramClient *)arg1;

@end
