/* Generated by RuntimeBrowser.
 */

@protocol HMEPersistentConnectionServerDataSource <NSObject>

@required

- (unsigned long long)debounceTimeForConnection:(id <HMEPersistentConnection>)arg1;

@end
