/* Generated by RuntimeBrowser.
 */

@protocol MCProfileViewControllerDelegate <NSObject>

@required

- (void)profileViewControllerDidSelectRemoveProfile:(MCProfileViewController *)arg1;
- (bool)profileViewControllerIsProfileInstalled;

@optional

- (void)profileViewControllerDidSelectPoll:(MCProfileViewController *)arg1;
- (void)profileViewControllerDidSelectUpdateProfile:(MCProfileViewController *)arg1;
- (bool)profileViewControllerShouldDisplayPoll:(MCProfileViewController *)arg1;

@end
