/* Generated by RuntimeBrowser.
 */

@protocol MPMediaControlsSpatialAudioControllerDelegate <NSObject>

@required

- (void)mediaControlsSpatialAudioController:(MPMediaControlsSpatialAudioController *)arg1 didChangeHeadTrackedSpatialAudioEnabled:(bool)arg2;

@end
