/* Generated by RuntimeBrowser.
 */

@protocol NMSPodcastsDownloadableContentControllerDelegate <NSObject>

@required

- (void)podcastsDownloadableContentControllerContentDidChange:(NMSPodcastsDownloadableContentController *)arg1;

@end
