/* Generated by RuntimeBrowser.
 */

@protocol NTKGreenfieldB640ContentViewControllerDelegate <NSObject>

@required

- (void)greenfieldB640ContentViewController:(NTKGreenfieldB640ContentViewController *)arg1 handleActionEvent:(long long)arg2 selectedDecodedRecipe:(NTKGreenfieldDecodedRecipe *)arg3;

@end
