/* Generated by RuntimeBrowser.
 */

@protocol SBBannerHomeGestureViewProviding <NSObject>

@required

- (SBBarSwipeAffordanceView *)bannerBarSwipeAffordanceViewForParticipant:(id <SBUIBannerHomeGestureParticipant>)arg1;

@end
