/* Generated by RuntimeBrowser.
 */

@protocol SBBannerManagerHomeGestureContextDelegate <NSObject>

@required

- (void)wantsHomeGestureDidChangeForBannerManagerHomeGestureContext:(SBBannerManagerHomeGestureContext *)arg1;

@optional

- (<BSInvalidatable> *)gestureRecognizerPriorityAssertionForBannerManagerHomeGestureContext:(SBBannerManagerHomeGestureContext *)arg1 priority:(long long)arg2 reason:(NSString *)arg3;
- (SBKeyboardHomeAffordanceAssertion *)keyboardHomeAffordanceAssertionForBannerManagerHomeGestureContext:(SBBannerManagerHomeGestureContext *)arg1;

@end
