/* Generated by RuntimeBrowser.
 */

@protocol SBHTodayViewControllerObserver <NSObject>

@optional

- (void)todayViewControllerDidAppear:(id <SBHTodayViewController>)arg1;
- (void)todayViewControllerDidDisappear:(id <SBHTodayViewController>)arg1;
- (void)todayViewControllerDidEndScrolling:(id <SBHTodayViewController>)arg1;

@end
