/* Generated by RuntimeBrowser.
 */

@protocol SBUIPoseidonContainerViewControllerDelegate <NSObject>

@required

- (void)poseidonContainerViewControllerCoachingStateDidChange:(SBUIPoseidonContainerViewController *)arg1;

@end
