/* Generated by RuntimeBrowser.
 */

@protocol SBUIPhoneUnlockWithWatchControllerDelegate <NSObject>

@required

- (bool)phoneUnlockWithWatchControllerShowRawErrorCodes:(SBUIPhoneUnlockWithWatchController *)arg1;

@end
