/* Generated by RuntimeBrowser.
 */

@protocol TSFollowingEventTracker

@required

- (void)followingBrowserDidCompleteWith:(long long)arg1;
- (void)followingBrowserDidTapOnItemWithTagID:(NSString *)arg1 selected:(bool)arg2;

@end
