/* Generated by RuntimeBrowser.
 */

@protocol WFActionUserInterfaceDelegate <NSObject>

@required

- (void)actionUserInterface:(WFActionUserInterface *)arg1 setSupportedInterfaceOrientations:(unsigned long long)arg2;
- (void)actionUserInterface:(WFActionUserInterface *)arg1 showViewInPlatter:(UIView *)arg2 attribution:(WFDialogAttribution *)arg3;

@end
