/* Generated by RuntimeBrowser.
 */

@protocol WFWorkflowSettingsViewControllerDelegate <NSObject>

@required

- (bool)settingsViewControllerWantsToKnowIfNewShortcutFlow:(WFWorkflowSettingsViewController *)arg1;
- (void)settingsViewControllerWantsWorkflowReload:(WFWorkflowSettingsViewController *)arg1;

@end
