/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriContactsIntents.framework/SiriContactsIntents
 */

@interface SiriContactsIntents.UnsupportedActionFlow : _TtCs12_SwiftObject {
    void aceService;
    void canUseServerTTS;
    void commonCATs;
    void deviceState;
    void ttsEnabled;
}

@end
