/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalendarDaemon.framework/CalendarDaemon
 */

@interface CADStatsGeneralCollection : CADStatCollector {
    CADStatCollectionContext * _context;
    NSCountedSet * accountTypes;
    EKCalendarDate * days1;
    EKCalendarDate * days28;
    EKCalendarDate * days365;
    EKCalendarDate * days7;
    struct { 
        long long thresholds[9]; 
        unsigned long long inLast1Day[10]; 
        unsigned long long inNext1Day[10]; 
        unsigned long long inNext7Days[10]; 
        unsigned long long inNext28Days[10]; 
        unsigned long long inNext365Days[10]; 
    }  durationAllDayDays;
    struct { 
        long long thresholds[9]; 
        unsigned long long inLast1Day[10]; 
        unsigned long long inNext1Day[10]; 
        unsigned long long inNext7Days[10]; 
        unsigned long long inNext28Days[10]; 
        unsigned long long inNext365Days[10]; 
    }  durationNonAllDayMinutes;
    bool  hasLocalSource;
    bool  hasRemoteSource;
    EKCalendarDate * now;
    struct { 
        long long thresholds[9]; 
        unsigned long long inLast1Day[10]; 
        unsigned long long inNext1Day[10]; 
        unsigned long long inNext7Days[10]; 
        unsigned long long inNext28Days[10]; 
        unsigned long long inNext365Days[10]; 
    }  numAttendees;
    EKCalendarDate * oneDayAgo;
    NSMutableDictionary * payload;
    unsigned long long  significantEventsCount;
    unsigned long long  significantEventsOnSharedCalendarCount;
    unsigned long long  significantEventsWithPredictedLocationAndOnSharedCalendar;
    unsigned long long  significantEventsWithPredictedLocationCount;
    unsigned long long  totalAccounts;
    unsigned long long  totalAccountsWithSyncStyleFetch;
    unsigned long long  totalAccountsWithSyncStyleManual;
    unsigned long long  totalAccountsWithSyncStylePush;
    unsigned long long  totalAllDayEvents;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalAllDayOccurrences;
    unsigned long long  totalCalendars;
    unsigned long long  totalDefaultBirthdays;
    unsigned long long  totalDetachedEvents;
    unsigned long long  totalEvents;
    unsigned long long  totalEventsAreCandidatesForTravelAdvisories;
    unsigned long long  totalEventsAreImmediatelyEligibleForTravelAdvisories;
    unsigned long long  totalEventsThatUserDeclined;
    unsigned long long  totalEventsWithAlertsIgnored;
    unsigned long long  totalEventsWithClientLocation;
    unsigned long long  totalEventsWithConferenceRoomLocation;
    unsigned long long  totalEventsWithConferenceRoomLocationHavingKnownSpatialData;
    unsigned long long  totalEventsWithLocation;
    unsigned long long  totalEventsWithLocationHavingKnownSpatialData;
    unsigned long long  totalEventsWithRecurrence;
    unsigned long long  totalEventsWithTravelAdvisoryBehaviorAutomatic;
    unsigned long long  totalEventsWithTravelAdvisoryBehaviorDisabled;
    unsigned long long  totalEventsWithTravelAdvisoryBehaviorEnabled;
    unsigned long long  totalFacebookEvents;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrences;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesAreCandidatesForTravelAdvisories;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesAreImmediatelyEligibleForTravelAdvisories;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesInCalendarsThatSuppressEventAlerts;
    long long  totalOccurrencesProcessed;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeeResponseComment;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeeStatusAccepted;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeeStatusCompleted;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeeStatusDeclined;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeeStatusDelegated;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeeStatusInprocess;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeeStatusNone;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeeStatusPending;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeeStatusTentative;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendees;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeesAndOrganizerIsNotSelf;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithAttendeesAndOrganizerIsSelf;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithClientLocation;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithConferenceRoomLocation;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithConferenceRoomLocationHavingKnownSpatialData;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithLocation;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithLocationHavingKnownSpatialData;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithNonDefaultAlarms;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithNotes;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithStatusCancelled;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithStatusConfirmed;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithStatusNone;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithStatusTentative;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithStatusTentativeUnlisted;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithTravelAdvisoryBehaviorAutomatic;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithTravelAdvisoryBehaviorDisabled;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithTravelAdvisoryBehaviorEnabled;
    struct { 
        unsigned long long inLast1Day; 
        unsigned long long inNext1Day; 
        unsigned long long inNext7Days; 
        unsigned long long inNext28Days; 
        unsigned long long inNext365Days; 
    }  totalOccurrencesWithURLs;
}

+ (id)eventName;

- (void).cxx_destruct;
- (id)eventDictionaries;
- (id)init;
- (void)performOtherGeneralCollection;
- (void)prepareWithContext:(id)arg1;
- (void)processBirthdayCalendarEvents:(id)arg1;
- (void)processCalendars:(id)arg1 inStore:(void*)arg2;
- (void)processEvents:(id)arg1;
- (void)processOccurrences:(id)arg1;
- (void)processSignificantEventWithPredictedLocation:(bool)arg1 onSharedCalendar:(bool)arg2;
- (void)processStores:(id)arg1;
- (bool)wantsBirthdays;
- (bool)wantsCalendars;
- (bool)wantsEvents;
- (bool)wantsOccurrences;
- (bool)wantsSignificantEvents;
- (bool)wantsStores;

@end
