/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CalendarDaemon.framework/CalendarDaemon
 */

@interface CADStatsCalendars : CADStatCollector {
    CADStatCollectionContext * _context;
    int  _totalAuthenticatedSubscribedCalendars;
    int  _totalCalDAVSubscribedCalendars;
    int  _totalCalendarSharees;
    int  _totalCalendars;
    int  _totalHolidayCalendars;
    int  _totalSharedCalendars;
    int  _totalSubscribedCalendars;
}

+ (id)eventName;

- (void).cxx_destruct;
- (bool)calendarUsesAuthentication:(void*)arg1;
- (id)eventDictionaries;
- (void)prepareWithContext:(id)arg1;
- (void)processCalendars:(id)arg1 inStore:(void*)arg2;
- (bool)wantsCalendars;

@end
