/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TelephonyUtilities.framework/TelephonyUtilities
 */

@interface TUFeatureFlags : NSObject <TUFeatureFlags>

@property (nonatomic, readonly) bool announceCalls;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) bool nonInterruptingCalls;
@property (nonatomic, readonly) bool siriGroupFaceTime;
@property (readonly) Class superclass;

- (bool)announceCalls;
- (bool)nonInterruptingCalls;
- (bool)siriGroupFaceTime;

@end
