/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AVConference.framework/AVConference
 */

@interface VCSecurityKeyManager : NSObject {
    id  _delegate;
    bool  _isKeyIndexNotReceivedReported;
    bool  _isReceiveKeysCleanUpPending;
    bool  _isSendKeysCleanUpPending;
    VCMasterKeyIndex * _keyIndexNotReceived;
    NSObject<OS_dispatch_queue> * _keyManagerQueue;
    double  _lastKeyIndexNotReceived;
    VCMasterKeyIndex * _latestReceiveKeyIndex;
    VCMasterKeyIndex * _latestSendKeyIndex;
    NSMutableDictionary * _prunePendingReceiveKeys;
    NSObject<OS_dispatch_source> * _pruneTimer;
    NSMutableDictionary * _receiveKeys;
    id  _reportingAgentWeak;
    NSMutableDictionary * _sendKeys;
    NSMutableArray * _unknownKeyIndexList;
}

- (bool)addSecurityKeyMaterial:(id)arg1;
- (void)associateMKI:(id)arg1 withClientID:(id)arg2;
- (void)dealloc;
- (id)delegate;
- (double)firstExpirationTime;
- (id)getLatestRecvKeyMaterial;
- (id)getLatestSendKeyMaterial;
- (long long)getNotUsedTimeout;
- (id)getRecvKeyMaterialWithIndex:(id)arg1;
- (id)getSendKeyMaterialWithIndex:(id)arg1;
- (void)handlePruneTimerEventAndReschedule;
- (id)initWithDelegate:(id)arg1 reportingAgent:(struct opaqueRTCReporting { }*)arg2;
- (double)pruneAllExpiredKeys;
- (void)pruneRecvKeyMaterialWithDelay:(double)arg1;
- (void)pruneSendKeyMaterialWithDelay:(double)arg1;
- (struct opaqueRTCReporting { }*)reportingAgent;
- (void)schedulePruneTimer:(double)arg1;
- (void)setReportingAgent:(struct opaqueRTCReporting { }*)arg1;

@end
