/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DialogEngine.framework/DialogEngine
 */

@interface DEManifestSyncDownload : NSObject {
    unsigned long long  _size;
    NSURL * _url;
}

@property (nonatomic) unsigned long long size;
@property (nonatomic, retain) NSURL *url;

- (void).cxx_destruct;
- (void)setSize:(unsigned long long)arg1;
- (void)setUrl:(id)arg1;
- (unsigned long long)size;
- (id)url;

@end
