/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ConversationKit.framework/ConversationKit
 */

@interface CNKDebugOverlayController : UIViewController <UITextViewDelegate> {
    void call;
    void conversationController;
    void debugOverlayDelegate;
    void delegate;
    void deviceOrientation;
    void explanationLabel;
    void isOnScreen;
    void localParticipantName;
    void localPreviewView;
    void mainButton;
    void mainScrollView;
    void mainView;
    void nameButtonAttributes;
    void nameInputBackgroundView;
    void nameInputCenterYConstraint;
    void nameInputLabel;
    void nameLabel;
    void nameTextAttributes;
    void nameTextField;
    void paragraphStyle;
    void participantLabel;
    void scrollContentView;
    void secondaryButton;
    void secondaryParticipantLabel;
    void videoDeviceController;
}

@property (nonatomic, retain) TUCall *call;
@property (nonatomic) <CNKDebugOverlayControllerDelegate> *debugOverlayDelegate;
@property (nonatomic) <CNKFaceTimeMultiwayConversationViewControllerDelegate> *delegate;
@property (nonatomic) long long deviceOrientation;
@property (nonatomic) bool isOnScreen;

+ (id)dismissalAssertionReason;

- (void).cxx_destruct;
- (bool)_canShowWhileLocked;
- (id)call;
- (id)debugOverlayDelegate;
- (id)delegate;
- (long long)deviceOrientation;
- (void)didTapCancelButton;
- (void)didTapDoneButton;
- (void)didTapMainButton;
- (void)didTapSecondaryButton;
- (id)initWithActiveCall:(id)arg1 localParticipantName:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (bool)isOnScreen;
- (void)keyboardWillHideWithNotification:(id)arg1;
- (void)keyboardWillShowWithNotification:(id)arg1;
- (void)setCall:(id)arg1;
- (void)setDebugOverlayDelegate:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setDeviceOrientation:(long long)arg1;
- (void)setIsOnScreen:(bool)arg1;
- (bool)textView:(id)arg1 shouldInteractWithURL:(id)arg2 inRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg3 interaction:(long long)arg4;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillTransitionToSize:(struct CGSize { double x1; double x2; })arg1 withTransitionCoordinator:(id)arg2;

@end
