/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/CoreNFC.framework/CoreNFC
 */

@interface NFCVASReaderSession : NFCReaderSession <NFReaderSessionCallbacks> {
    NFTimer * _presenceCheckTimer;
    NSArray * _vasConfig;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (bool)readingAvailable;

- (void).cxx_destruct;
- (void)_callbackDidBecomeActive;
- (void)_callbackDidInvalidateWithError:(id)arg1;
- (id)_getVASDataWithConfig:(id)arg1 lastInSequence:(bool)arg2;
- (bool)_selectOSE;
- (void)beginSession;
- (void)dealloc;
- (void)didDetectTags:(id)arg1 connectedTagIndex:(unsigned long long)arg2;
- (void)didTerminate:(id)arg1;
- (id)initWithDelegate:(id)arg1 sessionDelegateType:(long long)arg2 queue:(id)arg3 pollMethod:(unsigned long long)arg4 sessionConfig:(unsigned long long)arg5;
- (id)initWithVASCommandConfigurations:(id)arg1 delegate:(id)arg2 queue:(id)arg3;

@end
