/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamInsights.framework/ShazamInsights
 */

@interface SHDataStoreMetadata : NSObject {
    NSString * _etag;
    NSDate * _fetchDate;
    NSString * _storefront;
}

@property (nonatomic, readonly, copy) NSString *etag;
@property (nonatomic, readonly) NSDate *fetchDate;
@property (nonatomic, readonly, copy) NSString *storefront;

- (void).cxx_destruct;
- (id)etag;
- (id)fetchDate;
- (id)initWithStorefront:(id)arg1 fetchDate:(id)arg2 etag:(id)arg3;
- (id)storefront;

@end
