/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamInsights.framework/ShazamInsights
 */

@interface SHFileReader : NSObject {
    NSString * _filePath;
    unsigned long long  chunkSize;
    unsigned long long  currentOffset;
    NSFileHandle * fileHandle;
    NSString * lineDelimiter;
    unsigned long long  totalFileLength;
}

@property (nonatomic) unsigned long long chunkSize;
@property (nonatomic, copy) NSString *filePath;
@property (nonatomic, copy) NSString *lineDelimiter;

- (void).cxx_destruct;
- (unsigned long long)chunkSize;
- (void)dealloc;
- (void)enumerateDataLinesUsingBlock:(id /* block */)arg1;
- (void)enumerateJSONObjectsUsingBlock:(id /* block */)arg1;
- (id)filePath;
- (id)initWithFilePath:(id)arg1;
- (id)lineDelimiter;
- (id)readDataLine;
- (id)readLine;
- (void)setChunkSize:(unsigned long long)arg1;
- (void)setFilePath:(id)arg1;
- (void)setLineDelimiter:(id)arg1;

@end
