/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamInsights.framework/ShazamInsights
 */

@interface SHInsightsPersistenceController : NSObject {
    SKCloudServiceController * _cloudServiceController;
    <SHDataFetcher> * _dataFetcher;
    <SHDataStore> * _dataStore;
}

@property (nonatomic, readonly) SKCloudServiceController *cloudServiceController;
@property (nonatomic, readonly) <SHDataFetcher> *dataFetcher;
@property (nonatomic, readonly) <SHDataStore> *dataStore;

- (void).cxx_destruct;
- (id)cloudServiceController;
- (void)clustersForLocation:(id)arg1 date:(id)arg2 completionHandler:(id /* block */)arg3;
- (id)dataFetcher;
- (id)dataStore;
- (void)fetchDataForCountryCode:(id)arg1 withCompletion:(id /* block */)arg2;
- (id)initWithDataFetcher:(id)arg1 dataStore:(id)arg2;
- (void)loadTargetingDataWithCompletion:(id /* block */)arg1;
- (void)queryWithCompletion:(id /* block */)arg1;
- (void)removeAllTargeting;

@end
