/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamInsights.framework/ShazamInsights
 */

@interface SHRegionAffinityGroup : NSObject {
    SHAffinityGroup * _affinityGroup;
    NSArray * _regions;
}

@property (nonatomic, readonly) SHAffinityGroup *affinityGroup;
@property (nonatomic, readonly) NSArray *regions;

- (void).cxx_destruct;
- (id)affinityGroup;
- (id)initWithRegions:(id)arg1 affinityGroup:(id)arg2;
- (id)regions;
- (id)regionsForGeohash:(id)arg1;

@end
