/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideoSubscriberAccountUI.framework/VideoSubscriberAccountUI
 */

@interface VSStorefront : NSObject {
    NSString * _displayName;
    NSString * _identitifer;
}

@property (nonatomic, retain) NSString *displayName;
@property (nonatomic, retain) NSString *identitifer;

- (void).cxx_destruct;
- (id)displayName;
- (id)identitifer;
- (void)setDisplayName:(id)arg1;
- (void)setIdentitifer:(id)arg1;

@end
