/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeStreams.framework/BiomeStreams
 */

@interface BMInferredModeStream : NSObject <BMSourceStream, BMStream> {
    BMRestrictedStream * _stream;
}

@property (nonatomic, readonly) NSString *identifier;

// Image: /System/Library/PrivateFrameworks/BiomeStreams.framework/BiomeStreams

- (void).cxx_destruct;
- (id)identifier;
- (id)init;
- (id)publisherFromStartTime:(double)arg1;
- (id)source;

// Image: /System/Library/PrivateFrameworks/ProactiveContextClient.framework/ProactiveContextClient

- (id)currentMode;

@end
