/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BiomeStreams.framework/BiomeStreams
 */

@interface BMPBSemanticLocationEvent : PBCodable <NSCopying> {
    struct { 
        unsigned int label : 1; 
        unsigned int starting : 1; 
    }  _has;
    int  _label;
    bool  _starting;
}

@property (nonatomic) bool hasLabel;
@property (nonatomic) bool hasStarting;
@property (nonatomic) int label;
@property (nonatomic) bool starting;

- (int)StringAsLabel:(id)arg1;
- (void)copyTo:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)dictionaryRepresentation;
- (bool)hasLabel;
- (bool)hasStarting;
- (unsigned long long)hash;
- (bool)isEqual:(id)arg1;
- (int)label;
- (id)labelAsString:(int)arg1;
- (void)mergeFrom:(id)arg1;
- (bool)readFrom:(id)arg1;
- (void)setHasLabel:(bool)arg1;
- (void)setHasStarting:(bool)arg1;
- (void)setLabel:(int)arg1;
- (void)setStarting:(bool)arg1;
- (bool)starting;
- (void)writeTo:(id)arg1;

@end
