/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDAppleMediaAccessoryMatchingIdentifierEvent : HMDLogEvent <HMDCoreAnalyticsLogging> {
    NSNumber * _expectedRemovalCount;
    NSNumber * _matchingIdentifiersCount;
}

@property (readonly, copy) NSNumber *expectedRemovalCount;
@property (readonly, copy) NSNumber *matchingIdentifiersCount;

- (void).cxx_destruct;
- (id)attributeDescriptions;
- (id)eventName;
- (id)expectedRemovalCount;
- (id)initWithMatchingIdentifiersCount:(long long)arg1;
- (id)matchingIdentifiersCount;
- (id)serializedEvent;

@end
