/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDBackingStoreOperation : NSOperation <HMFLogging> {
    NSUUID * _operationUUID;
    id /* block */  _resultBlock;
    HMDBackingStore * _store;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSUUID *operationUUID;
@property (nonatomic, copy) id /* block */ resultBlock;
@property (nonatomic, retain) HMDBackingStore *store;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (id)description;
- (id)init;
- (id)initWithResultBlock:(id /* block */)arg1;
- (id)logIdentifier;
- (void)main;
- (id)mainReturningError;
- (id)operationUUID;
- (id /* block */)resultBlock;
- (void)setResultBlock:(id /* block */)arg1;
- (void)setStore:(id)arg1;
- (id)store;

@end
