/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDBiomeLogEventObserver : HMFObject <HMDLogEventObserver> {
    HMDBiomeEventManager * _biomeEventManager;
    <HMDBiomeLogEventObserverDataSource> * _dataSource;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)shortDescription;

- (void).cxx_destruct;
- (void)didReceiveEventFromDispatcher:(id)arg1;
- (id)initWithBiomeEventManager:(id)arg1 dataSource:(id)arg2;

@end
