/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCloudShareTrustManagerTrustActivityLogEvent : HMDCloudShareTrustManagerLogEvent <HMDCoreAnalyticsLogging> {
    NSNumber * _isPrimaryResident;
    NSNumber * _privilege;
    NSNumber * _trustActivityType;
}

@property (readonly, copy) NSNumber *isPrimaryResident;
@property (readonly, copy) NSNumber *privilege;
@property (readonly, copy) NSNumber *trustActivityType;

- (void).cxx_destruct;
- (id)eventName;
- (id)initWithTrustActivityType:(long long)arg1 privilege:(unsigned long long)arg2 isPrimaryResident:(bool)arg3;
- (id)isPrimaryResident;
- (id)privilege;
- (id)serializedEvent;
- (id)trustActivityType;

@end
