/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDCounterRateLoggingTrigger : NSObject <HMDEventCounterObserver> {
    NSString * _counterName;
    unsigned long long * _intervalCounts;
    unsigned long long  _intervalSize;
    unsigned long long  _lastUpdatedInterval;
    unsigned long long  _maxWindowCount;
    id /* block */  _timeSourceBlock;
    unsigned long long  _windowCount;
    unsigned long long  _windowSize;
    unsigned long long  _windowThreshold;
}

@property (nonatomic, readonly) NSString *counterName;
@property (nonatomic) unsigned long long*intervalCounts;
@property (nonatomic, readonly) unsigned long long intervalSize;
@property (nonatomic) unsigned long long lastUpdatedInterval;
@property (nonatomic) unsigned long long maxWindowCount;
@property (nonatomic, readonly) id /* block */ timeSourceBlock;
@property (nonatomic) unsigned long long windowCount;
@property (nonatomic, readonly) unsigned long long windowSize;
@property (nonatomic, readonly) unsigned long long windowThreshold;

- (void).cxx_destruct;
- (id)counterName;
- (void)dealloc;
- (id)initWithThreashold:(unsigned long long)arg1 windowSize:(unsigned long long)arg2 counterName:(id)arg3;
- (id)initWithThreashold:(unsigned long long)arg1 windowSize:(unsigned long long)arg2 counterName:(id)arg3 timeSourceBlock:(id /* block */)arg4;
- (unsigned long long*)intervalCounts;
- (unsigned long long)intervalSize;
- (unsigned long long)lastUpdatedInterval;
- (void)logRateTrigger:(id)arg1 triggerValue:(unsigned long long)arg2;
- (unsigned long long)maxWindowCount;
- (void)setIntervalCounts:(unsigned long long*)arg1;
- (void)setLastUpdatedInterval:(unsigned long long)arg1;
- (void)setMaxWindowCount:(unsigned long long)arg1;
- (void)setWindowCount:(unsigned long long)arg1;
- (id /* block */)timeSourceBlock;
- (void)updatedCounterForEventName:(id)arg1 requestGroup:(id)arg2 fromOldValue:(unsigned long long)arg3 toNewValue:(unsigned long long)arg4;
- (unsigned long long)windowCount;
- (unsigned long long)windowSize;
- (unsigned long long)windowThreshold;

@end
