/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDErrorAggregationLogEvent : HMDLogEvent <HMDCoreAnalyticsLogging> {
    NSDictionary * _coreAnalyticsSerializedEvent;
}

@property (nonatomic, readonly) NSDictionary *coreAnalyticsSerializedEvent;

- (void).cxx_destruct;
- (id)coreAnalyticsSerializedEvent;
- (id)eventName;
- (id)initWithEventGroupName:(id)arg1 errorString:(id)arg2 errorCount:(id)arg3;
- (id)serializedEvent;

@end
