/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDHomeMetricsDispatcherFactory : HMFObject <HMDHomeMetricsDispatcherFactory>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id)createHomeMetricsDispatcherWithIdentifier:(id)arg1 logEventDispatcher:(id)arg2;

@end
