/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDHAPMetricsReachabilityTimerLateEvent : HMDHAPMetrics <HMDCoreAnalyticsLogging> {
    NSNumber * _duration;
    NSNumber * _expectedDuration;
}

@property (nonatomic, readonly) NSNumber *duration;
@property (nonatomic, readonly) NSNumber *expectedDuration;

- (void).cxx_destruct;
- (id)duration;
- (id)eventName;
- (id)expectedDuration;
- (id)initWithAccessory:(id)arg1 duration:(id)arg2 expectedDuration:(id)arg3;
- (id)serializedEvent;

@end
