/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDLogEventHistograms : HMFObject

+ (id)configurationDataHistogram;
+ (id)fileSizeHistogram;
+ (id)highVolumeHistogram;
+ (void)initialize;
+ (id)latencyHistogram;
+ (id)lowVolumeHistogram;
+ (id)memoryHistogram;
+ (id)successRateHistogram;

@end
