/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDRemoteEventRouterAccessControl : NSObject {
    unsigned long long  _allowedDeviceTypes;
    unsigned long long  _allowedUserTypes;
}

@property (readonly) unsigned long long allowedDeviceTypes;
@property (readonly) unsigned long long allowedUserTypes;

+ (id)allowAllUsersAndDevicesAccessControl;

- (unsigned long long)allowedDeviceTypes;
- (unsigned long long)allowedUserTypes;
- (id)initWithAllowedUserTypes:(unsigned long long)arg1 deviceCategories:(unsigned long long)arg2;

@end
