/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDSiriStreamStartEvent : HMDLogEvent <HMDCoreAnalyticsLogging> {
    unsigned long long  _activationType;
}

@property (nonatomic, readonly) unsigned long long activationType;

- (unsigned long long)activationType;
- (id)eventName;
- (id)initWithActivationType:(unsigned long long)arg1;
- (id)serializedEvent;

@end
