/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeKitDaemon.framework/HomeKitDaemon
 */

@interface HMDXPCEventRouterServer : NSObject <HMEPersistentConnectionServerDataSource, HMEPersistentConnectionServerDelegate, HMFLogging, HMFMessageReceiver> {
    NSString * _changeRegistrationsMessageName;
    HMFMessageDispatcher * _messageDispatcher;
    NSUUID * _messageUUID;
    NSNotificationCenter * _notificationCenter;
    HMEPersistentConnectionServer * _persistentConnectionServer;
    NSString * _updateEventsMessageName;
    NSObject<OS_dispatch_queue> * _workQueue;
}

@property (readonly, copy) NSString *changeRegistrationsMessageName;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) HMFMessageDispatcher *messageDispatcher;
@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *messageReceiveQueue;
@property (nonatomic, readonly) NSUUID *messageTargetUUID;
@property (readonly, copy) NSUUID *messageUUID;
@property (readonly) NSNotificationCenter *notificationCenter;
@property (readonly) HMEPersistentConnectionServer *persistentConnectionServer;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *updateEventsMessageName;
@property (readonly) NSObject<OS_dispatch_queue> *workQueue;

+ (id)logCategory;

- (void).cxx_destruct;
- (void)_handleChangeRegistrationsRequest:(id)arg1;
- (id)changeRegistrationsMessageName;
- (void)configure;
- (unsigned long long)debounceTimeForConnection:(id)arg1;
- (id)dumpStateDescription;
- (void)handleXPCConnectionInvalidated:(id)arg1;
- (id)initWithMessageUUID:(id)arg1 changeRegistrationsMessageName:(id)arg2 updateEventsMessageName:(id)arg3 messageDispatcher:(id)arg4 queue:(id)arg5 notificationCenter:(id)arg6 persistentConnectionServerFactory:(id /* block */)arg7;
- (id)initWithMessageUUID:(id)arg1 changeRegistrationsMessageName:(id)arg2 updateEventsMessageName:(id)arg3 messageDispatcher:(id)arg4 queue:(id)arg5 notificationCenter:(id)arg6 subscriptionProvider:(id)arg7 registrationEventRouter:(id)arg8 storeReadHandle:(id)arg9;
- (id)logIdentifier;
- (id)messageDispatcher;
- (id)messageReceiveQueue;
- (id)messageTargetUUID;
- (id)messageUUID;
- (id)notificationCenter;
- (id)persistentConnectionServer;
- (void)registerForMessages;
- (void)sendUpdatedCachedEvents:(id)arg1 toConnection:(id)arg2;
- (void)sendUpdatedEvents:(id)arg1 toConnection:(id)arg2;
- (bool)shouldAllowEvent:(id)arg1 topic:(id)arg2 connection:(id)arg3;
- (id)updateEventsMessageName;
- (id)workQueue;

@end
