/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsAnalytics.framework/NewsAnalytics
 */

@interface NewsAnalytics.AllowedEventNameProvider : _TtCs12_SwiftObject {
    void allowedEventNames;
}

@end
