/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/RealityKit.framework/RealityKit
 */

@interface RealityKit.__RealityFileURLResolver : _TtCs12_SwiftObject {
    void assetService;
    void extraUrlsToDeleteDuringUnregistration;
    void resolvedURLByAssetPathPrefix;
    void resolvedURLByAssetPathPrefixQueue;
}

@end
