/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NanoTimeKitCompanion.framework/NanoTimeKitCompanion
 */

@interface NTKGreenfieldB640Model : NSObject {
    NSBundle * _bandImageBundle;
    NSString * _bandImagePath;
    NSArray * _decodedRecipes;
    NSError * _error;
}

@property (nonatomic, retain) NSBundle *bandImageBundle;
@property (nonatomic, retain) NSString *bandImagePath;
@property (nonatomic, retain) NSArray *decodedRecipes;
@property (nonatomic, retain) NSError *error;

- (void).cxx_destruct;
- (id)bandImageBundle;
- (id)bandImagePath;
- (id)decodedRecipes;
- (id)error;
- (id)initWithDecodedRecipes:(id)arg1 error:(id)arg2 bandImagePath:(id)arg3 bandImageBundle:(id)arg4;
- (void)setBandImageBundle:(id)arg1;
- (void)setBandImagePath:(id)arg1;
- (void)setDecodedRecipes:(id)arg1;
- (void)setError:(id)arg1;

@end
