/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BusinessChatService.framework/BusinessChatService
 */

@interface BCSDomainItemCacheManager : NSObject <BCSDomainItemCacheManaging> {
    <BCSDomainItemCaching> * _persistentStore;
}

@property (nonatomic, retain) <BCSDomainItemCaching> *persistentStore;

- (void).cxx_destruct;
- (id)domainItemForIdentifier:(id)arg1;
- (id)initWithDomainItemPersistentStore:(id)arg1;
- (id)persistentStore;
- (void)setPersistentStore:(id)arg1;
- (void)updateDomainItemsForDomainShard:(id)arg1;

@end
