/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebInspector.framework/WebInspector
 */

@interface RWIProtocolCSSFont : RWIProtocolJSONObject

@property (nonatomic, copy) NSString *displayName;
@property (nonatomic, copy) NSArray *variationAxes;

- (id)displayName;
- (id)initWithDisplayName:(id)arg1 variationAxes:(id)arg2;
- (void)setDisplayName:(id)arg1;
- (void)setVariationAxes:(id)arg1;
- (id)variationAxes;

@end
