/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AuthenticationServicesCore.framework/AuthenticationServicesCore
 */

@interface ASCCredentialRequestContext : NSObject <NSSecureCoding> {
    NSString * _proxiedAppIdentifier;
    NSString * _proxiedAppName;
    NSArray * _proxiedAssociatedDomains;
    NSData * _proxiedIconData;
    NSNumber * _proxiedIconScale;
    NSString * _relyingPartyIdentifier;
    unsigned long long  _requestTypes;
}

@property (nonatomic, copy) NSString *proxiedAppIdentifier;
@property (nonatomic, copy) NSString *proxiedAppName;
@property (nonatomic, copy) NSArray *proxiedAssociatedDomains;
@property (nonatomic, copy) NSData *proxiedIconData;
@property (nonatomic, copy) NSNumber *proxiedIconScale;
@property (nonatomic, copy) NSString *relyingPartyIdentifier;
@property (nonatomic, readonly) unsigned long long requestTypes;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithRequestTypes:(unsigned long long)arg1;
- (id)proxiedAppIdentifier;
- (id)proxiedAppName;
- (id)proxiedAssociatedDomains;
- (id)proxiedIconData;
- (id)proxiedIconScale;
- (id)relyingPartyIdentifier;
- (unsigned long long)requestTypes;
- (void)setProxiedAppIdentifier:(id)arg1;
- (void)setProxiedAppName:(id)arg1;
- (void)setProxiedAssociatedDomains:(id)arg1;
- (void)setProxiedIconData:(id)arg1;
- (void)setProxiedIconScale:(id)arg1;
- (void)setRelyingPartyIdentifier:(id)arg1;

@end
