/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoordinationCore.framework/CoordinationCore
 */

@interface CODistantAccessorySetting : NSObject <NSCopying, NSSecureCoding> {
    NSUUID * _accessoryUniqueIdentifier;
    NSString * _keyPath;
    <NSObject><NSCopying><NSSecureCoding> * _value;
    bool  _writable;
}

@property (nonatomic, readonly, copy) NSUUID *accessoryUniqueIdentifier;
@property (nonatomic, readonly, copy) NSString *keyPath;
@property (nonatomic, copy) <NSObject><NSCopying><NSSecureCoding> *value;
@property (getter=isWritable, nonatomic, readonly) bool writable;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)accessoryUniqueIdentifier;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithAccessorySetting:(id)arg1 accessory:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (bool)isWritable;
- (id)keyPath;
- (void)setValue:(id)arg1;
- (id)value;

@end
