/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoordinationCore.framework/CoordinationCore
 */

@interface CODistantAccessoryDataSetting : CODistantAccessorySetting

+ (bool)supportsSecureCoding;

- (id)initWithCoder:(id)arg1;

@end
