/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoordinationCore.framework/CoordinationCore
 */

@interface COHomeKitSettingUpdateRequest : COMeshRequest {
    CODistantAccessorySetting * _setting;
    <NSObject><NSCopying><NSSecureCoding> * _value;
}

@property (nonatomic, readonly, copy) CODistantAccessorySetting *setting;
@property (nonatomic, readonly) <NSObject><NSCopying><NSSecureCoding> *value;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithAccessorySetting:(id)arg1 value:(id)arg2;
- (id)initWithCoder:(id)arg1;
- (id)setting;
- (id)value;

@end
