/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoordinationCore.framework/CoordinationCore
 */

@interface COMeshElectionRequest : COMeshBaseBallotRequest

+ (id)acceptableResponses;

@end
