/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PDSAgent.framework/PDSAgent
 */

@interface PDSBag : IDSServerBag

- (unsigned long long)_bagDomain;
- (void)_bagExternallyReloaded;
- (id)init;

@end
