/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WorkflowEditor.framework/WorkflowEditor
 */

@interface WFRunWorkflowFooterView : UICollectionReusableView {
    WFFloatingButton * _addButton;
    <WFRunWorkflowFooterViewDelegate> * _delegate;
    WFModulesQuickLookView * _quickLookView;
    UIStackView * _stackView;
}

@property (nonatomic, retain) WFFloatingButton *addButton;
@property (nonatomic, readonly) bool addButtonHidden;
@property (nonatomic) <WFRunWorkflowFooterViewDelegate> *delegate;
@property (nonatomic, readonly) WFModulesQuickLookView *quickLookView;
@property (nonatomic, readonly) bool quickLookViewHidden;
@property (nonatomic, retain) UIStackView *stackView;

+ (double)preferredHeightWithQuickLookVisible:(bool)arg1 addButtonVisible:(bool)arg2 forWidth:(double)arg3;

- (void).cxx_destruct;
- (id)addButton;
- (bool)addButtonHidden;
- (id)delegate;
- (void)didTapAddButton;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)quickLookView;
- (bool)quickLookViewHidden;
- (void)setAddButton:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setQuickLookViewHidden:(bool)arg1 addButtonHidden:(bool)arg2;
- (void)setStackView:(id)arg1;
- (id)stackView;
- (void)tintColorDidChange;
- (void)updateAddButtonGradient;

@end
