/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ChronoServices.framework/ChronoServices
 */

@interface CHSWidgetExtensionInfo : NSObject <BSXPCSecureCoding, NSCopying, NSMutableCopying> {
    bool  _allowsMixedLocalizations;
    NSArray * _availableLocalizations;
    NSString * _bundleIdentifier;
    NSURL * _bundleURL;
    NSArray * _configurations;
    NSString * _containerBundleIdentifier;
    NSURL * _containerURL;
    NSString * _dataProtectionLevel;
    NSArray * _descriptors;
    NSDate * _lastModifiedDate;
    NSArray * _placeholderURLs;
    NSArray * _snapshotURLs;
    NSURL * _systemDataContainerURL;
    NSArray * _timelineURLs;
    NSString * _version;
    bool  _wantsLocation;
}

@property (nonatomic, readonly) bool allowsMixedLocalizations;
@property (nonatomic, readonly) NSArray *availableLocalizations;
@property (nonatomic, readonly, copy) NSString *bundleIdentifier;
@property (nonatomic, readonly) NSURL *bundleURL;
@property (nonatomic, readonly) NSArray *configurations;
@property (nonatomic, readonly, copy) NSString *containerBundleIdentifier;
@property (nonatomic, readonly) NSURL *containerURL;
@property (nonatomic, readonly, copy) NSString *dataProtectionLevel;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSArray *descriptors;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSDate *lastModifiedDate;
@property (nonatomic, readonly) NSArray *placeholderURLs;
@property (nonatomic, readonly) NSArray *snapshotURLs;
@property (readonly) Class superclass;
@property (nonatomic, readonly) NSURL *systemDataContainerURL;
@property (nonatomic, readonly) NSArray *timelineURLs;
@property (nonatomic, readonly, copy) NSString *version;
@property (nonatomic, readonly) bool wantsLocation;

+ (bool)supportsBSXPCSecureCoding;

- (void).cxx_destruct;
- (id)_init;
- (id)_initWithInfo:(id)arg1;
- (bool)allowsMixedLocalizations;
- (id)availableLocalizations;
- (id)bundleIdentifier;
- (id)bundleURL;
- (id)configurations;
- (id)containerBundleIdentifier;
- (id)containerURL;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)dataProtectionLevel;
- (id)descriptors;
- (void)encodeWithBSXPCCoder:(id)arg1;
- (id)initWithBSXPCCoder:(id)arg1;
- (id)lastModifiedDate;
- (id)mutableCopyWithZone:(struct _NSZone { }*)arg1;
- (id)placeholderURLs;
- (id)snapshotURLs;
- (id)systemDataContainerURL;
- (id)timelineURLs;
- (id)version;
- (bool)wantsLocation;

@end
