/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleMediaServicesUI.framework/AppleMediaServicesUI
 */

@interface AMSUIWebAccountAction : AMSUIWebAction <AMSUIWebActionRunnable> {
    ACAccount * _account;
    bool  _active;
    NSString * _creditString;
}

@property (nonatomic, retain) ACAccount *account;
@property (nonatomic) bool active;
@property (nonatomic, retain) NSString *creditString;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)account;
- (bool)active;
- (id)creditString;
- (id)initWithJSObject:(id)arg1 context:(id)arg2;
- (id)runAction;
- (void)setAccount:(id)arg1;
- (void)setActive:(bool)arg1;
- (void)setCreditString:(id)arg1;

@end
