/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SeymourUI.framework/SeymourUI
 */

@interface SeymourUI.RemoteBrowsingAccountProvider : NSObject {
    void accountProvider;
    void eventHub;
    void selectedUserProfile;
    void source;
}

- (void).cxx_destruct;
- (void)handleSelectedUserProfileChanged:(id)arg1;
- (id)init;

@end
