/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsCore.framework/NewsCore
 */

@interface FCFeedTransformationFilter : NSObject <FCFeedTransforming> {
    NSString * _briefingsTagID;
    FCBundleSubscription * _bundleSubscription;
    long long  _filterOptions;
    NSSet * _mutedTagIDs;
    NSSet * _otherArticleIDs;
    NSSet * _otherClusterIDs;
    <FCPaidAccessCheckerType> * _paidAccessChecker;
    NSSet * _subscribedTagIDs;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)transformationWithFilterOptions:(long long)arg1 configuration:(id)arg2 context:(id)arg3;
+ (id)transformationWithFilterOptions:(long long)arg1 configuration:(id)arg2 context:(id)arg3 otherArticleIDs:(id)arg4;
+ (id)transformationWithFilterOptions:(long long)arg1 otherArticleIDs:(id)arg2 otherClusterIDs:(id)arg3 subscribedTagIDs:(id)arg4 mutedTagIDs:(id)arg5 briefingsTagID:(id)arg6 paidAccessChecker:(id)arg7 bundleSubscription:(id)arg8;

- (void).cxx_destruct;
- (id)transformFeedItems:(id)arg1;
- (id)transformHeadline:(id)arg1;
- (id)transformHeadlines:(id)arg1;
- (id)transformHeadlinesWithResult:(id)arg1;

@end
