/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSMutableHIDEventAuthenticationMessage : BKSHIDEventAuthenticationMessage

@property (nonatomic) unsigned long long context;
@property (nonatomic) unsigned int eventType;
@property (nonatomic) long long keyGeneration;
@property (nonatomic) unsigned long long originIdentifier;
@property (nonatomic) bool registrantEntitled;
@property (nonatomic) long long versionedPID;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)setContext:(unsigned long long)arg1;
- (void)setDestinationAuditToken:(id)arg1;
- (void)setEventType:(unsigned int)arg1;
- (void)setKeyGeneration:(long long)arg1;
- (void)setOriginIdentifier:(unsigned long long)arg1;
- (void)setRegistrantEntitled:(bool)arg1;
- (void)setVersionedPID:(long long)arg1;

@end
