/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/BackBoardServices.framework/BackBoardServices
 */

@interface BKSMutableHIDKeyboardDeviceProperties : BKSHIDKeyboardDeviceProperties

@property (nonatomic) bool capsLockKeyHasLanguageSwitchLabel;
@property (nonatomic) unsigned char countryCode;
@property (nonatomic, copy) NSString *language;
@property (nonatomic, copy) NSString *layout;
@property (nonatomic) unsigned int standardType;
@property (nonatomic) long long subinterfaceID;

- (void)setCapsLockKeyHasLanguageSwitchLabel:(bool)arg1;
- (void)setCountryCode:(unsigned char)arg1;
- (void)setLanguage:(id)arg1;
- (void)setLayout:(id)arg1;
- (void)setStandardType:(unsigned int)arg1;
- (void)setSubinterfaceID:(long long)arg1;

@end
