/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SearchFoundation.framework/SearchFoundation
 */

@interface SFStartLocalSearchFeedback : SFStartSearchFeedback {
    unsigned long long  _indexType;
    unsigned long long  _searchType;
}

@property (nonatomic) unsigned long long indexType;
@property (nonatomic) unsigned long long searchType;

+ (bool)supportsSecureCoding;

- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)indexType;
- (id)initWithCoder:(id)arg1;
- (id)initWithInput:(id)arg1 triggerEvent:(unsigned long long)arg2 indexType:(unsigned long long)arg3;
- (id)initWithInput:(id)arg1 triggerEvent:(unsigned long long)arg2 indexType:(unsigned long long)arg3 queryId:(unsigned long long)arg4;
- (id)initWithInput:(id)arg1 triggerEvent:(unsigned long long)arg2 searchType:(unsigned long long)arg3 indexType:(unsigned long long)arg4 queryId:(unsigned long long)arg5;
- (unsigned long long)searchType;
- (void)setIndexType:(unsigned long long)arg1;
- (void)setSearchType:(unsigned long long)arg1;

@end
