/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriPlaybackControlIntents.framework/SiriPlaybackControlIntents
 */

@interface AddSpeakerIntent : INIntent

@property (nonatomic, copy) NSArray *destinations;
@property (nonatomic, copy) NSArray *deviceContext;
@property (nonatomic, copy) NSArray *deviceQueries;
@property (nonatomic) long long mediaType;
@property (nonatomic, copy) MediaStream *source;

@end
