/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriPlaybackControlIntents.framework/SiriPlaybackControlIntents
 */

@interface DeviceGroup : INObject

@property (nonatomic, readonly) NSString *description;
@property (nonatomic, copy) NSNumber *excludeGroup;
@property (nonatomic, copy) NSString *groupName;
@property (nonatomic, copy) NSNumber *includesTVs;
@property (nonatomic, copy) NSArray *streams;
@property (nonatomic) long long type;

- (id)description;

@end
