/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFCommandExecutionInfo : NSObject <AFDictionaryConvertible, NSCopying, NSSecureCoding> {
    NSArray * _deviceRestrictions;
    AFEndpointInfo * _endpointInfo;
    NSString * _executionID;
    AFInstanceInfo * _instanceInfo;
    AFPeerInfo * _originPeerInfo;
    AFRequestHandlingContext * _requestHandlingContextSnapshot;
    NSString * _requestID;
    AFSpeechInfo * _speechInfo;
    NSDictionary * _userInfo;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSArray *deviceRestrictions;
@property (nonatomic, readonly, copy) AFEndpointInfo *endpointInfo;
@property (nonatomic, readonly, copy) NSString *executionID;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly, copy) AFInstanceInfo *instanceInfo;
@property (nonatomic, readonly, copy) AFPeerInfo *originPeerInfo;
@property (nonatomic, readonly, copy) AFRequestHandlingContext *requestHandlingContextSnapshot;
@property (nonatomic, readonly, copy) NSString *requestID;
@property (nonatomic, readonly, copy) AFSpeechInfo *speechInfo;
@property (readonly) Class superclass;
@property (nonatomic, readonly, copy) NSDictionary *userInfo;

+ (id)newWithBuilder:(id /* block */)arg1;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)_descriptionWithIndent:(unsigned long long)arg1;
- (id)buildDictionaryRepresentation;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)deviceRestrictions;
- (void)encodeWithCoder:(id)arg1;
- (id)endpointInfo;
- (id)executionID;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithExecutionID:(id)arg1 requestID:(id)arg2 originPeerInfo:(id)arg3 endpointInfo:(id)arg4 instanceInfo:(id)arg5 speechInfo:(id)arg6 requestHandlingContextSnapshot:(id)arg7 deviceRestrictions:(id)arg8 userInfo:(id)arg9;
- (id)instanceInfo;
- (bool)isEqual:(id)arg1;
- (id)mutatedCopyWithMutator:(id /* block */)arg1;
- (id)originPeerInfo;
- (id)requestHandlingContextSnapshot;
- (id)requestID;
- (id)speechInfo;
- (id)userInfo;

@end
