/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AssistantServices.framework/AssistantServices
 */

@interface AFMyriadGoodnessScoreEvaluator : NSObject <AFSettingsDelegate> {
    AFInstanceContext * _deviceInstanceContext;
    bool  _evaluateForAudioAccessory;
    double  _lastActivationTime;
    unsigned char  _myriadPlatformBias;
    unsigned long long  _platformBiasAcquisitionState;
    AFPreferences * _pref;
    NSObject<OS_dispatch_queue> * _queue;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _scoreEvaluationLock;
    AFSettingsConnection * _settingsConnection;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) bool evaluateForAudioAccessory;
@property (readonly) unsigned long long hash;
@property (nonatomic) double lastActivationTime;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_fetchDevicePlatformBiasIfRequired;
- (void)_settingsConnectionDidDisconnect;
- (void)_updatePlatformBias:(unsigned char)arg1;
- (unsigned char)bumpGoodnessScore:(id)arg1 lastActivationTime:(double)arg2 mediaPlaybackInterruptedTime:(double)arg3 ignoreAdjustedBoost:(bool)arg4;
- (bool)evaluateForAudioAccessory;
- (unsigned char)getMyriadAdjustedBoostForGoodnessScoreContext:(id)arg1;
- (unsigned char)getPlatformBias;
- (unsigned char)getRecentBump:(double)arg1 ignoreAdjustedBoost:(bool)arg2;
- (id)initWithDeviceInstanceContext:(id)arg1 queue:(id)arg2;
- (double)lastActivationTime;
- (void)preheat;
- (void)setLastActivationTime:(double)arg1;

@end
