/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInference.framework/SiriInference
 */

@interface SiriInference.ExperimentUpdater : SiriInference.XPCActivityOperation {
    void experiment;
}

- (void).cxx_destruct;
- (id)init;
- (void)main;

@end
