/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatGroupCompilerScope : _TtCs12_SwiftObject {
    void context;
    void group;
    void inputSlotDefinitions;
    void seenReferences;
    void seenSlotIdentifiers;
    void slotDefinitionStates;
    void usedProperties;
}

@end
