/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatLayoutViewRenderer : _TtCs12_SwiftObject {
    void adMetricsNodeRenderer;
    void buttonNodeRenderer;
    void commandCenter;
    void customNodeRenderer;
    void imageNodeRenderer;
    void layeredMediaNodeRenderer;
    void micaNodeRenderer;
    void presentingViewController;
    void rendererTool;
    void stateViewNodeRenderer;
    void textNodeRenderer;
    void timer;
    void videoNodeRenderer;
    void viewNodeRenderer;
    void webEmbedNodeRenderer;
    void webEmbedViewControllerReuseManager;
}

@end
