/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatTextNode : _TtCs12_SwiftObject {
    void _adjustments;
    void _identifier;
    void _selectors;
    void _zIndex;
    void accessibility;
    void accessibilityRole;
    void content;
    void invalidation;
    void size;
    void style;
}

@end
