/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatIssue : _TtCs12_SwiftObject {
    void identifier;
    void overrides;
}

@end
