/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsFeed.framework/NewsFeed
 */

@interface NewsFeed.FormatDecorationCompilerScope : _TtCs12_SwiftObject {
    void context;
    void decoration;
    void usedProperties;
}

@end
