/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SoundBoardServices.framework/SoundBoardServices
 */

@interface SBSProximityHandoffUI : NSObject <SBSProximityHandoffUICallerDelegate> {
    <SBSProximityHandoffUIDelegate> * _delegate;
    <SBSProximityHandoffUIImplementer> * _sbProxy;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <SBSProximityHandoffUIDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) <SBSProximityHandoffUIImplementer> *sbProxy;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)cancel:(id)arg1;
- (void)complete;
- (id)delegate;
- (void)handoffCancelled;
- (void)handoffCompleted;
- (void)handoffInactive;
- (void)handoffStarted;
- (void)handoffUpdating;
- (id)init;
- (id)initWithProxy:(id)arg1;
- (id)sbProxy;
- (void)setDelegate:(id)arg1;
- (void)setSbProxy:(id)arg1;
- (void)start;
- (void)updateIntensity:(float)arg1;

@end
