/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSpeechFoundation.framework/CoreSpeechFoundation
 */

@interface CSAudioTimeConverterPool : NSObject {
    CSAudioTimeConverter * _defaultTimeConverter;
    NSMutableDictionary * _pool;
    NSObject<OS_dispatch_queue> * _queue;
}

@property (nonatomic, retain) CSAudioTimeConverter *defaultTimeConverter;
@property (nonatomic, retain) NSMutableDictionary *pool;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queue;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)_getAudioTimeConverterWithDeviceId:(id)arg1;
- (id)converterForDeviceId:(id)arg1;
- (id)defaultConverter;
- (id)defaultTimeConverter;
- (id)init;
- (id)pool;
- (id)queue;
- (void)setDefaultTimeConverter:(id)arg1;
- (void)setPool:(id)arg1;
- (void)setQueue:(id)arg1;

@end
