/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSpeechFoundation.framework/CoreSpeechFoundation
 */

@interface CSVoiceTriggerEventInfoProvider : NSObject {
    NSString * _remoteDeviceId;
    NSDictionary * _rtsTriggerInfo;
    unsigned long long  _triggerNotifiedMachTime;
    NSDictionary * _voiceTriggerInfo;
}

@property (nonatomic, copy) NSString *remoteDeviceId;
@property (nonatomic, copy) NSDictionary *rtsTriggerInfo;
@property (nonatomic) unsigned long long triggerNotifiedMachTime;
@property (nonatomic, copy) NSDictionary *voiceTriggerInfo;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)remoteDeviceId;
- (id)rtsTriggerInfo;
- (void)setRemoteDeviceId:(id)arg1;
- (void)setRtsTriggerInfo:(id)arg1;
- (void)setTriggerNotifiedMachTime:(unsigned long long)arg1;
- (void)setVoiceTriggerInfo:(id)arg1;
- (unsigned long long)triggerNotifiedMachTime;
- (id)voiceTriggerInfo;

@end
