/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKBusinessChatTransactionDisputeContext : NSObject <PKBusinessChatContext> {
    PKAccount * _account;
    PKAccountUser * _accountUser;
    bool  _disputingAccountUserTransaction;
    PKFamilyMember * _familyMember;
    long long  _intent;
    PKPaymentPass * _paymentPass;
    PKPaymentTransaction * _transaction;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)bodyText;
- (id)businessIdentifier;
- (id)groupParameters;
- (id)initWithPaymentPass:(id)arg1 transaction:(id)arg2 account:(id)arg3 accountUser:(id)arg4 familyMember:(id)arg5 intent:(long long)arg6;
- (id)intentParameters;
- (bool)requiresAuthorization;

@end
