/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKFormattableTextFieldTableViewCell : UITableViewCell {
    PKFormattableTextFieldFormatter * _formatter;
    UITextField * _textField;
}

@property (nonatomic, retain) PKFormattableTextFieldFormatter *formatter;
@property (nonatomic, readonly) UITextField *textField;

- (void).cxx_destruct;
- (id)formatter;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)layoutSubviews;
- (void)setFormatter:(id)arg1;
- (id)textField;

@end
