/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKPGSVSectionHeaderView : UIView <PKPGSVSectionHeaderView> {
    UIButton * _actionButton;
    UIActivityIndicatorView * _activityIndicator;
    <PKPGSVSectionHeaderViewDelegate> * _delegate;
    UILabel * _environmentLabel;
    PKButtonBadgeView * _inboxBadge;
    UIButton * _inboxButton;
    struct UIEdgeInsets { 
        double top; 
        double left; 
        double bottom; 
        double right; 
    }  _margins;
    unsigned long long  _passType;
    bool  _showActivityIndicator;
    bool  _sizesDirty;
    UILabel * _titleView;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long passType;
@property (nonatomic) bool showActivityIndicator;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)_addTapped;
- (id)_inboxBadgeValue;
- (void)_inboxTapped;
- (bool)_shouldShowInboxButton;
- (bool)_shouldShowMoreInfoButtonForBarcodePass;
- (void)addTapped;
- (void)inboxTapped;
- (id)init;
- (id)initWithPassType:(unsigned long long)arg1 delegate:(id)arg2;
- (void)layoutSubviews;
- (id)leadingView;
- (bool)needsUpdate;
- (unsigned long long)passType;
- (void)setShowActivityIndicator:(bool)arg1;
- (bool)showActivityIndicator;
- (id)trailingView;
- (void)traitCollectionDidChange:(id)arg1;

@end
