/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKSettingsRowDiffableDataSource : PKTableViewDiffableDataSource

- (id)initWithTableView:(id)arg1;

@end
