/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKSettingsTableViewConfiguration : NSObject {
    NSDiffableDataSourceSnapshot * _currentSnapshot;
}

@property (nonatomic, readonly) NSArray *sections;

- (void).cxx_destruct;
- (void)appendSection:(id)arg1 rows:(id)arg2;
- (id)rowsForSection:(id)arg1;
- (id)sections;
- (id)snapshot;

@end
