/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PassKitUI.framework/PassKitUI
 */

@interface PKSpendingSummaryViewController : UIViewController <PKSpendingSingleSummaryViewControllerDelegate, PKSpendingSummaryFetcherObserver, UIScrollViewDelegate> {
    PKAccount * _account;
    PKAccountUserCollection * _accountUserCollection;
    PKContactAvatarManager * _avatarManager;
    double  _collectionViewVerticalOffset;
    NSCalendar * _currentCalendar;
    NSArray * _currentDataSet;
    double  _currentHeight;
    NSArray * _currentMonthTransactions;
    unsigned long long  _currentSummaryType;
    double  _currentWidth;
    <PKSpendingSummaryViewControllerDelegate> * _delegate;
    unsigned long long  _displayType;
    PKFamilyMemberCollection * _familyCollection;
    PKSpendingSummaryFooterContainer * _footerView;
    bool  _hasPrefetchedLeft;
    bool  _hasPrefetchedRight;
    NSMutableDictionary * _indicesToVCMapping;
    bool  _isDragging;
    bool  _isLowEndDevice;
    bool  _isScrolling;
    struct os_unfair_lock_s { 
        unsigned int _os_unfair_lock_opaque; 
    }  _lockUpdate;
    NSArray * _months;
    NSString * _navTitle;
    NSMutableDictionary * _nonVisibleIndicesToVCMapping;
    unsigned long long  _numberOfItems;
    PKPaymentPass * _pass;
    NSMutableDictionary * _pendingCollectionViewUpdates;
    NSMutableDictionary * _pendingUpdates;
    struct CGRect { 
        struct CGPoint { 
            double x; 
            double y; 
        } origin; 
        struct CGSize { 
            double width; 
            double height; 
        } size; 
    }  _previousBounds;
    unsigned long long  _primaryIndex;
    NSObject<OS_dispatch_source> * _scrollTimer;
    UIScrollView * _scrollView;
    unsigned long long  _selectionType;
    PKSpendingSummaryFetcher * _summaryFetcher;
    NSArray * _summaryVCs;
    PKTransactionSourceCollection * _transactionSourceCollection;
    bool  _transitioningMode;
    NSMutableSet * _unusedVCs;
    NSIndexSet * _visibleIndices;
    NSArray * _weeks;
    NSArray * _years;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <PKSpendingSummaryViewControllerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (bool)_canReloadVCs;
- (void)_changeModeTo:(unsigned long long)arg1;
- (id)_dequeueNonVisibleVCForIndex:(unsigned long long)arg1;
- (id)_dequeueVCForIndex:(unsigned long long)arg1;
- (double)_endOfItemAtIndex:(unsigned long long)arg1;
- (unsigned long long)_indexAtContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (void)_layoutCollectionViews;
- (void)_loadSummariesForContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (unsigned long long)_newDataSetIndexAfterTransitionFromMode:(unsigned long long)arg1 toMode:(unsigned long long)arg2;
- (unsigned long long)_primaryIndexAtOffset:(struct CGPoint { double x1; double x2; })arg1;
- (id)_recoverUnusedVC;
- (void)_reloadDataForVCAtIndex:(unsigned long long)arg1 swap:(bool)arg2;
- (void)_reloadPendingVCs;
- (void)_reportTappedButtonWithTag:(id)arg1;
- (void)_retireVCForIndex:(unsigned long long)arg1;
- (void)_scrollViewStoppedScrolling;
- (double)_startOfItemAtIndex:(unsigned long long)arg1;
- (void)_switchPrimaryIndexToIndex:(unsigned long long)arg1;
- (double)_transitionProgress;
- (void)_updateAlphaAndFooterDuringTransition;
- (void)_updatePrimaryViewScrolling;
- (void)_updateScrollViewContentSize;
- (id)_visibileIndicesAtContentOffset:(struct CGPoint { double x1; double x2; })arg1;
- (double)_yPositionForNonPrimaryVCs;
- (void)dealloc;
- (id)delegate;
- (id)initWithTransactionSourceCollection:(id)arg1 familyCollection:(id)arg2 avatarManager:(id)arg3 account:(id)arg4 accountUserCollection:(id)arg5 fetcher:(id)arg6 weeks:(id)arg7 months:(id)arg8 years:(id)arg9 type:(unsigned long long)arg10 unit:(unsigned long long)arg11 currentMonthTransactions:(id)arg12 upcomingScheduledPayments:(id)arg13 dispayType:(unsigned long long)arg14;
- (void)invalidatedSpendingSummaryOfType:(unsigned long long)arg1 startingWithDate:(id)arg2;
- (void)invalidatedSummariesAvailable;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint { double x1; double x2; })arg2 targetContentOffset:(inout struct CGPoint { double x1; double x2; }*)arg3;
- (void)setDelegate:(id)arg1;
- (void)spendingSingleSummaryViewController:(id)arg1 changedSelection:(unsigned long long)arg2;
- (void)spendingSingleSummaryViewController:(id)arg1 scrollViewDidScroll:(id)arg2;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;

@end
