/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ODML.framework/ODML
 */

@interface APOdmlPrivatizingService : APOdmlSingleton <APOdmlPrivatizing, NSXPCListenerDelegate> {
    NSXPCListener * _listener;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (retain) NSXPCListener *listener;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (void)addPrivatization:(id)arg1 recipe:(id)arg2 completion:(id /* block */)arg3;
- (id)init;
- (id)listener;
- (bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (void)setListener:(id)arg1;

@end
