/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ODML.framework/ODML
 */

@interface APOdmlDESRecord : NSObject {
    NSMutableDictionary * _adRecords;
    APOdmlVector * _appUsageVector;
    APOdmlSettings * _odmlSettings;
    bool  _organicsExist;
    NSArray * _organicsList;
    NSArray * _originalAdOrderList;
    NSMutableArray * _postWriteOperations;
    NSUUID * _recordIdentifier;
    DESRecordStore * _recordStore;
    NSString * _requestID;
    NSArray * _rerankedAdOrderList;
    bool  _shouldMakeRecord;
    bool  _writingInProgress;
}

@property (nonatomic, retain) NSMutableDictionary *adRecords;
@property (nonatomic, retain) APOdmlVector *appUsageVector;
@property (nonatomic, retain) APOdmlSettings *odmlSettings;
@property (nonatomic) bool organicsExist;
@property (nonatomic, retain) NSArray *organicsList;
@property (nonatomic, retain) NSArray *originalAdOrderList;
@property (nonatomic, retain) NSMutableArray *postWriteOperations;
@property (nonatomic, retain) NSUUID *recordIdentifier;
@property (nonatomic, retain) DESRecordStore *recordStore;
@property (nonatomic, retain) NSString *requestID;
@property (nonatomic, retain) NSArray *rerankedAdOrderList;
@property (nonatomic) bool shouldMakeRecord;
@property bool writingInProgress;

- (void).cxx_destruct;
- (id)adRecords;
- (void)addAdListToDES:(id)arg1 organics:(id)arg2;
- (id)appUsageVector;
- (id)dictionaryRepresentation;
- (void)handleSaveCompletion:(id)arg1 error:(id)arg2;
- (id)initWithRequestID:(id)arg1;
- (id)odmlSettings;
- (bool)organicsExist;
- (id)organicsList;
- (id)originalAdOrderList;
- (void)performAfterWrite:(id /* block */)arg1;
- (id)postWriteOperations;
- (id)recordData;
- (id)recordIdentifier;
- (id)recordStore;
- (id)requestID;
- (id)rerankedAdOrderList;
- (void)saveDESRecord:(id)arg1 info:(id)arg2;
- (void)setAdRecords:(id)arg1;
- (void)setAppUsageVector:(id)arg1;
- (void)setOdmlSettings:(id)arg1;
- (void)setOrganicsExist:(bool)arg1;
- (void)setOrganicsList:(id)arg1;
- (void)setOriginalAdOrderList:(id)arg1;
- (void)setPostWriteOperations:(id)arg1;
- (void)setRecordIdentifier:(id)arg1;
- (void)setRecordStore:(id)arg1;
- (void)setRequestID:(id)arg1;
- (void)setRerankedAdOrderList:(id)arg1;
- (void)setShouldMakeRecord:(bool)arg1;
- (void)setWritingInProgress:(bool)arg1;
- (bool)shouldMakeRecord;
- (void)updateAd:(id)arg1 event:(long long)arg2;
- (void)updateRerankedAdList:(id)arg1;
- (void)writeDESRecord;
- (bool)writingInProgress;

@end
