/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AppTrackingTransparency.framework/AppTrackingTransparency
 */

@interface ATFollowUpManager : NSObject

+ (void)presentFollowUpInterfaceWithApplicationCount:(unsigned long long)arg1 trackerCount:(unsigned long long)arg2 completionHandler:(id /* block */)arg3;

@end
