/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVideoIntents.framework/SiriVideoIntents
 */

@interface _TtC16SiriVideoIntentsP33_EDFFBCC65375BB155F1EEB5FFCCCD06219AppSelectionContext : _TtCs12_SwiftObject {
    void _lastResultBundleIdentifier;
}

@end
