/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriVideoIntents.framework/SiriVideoIntents
 */

@interface SiriVideoIntents.INSearchForMediaNeedsConfirmationStrategy : _TtCs12_SwiftObject {
    void deviceState;
    void dialogProvider;
}

@end
