/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAutomationInternal.framework/HomeAutomationInternal
 */

@interface HomeAutomationInternal.KeepAboveOrBelowTemperatureHandler : _TtCs12_SwiftObject

@end
