/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAutomationInternal.framework/HomeAutomationInternal
 */

@interface HomeAutomationInternal.SessionContext : _TtCs12_SwiftObject {
    void backToComfortableTemperature;
    void climateState;
    void isAlreadyHeatingCooling;
    void previousIntents;
    void previousNLIntents;
    void previousResponses;
}

@end
