/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAutomationInternal.framework/HomeAutomationInternal
 */

@interface HomeAutomationInternal.NativeHome : HomeAutomationInternal.NativeEntity {
    void home;
}

@end
