/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WebCore.framework/WebCore
 */

@interface WebAVAudioSessionAvailableInputsListener : NSObject {
    struct AVAudioSessionCaptureDeviceManager { int (**x1)(); struct Optional<WTF::Vector<WebCore::CaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> { bool x_2_1_1; union storage_t<WTF::Vector<WebCore::CaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> { unsigned char x_2_2_1; struct Vector<WebCore::CaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct CaptureDevice {} *x_2_3_1; unsigned int x_2_3_2; unsigned int x_2_3_3; } x_2_2_2; } x_2_1_2; } x2; struct Vector<WebCore::CaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct CaptureDevice {} *x_3_1_1; unsigned int x_3_1_2; unsigned int x_3_1_3; } x3; struct Optional<WTF::Vector<WebCore::AVAudioSessionCaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> { bool x_4_1_1; union storage_t<WTF::Vector<WebCore::AVAudioSessionCaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> { unsigned char x_2_2_1; struct Vector<WebCore::AVAudioSessionCaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct AVAudioSessionCaptureDevice {} *x_2_3_1; unsigned int x_2_3_2; unsigned int x_2_3_3; } x_2_2_2; } x_4_1_2; } x4; } * _callback;
}

- (id)initWithCallback:(struct AVAudioSessionCaptureDeviceManager { int (**x1)(); struct Optional<WTF::Vector<WebCore::CaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> { bool x_2_1_1; union storage_t<WTF::Vector<WebCore::CaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> { unsigned char x_2_2_1; struct Vector<WebCore::CaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct CaptureDevice {} *x_2_3_1; unsigned int x_2_3_2; unsigned int x_2_3_3; } x_2_2_2; } x_2_1_2; } x2; struct Vector<WebCore::CaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct CaptureDevice {} *x_3_1_1; unsigned int x_3_1_2; unsigned int x_3_1_3; } x3; struct Optional<WTF::Vector<WebCore::AVAudioSessionCaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> { bool x_4_1_1; union storage_t<WTF::Vector<WebCore::AVAudioSessionCaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> { unsigned char x_2_2_1; struct Vector<WebCore::AVAudioSessionCaptureDevice, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct AVAudioSessionCaptureDevice {} *x_2_3_1; unsigned int x_2_3_2; unsigned int x_2_3_3; } x_2_2_2; } x_4_1_2; } x4; }*)arg1 audioSession:(id)arg2;
- (void)invalidate;
- (void)routeDidChange:(id)arg1;

@end
