/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKPlaceCollectionImageProvider : NSObject <NSCacheDelegate> {
    NSObject<OS_dispatch_queue> * _blurQueue;
    NSCache * _blurredImagesCache;
    NSMutableDictionary * _blurringOperationsPair;
    NSMutableDictionary * _downloadOperationsPair;
    NSCache * _downloadedImagesCache;
    bool  _isRTL;
    GEOMapItemPhotoOptions * _optionsForCollectionCells;
    double  _screenScale;
}

@property (nonatomic, retain) NSObject<OS_dispatch_queue> *blurQueue;
@property (nonatomic, retain) NSCache *blurredImagesCache;
@property (nonatomic, retain) NSMutableDictionary *blurringOperationsPair;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, retain) NSMutableDictionary *downloadOperationsPair;
@property (nonatomic, retain) NSCache *downloadedImagesCache;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool isRTL;
@property (nonatomic, readonly) GEOMapItemPhotoOptions *optionsForCollectionCells;
@property (nonatomic) double screenScale;
@property (readonly) Class superclass;

+ (id)sharedInstance;

- (void).cxx_destruct;
- (id)blurQueue;
- (id)blurredImagesCache;
- (id)blurringOperationsPair;
- (void)cache:(id)arg1 willEvictObject:(id)arg2;
- (void)cancelAllOperationsForImageSource:(long long)arg1;
- (void)checkQueuesForSource:(long long)arg1;
- (void)darkenAndBlurImage:(id)arg1 completion:(id /* block */)arg2;
- (struct CGSize { double x1; double x2; })desiredSizeFromFrameSize:(struct CGSize { double x1; double x2; })arg1;
- (id)downloadOperationsPair;
- (id)downloadedImagesCache;
- (id)init;
- (bool)isRTL;
- (id)joeColorForCuratedCollection:(id)arg1;
- (void)loadBlurredCoverImageWithCuratedCollection:(id)arg1 size:(struct CGSize { double x1; double x2; })arg2 imageSizeType:(long long)arg3 contentSizeCategory:(id)arg4 usingImageSource:(long long)arg5 completion:(id /* block */)arg6;
- (id)optionsForCollectionCells;
- (id)photoInfoWithPhoto:(id)arg1 desiredSize:(struct CGSize { double x1; double x2; })arg2;
- (double)screenScale;
- (void)setBlurQueue:(id)arg1;
- (void)setBlurredImagesCache:(id)arg1;
- (void)setBlurringOperationsPair:(id)arg1;
- (void)setDownloadOperationsPair:(id)arg1;
- (void)setDownloadedImagesCache:(id)arg1;
- (void)setIsRTL:(bool)arg1;
- (void)setScreenScale:(double)arg1;

@end
