/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MapKit.framework/MapKit
 */

@interface MKPlaceCollectionImageNoGradientOperation : NSOperation {
    NSString * _cacheID;
    NSCache * _downloadCache;
    NSCache * _gradientCache;
    NSURL * _url;
}

@property (nonatomic, readonly) NSString *cacheID;
@property (nonatomic, readonly) NSCache *downloadCache;
@property (nonatomic, readonly) NSCache *gradientCache;
@property (nonatomic, readonly) NSURL *url;

- (void).cxx_destruct;
- (id)cacheID;
- (id)downloadCache;
- (id)gradientCache;
- (id)initWithURL:(id)arg1 downloadCache:(id)arg2 gradientCache:(id)arg3 cacheID:(id)arg4;
- (void)main;
- (id)url;

@end
