/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaFoundation.framework/MediaFoundation
 */

@interface MediaFoundation.InternalPlaybackStackController : _TtCs12_SwiftObject <MFStateDumpable> {
    void $__lazy_storage_$_skipAggregator;
    void assetLoadingId;
    void backgroundTaskController;
    void currentQueueControllerItem;
    void currentQueueRestorationItem;
    void deferredPlaybackRateForNextSetQueue;
    void delegate;
    void errorController;
    void externalPlaybackController;
    void inFlightSetQueueLoadingContext;
    void lastSetQueueIdentifier;
    void loadedQueueControllerItems;
    void maximumPlayerQueueLength;
    void playerController;
    void playerItemStateSnapshot;
    void queueAssetLoader;
    void queueController;
    void reporter;
    void skippingState;
    void stackVersion;
    void synchronizingToPlayer;
}

@property (nonatomic, readonly) NSDictionary *stateDictionary;

- (id)stateDictionary;

@end
