/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaFoundation.framework/MediaFoundation
 */

@interface MediaFoundation.PlayingState : MediaFoundation.TransportableState {
    void isStalled;
    void playbackDidStopReceived;
    void resumeOnEnter;
}

@end
