/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSpeechSynthesis.framework/SiriSpeechSynthesis
 */

@interface QSSMutableBatchTranslationStreamingResponse : QSSBatchTranslationStreamingResponse

@property (nonatomic, copy) QSSBatchTranslationResponse *contentAsQSSBatchTranslationResponse;
@property (nonatomic, copy) QSSFinalBlazarResponse *contentAsQSSFinalBlazarResponse;
@property (nonatomic) long long content_type;

- (id)contentAsQSSBatchTranslationResponse;
- (id)contentAsQSSFinalBlazarResponse;
- (long long)content_type;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;
- (void)setContentAsQSSBatchTranslationResponse:(id)arg1;
- (void)setContentAsQSSFinalBlazarResponse:(id)arg1;
- (void)setContent_type:(long long)arg1;

@end
