/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriSpeechSynthesis.framework/SiriSpeechSynthesis
 */

@interface SFSpeechSynthesisVoice : NSObject {
    NSString * _gender;
    bool  _isDefault;
    NSLocale * _locale;
    NSString * _name;
    SFSSResourceAsset * _resourceAsset;
    SFSSVoiceAsset * _voiceAsset;
    long long  _voiceReleaseType;
    long long  _voiceType;
}

@property (nonatomic, readonly) NSString *gender;
@property (nonatomic, readonly) bool isDefault;
@property (nonatomic, readonly) NSLocale *locale;
@property (nonatomic, readonly) NSString *name;
@property (nonatomic, retain) SFSSResourceAsset *resourceAsset;
@property (nonatomic, retain) SFSSVoiceAsset *voiceAsset;
@property (nonatomic) long long voiceReleaseType;
@property (nonatomic) long long voiceType;

+ (id)getDefaultVoiceByLocale:(id)arg1;
+ (id)getVoiceByName:(id)arg1;
+ (void)initialize;
+ (id)supportedLocales;
+ (id)supportedVoicesByLocale:(id)arg1;

- (void).cxx_destruct;
- (id)gender;
- (id)init:(id)arg1 gender:(id)arg2 name:(id)arg3 isDefault:(bool)arg4;
- (bool)isDefault;
- (id)locale;
- (id)name;
- (id)resourceAsset;
- (void)setResourceAsset:(id)arg1;
- (void)setVoiceAsset:(id)arg1;
- (void)setVoiceReleaseType:(long long)arg1;
- (void)setVoiceType:(long long)arg1;
- (id)voiceAsset;
- (long long)voiceReleaseType;
- (long long)voiceType;

@end
