/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/NearbyInteraction.framework/NearbyInteraction
 */

@interface NIConfiguration : NSObject <NSCopying, NSSecureCoding> {
    unsigned long long  _suspensionPolicy;
}

@property unsigned long long suspensionPolicy;

+ (id)new;
+ (bool)supportsSecureCoding;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initInternal;
- (id)initWithCoder:(id)arg1;
- (id)initWithConfiguration:(id)arg1;
- (bool)isEqualToConfiguration:(id)arg1;
- (void)setSuspensionPolicy:(unsigned long long)arg1;
- (unsigned long long)suspensionPolicy;

@end
