/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotosUICore.framework/PhotosUICore
 */

@interface PXCuratedLibraryFilterActionPerformer : PXCuratedLibraryActionPerformer <PXContentFilterControllerDelegate, UIAdaptivePresentationControllerDelegate> {
    PXUIContentFilterController * _contentFilterController;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)activitySystemImageName;
- (id)activityType;
- (bool)canPerformWithActivityItems:(id)arg1 forActivity:(id)arg2;
- (void)contentFilterController:(id)arg1 filterStateChanged:(id)arg2;
- (void)contentFilterControllerDidComplete:(id)arg1;
- (id)initWithActionType:(id)arg1 viewModel:(id)arg2;
- (void)performUserInteractionTask;
- (bool)performerResetsAfterCompletion;
- (void)presentationControllerDidDismiss:(id)arg1;

@end
