/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFAudio.framework/AVFAudio
 */

@interface AudioPlayerImpl : NSObject {
    NSDictionary * _actualSettings;
    AVAudioSession * _audioSession;
    NSArray * _channelAssignments;
    NSData * _data;
    <AVAudioPlayerDelegate> * _delegate;
    unsigned long long  _endInterruptionFlags;
    AVAudioFormat * _format;
    NSObject<OS_dispatch_queue> * _gcd;
    struct AVAudioPlayerCpp { struct __CFData {} *x1; struct __CFURL {} *x2; struct __CFDictionary {} *x3; unsigned int x4; struct AudioStreamBasicDescription { double x_5_1_1; unsigned int x_5_1_2; unsigned int x_5_1_3; unsigned int x_5_1_4; unsigned int x_5_1_5; unsigned int x_5_1_6; unsigned int x_5_1_7; unsigned int x_5_1_8; unsigned int x_5_1_9; } x5; struct AudioStreamBasicDescription { double x_6_1_1; unsigned int x_6_1_2; unsigned int x_6_1_3; unsigned int x_6_1_4; unsigned int x_6_1_5; unsigned int x_6_1_6; unsigned int x_6_1_7; unsigned int x_6_1_8; unsigned int x_6_1_9; } x6; unsigned int x7; unsigned long long x8; char *x9; unsigned int x10; struct AudioFormatListItem {} *x11; unsigned int x12; struct OpaqueAudioFileID {} *x13; unsigned int x14; struct OpaqueAudioQueue {} *x15; long long x16; long long x17; long long x18; double x19; double x20; double x21; double x22; unsigned int x23; double x24; int x25; struct AudioFilePacketTableInfo { long long x_26_1_1; int x_26_1_2; int x_26_1_3; } x26; long long x27; long long x28; int x29; } * _localPlayer;
    bool  _playRetain;
    bool  _sessionListenerWasSet;
    NSURL * _url;
}

- (void)dealloc;
- (id)init;

@end
