/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/AVFAudio.framework/AVFAudio
 */

@interface AVMusicTrack : NSObject {
    void * _impl;
}

@property (nonatomic, retain) AVAudioUnit *destinationAudioUnit;
@property (nonatomic) unsigned int destinationMIDIEndpoint;
@property (nonatomic) double lengthInBeats;
@property (nonatomic) double lengthInSeconds;
@property (nonatomic) struct _AVBeatRange { double x1; double x2; } loopRange;
@property (getter=isLoopingEnabled, nonatomic) bool loopingEnabled;
@property (getter=isMuted, nonatomic) bool muted;
@property (nonatomic) long long numberOfLoops;
@property (nonatomic) double offsetTime;
@property (getter=isSoloed, nonatomic) bool soloed;
@property (nonatomic, readonly) unsigned long long timeResolution;

- (void)dealloc;
- (id)destinationAudioUnit;
- (unsigned int)destinationMIDIEndpoint;
- (unsigned long long)index;
- (id)initWithImpl:(struct MusicTrackImpl { struct OpaqueMusicTrack {} *x1; id x2; bool x3; unsigned int x4; }*)arg1;
- (bool)isLoopingEnabled;
- (bool)isMuted;
- (bool)isSoloed;
- (double)lengthInBeats;
- (double)lengthInSeconds;
- (struct _AVBeatRange { double x1; double x2; })loopRange;
- (long long)numberOfLoops;
- (double)offsetTime;
- (void)setDestinationAudioUnit:(id)arg1;
- (void)setDestinationMIDIEndpoint:(unsigned int)arg1;
- (void)setLengthInBeats:(double)arg1;
- (void)setLengthInSeconds:(double)arg1;
- (void)setLoopRange:(struct _AVBeatRange { double x1; double x2; })arg1;
- (void)setLoopingEnabled:(bool)arg1;
- (void)setMuted:(bool)arg1;
- (void)setNumberOfLoops:(long long)arg1;
- (void)setOffsetTime:(double)arg1;
- (void)setSoloed:(bool)arg1;
- (void)setUsesAutomatedParameters:(bool)arg1;
- (unsigned long long)timeResolution;
- (struct OpaqueMusicTrack { }*)track;
- (bool)usesAutomatedParameters;

@end
