/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreSpeech.framework/CoreSpeech
 */

@interface CSAcousticSLProxy : NSObject <SLProgressiveCheckerAnalyzerDelegate> {
    SLProgressiveCheckerAnalyzer * _acousticAnalyzer;
    CSAudioRecordContext * _context;
    CSAsset * _currentAsset;
    <CSAcousticSLProxyDelegate> * _delegate;
    bool  _isShadowModeEnabled;
    SLProgressiveCheckerResult * _latestResult;
    NSObject<OS_dispatch_queue> * _queue;
    id /* block */  _reportResultBlock;
    bool  _sessionInProgress;
    unsigned long long  _supportedRecordType;
    NSArray * _thresholds;
}

@property (nonatomic, retain) SLProgressiveCheckerAnalyzer *acousticAnalyzer;
@property (nonatomic, retain) CSAudioRecordContext *context;
@property (nonatomic, retain) CSAsset *currentAsset;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <CSAcousticSLProxyDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic) bool isShadowModeEnabled;
@property (nonatomic, retain) SLProgressiveCheckerResult *latestResult;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queue;
@property (nonatomic, copy) id /* block */ reportResultBlock;
@property (nonatomic) bool sessionInProgress;
@property (readonly) Class superclass;
@property (nonatomic) unsigned long long supportedRecordType;
@property (nonatomic, retain) NSArray *thresholds;

- (void).cxx_destruct;
- (void)_addAudio:(id)arg1;
- (id)_createResultDict;
- (bool)_isRequestMitigated:(id)arg1;
- (void)_logResultToVTDirectory:(id)arg1;
- (void)_reportResultToAnalytics;
- (void)_reportResultToSiriDebugApp;
- (void)_reset;
- (void)_setAsset:(id)arg1;
- (void)_startRequestWithContext:(id)arg1 withVtei:(id)arg2 completion:(id /* block */)arg3;
- (id)_timeStampString;
- (id)acousticAnalyzer;
- (void)addAudio:(id)arg1;
- (void)analyzer:(id)arg1 hasFinalResult:(id)arg2;
- (void)analyzer:(id)arg1 hasPartialResult:(id)arg2;
- (id)context;
- (id)currentAsset;
- (id)delegate;
- (void)getLatestAcousticSLResult:(id /* block */)arg1;
- (id)init;
- (bool)isShadowModeEnabled;
- (id)latestResult;
- (id)queue;
- (id /* block */)reportResultBlock;
- (bool)sessionInProgress;
- (void)setAcousticAnalyzer:(id)arg1;
- (void)setAsset:(id)arg1;
- (void)setContext:(id)arg1;
- (void)setCurrentAsset:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)setIsShadowModeEnabled:(bool)arg1;
- (void)setLatestResult:(id)arg1;
- (void)setQueue:(id)arg1;
- (void)setReportResultBlock:(id /* block */)arg1;
- (void)setSessionInProgress:(bool)arg1;
- (void)setSupportedRecordType:(unsigned long long)arg1;
- (void)setThresholds:(id)arg1;
- (void)startRequestWithContext:(id)arg1 withVtei:(id)arg2 completion:(id /* block */)arg3;
- (void)stopRequest;
- (unsigned long long)supportedRecordType;
- (id)thresholds;

@end
