/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriFindMy.framework/SiriFindMy
 */

@interface LocationMetadata : INObject

@property (nonatomic, retain) NSNumber *horizontalAccuracy;
@property (nonatomic, retain) NSNumber *timestamp;

- (id)initWithCoder:(id)arg1;
- (id)initWithIdentifier:(id)arg1 displayString:(id)arg2 pronunciationHint:(id)arg3;

@end
