/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriFindMy.framework/SiriFindMy
 */

@interface SiriFindMy.SetSharedLocationVisibilityIntentHandler : NSObject <SetSharedLocationVisibilityIntentHandling> {
    void deviceState;
    void sharedLocationVisibilitySetter;
}

- (void).cxx_destruct;
- (void)confirmSetSharedLocationVisibility:(id)arg1 completion:(id /* block */)arg2;
- (void)handleSetSharedLocationVisibility:(id)arg1 completion:(id /* block */)arg2;
- (id)init;

@end
