/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriFindMy.framework/SiriFindMy
 */

@interface SiriFindMy.FindmyDevice : _TtCs12_SwiftObject {
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  deviceLocality;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  deviceName;
    void displayByName;
    void isItem;
    void mockGlobals;
    void owner;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  productName;
}

@end
