/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/GameController.framework/GameController
 */

@interface _GCDefaultLogicalDevice : NSObject <GCAdaptiveTriggersXPCProxyServerEndpointDelegate, GCApplicationStateObserver, GCBatteryXPCProxyServerEndpointDelegate, GCLightXPCProxyServerEndpointDelegate, GCMotionXPCProxyServerEndpointDelegate, GCPlayerIndicatorXPCProxyServerEndpointDelegate, GCSettingsXPCProxyServerEndpointDelegate, _GCDeviceControllerProviding, _GCDeviceSettingsComponent, _GCLogicalDevice> {
    int  _activeApplicationPID;
    NSArray * _adaptiveTriggerStatuses;
    GCDeviceBattery * _battery;
    NSMapTable * _clientAdaptiveTriggersEndpoints;
    NSMapTable * _clientBatteryEndpoints;
    NSMapTable * _clientLightEndpoints;
    NSMapTable * _clientMotionEndpoints;
    NSMapTable * _clientPlayerIndicatorEndpoints;
    NSMapTable * _clientSettingsEndpoints;
    NSMapTable * _clients;
    _GCDeviceConfiguration * _configuration;
    <_GCDefaultLogicalDeviceDelegate> * _delegate;
    <_GCDeviceAdaptiveTriggersComponent> * _deviceAdaptiveTriggersComponent;
    <_GCDeviceBatteryComponent> * _deviceBatteryComponent;
    <_GCDeviceLightComponent> * _deviceLightComponent;
    <_GCDeviceMotionComponent> * _deviceMotionComponent;
    <_GCDevicePlayerIndexIndicatorComponent> * _devicePlayerIndicatorComponent;
    <_GCDeviceSettingsComponent> * _deviceSettingsComponent;
    NSMutableDictionary * _deviceSettingsForBundleIDs;
    <NSObject><NSCopying><NSSecureCoding> * _identifier;
    long long  _indicatedPlayerIndex;
    GCDeviceLight * _light;
    <_GCDeviceManager> * _manager;
    bool  _motionSensorsActive;
    NSMapTable * _pidToAdaptiveTriggersComponent;
    NSMutableDictionary * _pidToAnalytics;
    <_GCPhysicalDevice> * _underlyingDevice;
}

@property (nonatomic) int activeApplicationPID;
@property (readonly) NSSet *components;
@property (nonatomic, readonly) _GCDeviceConfiguration *configuration;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <_GCDefaultLogicalDeviceDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly, copy) <NSObject><NSCopying><NSSecureCoding> *identifier;
@property (readonly) <_GCDeviceManager> *manager;
@property (readonly) Class superclass;
@property (nonatomic, readonly) <_GCPhysicalDevice> *underlyingDevice;
@property (readonly) NSSet *underlyingDevices;

- (void).cxx_destruct;
- (bool)_addClient:(id)arg1;
- (void)_removeClient:(id)arg1;
- (void)activateLogical;
- (int)activeApplicationPID;
- (void)adaptiveTriggersXPCProxyServerEndpoint:(id)arg1 didReceiveAdaptiveTriggersChange:(id)arg2 forIndex:(int)arg3;
- (void)applicationBackgrounded:(int)arg1;
- (void)applicationForegrounded:(int)arg1;
- (id)components;
- (id)configuration;
- (void)deactivateLogical;
- (id)debugDescription;
- (id)defaultSettings;
- (id)delegate;
- (id)description;
- (id)identifier;
- (id)init;
- (id)initWithPhysicalDevice:(id)arg1 configuration:(id)arg2 manager:(id)arg3;
- (void)lightXPCProxyServerEndpoint:(id)arg1 didReceiveLightChange:(id)arg2;
- (id)makeControllerForClient:(id)arg1;
- (id)manager;
- (void)motionXPCProxyServerEndpoint:(id)arg1 didReceiveSensorsActiveChange:(bool)arg2;
- (void)playerIndicatorXPCProxyServerEndpoint:(id)arg1 didReceivePlayerIndexChange:(long long)arg2;
- (id)propertyForKey:(id)arg1;
- (id)redactedDescription;
- (void)setActiveApplicationPID:(int)arg1;
- (void)setDelegate:(id)arg1;
- (id)settingsForBundleIdentifier:(id)arg1;
- (void)startTrackingSessionForClient:(id)arg1;
- (void)stopObservingClientStateChanges:(id)arg1;
- (void)stopObservingClientStateChangesForAllClients;
- (void)stopTrackingSessionForClient:(id)arg1;
- (void)stopTrackingSessionsForAllClients;
- (id)underlyingDevice;
- (id)underlyingDevices;

@end
