/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/GameController.framework/GameController
 */

@interface GCDeviceAdaptiveTriggersPayload : NSObject <NSSecureCoding> {
    NSNumber * _amplitude;
    NSNumber * _endPosition;
    NSNumber * _frequency;
    NSNumber * _mode;
    NSNumber * _startPosition;
    NSNumber * _strength;
}

@property (nonatomic, readonly) NSNumber *amplitude;
@property (nonatomic, readonly) NSNumber *endPosition;
@property (nonatomic, readonly) NSNumber *frequency;
@property (nonatomic, readonly) NSNumber *mode;
@property (nonatomic, readonly) NSNumber *startPosition;
@property (nonatomic, readonly) NSNumber *strength;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)amplitude;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)endPosition;
- (id)frequency;
- (id)initFeedbackWithStartPosition:(float)arg1 resistiveStrength:(float)arg2;
- (id)initOff;
- (id)initVibrationWithStartPosition:(float)arg1 amplitude:(float)arg2 frequency:(float)arg3;
- (id)initWeaponWithStartPosition:(float)arg1 endPosition:(float)arg2 resistiveStrength:(float)arg3;
- (id)initWithCoder:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)mode;
- (id)redactedDescription;
- (id)startPosition;
- (id)strength;

@end
