/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/StoreKit.framework/StoreKit
 */

@interface SKAdNetwork : NSObject

+ (void)endImpression:(id)arg1 completionHandler:(id /* block */)arg2;
+ (void)registerAppForAdNetworkAttribution;
+ (void)startImpression:(id)arg1 completionHandler:(id /* block */)arg2;
+ (void)updateConversionValue:(long long)arg1;

@end
