/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/VideoProcessing.framework/VideoProcessing
 */

@interface VCPVideoInterpolator : VCPVideoAnalyzer {
    unsigned long long  _anchorIndex;
    struct { 
        long long value; 
        int timescale; 
        unsigned int flags; 
        long long epoch; 
    }  _anchorPTS;
    VCPMovieAssetWriter * _assetWriter;
    NSString * _filePath;
    NSArray * _frameInsertionLists;
    FRCFrameInterpolator * _frameInterpolator;
    FRCFrame * _previousFrame;
}

+ (bool)isEnabled;
+ (bool)isFRCFramworkAvailable;

- (void).cxx_destruct;
- (int)analyzeFrame:(struct __CVBuffer { }*)arg1 withTimestamp:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg2 andDuration:(struct { long long x1; int x2; unsigned int x3; long long x4; })arg3 flags:(unsigned long long*)arg4;
- (int)finishAnalysisPass:(struct { struct { long long x_1_1_1; int x_1_1_2; unsigned int x_1_1_3; long long x_1_1_4; } x1; struct { long long x_2_1_1; int x_2_1_2; unsigned int x_2_1_3; long long x_2_1_4; } x2; })arg1;
- (struct CGSize { double x1; double x2; })getFrameSize:(id)arg1;
- (id)initWithTimestamps:(id)arg1 andIdentifier:(id)arg2 andTrack:(id)arg3;
- (int)processPTS:(id)arg1 withPTS:(id*)arg2 andOriginalPTS:(id*)arg3 andInputTimestamps:(id)arg4;

@end
