/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PegasusAPI.framework/PegasusAPI
 */

@interface _TtCV10PegasusAPI26Sirikit_DateTimeRangeValueP33_5E799D70FD8561074B8682897C002CEF13_StorageClass : _TtCs12_SwiftObject {
    void _allDay;
    void _endCalendar;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _endDateTime;
    void _name;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _recurrence;
    void _startCalendar;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _startDateTime;
    void _temporalIntent;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _valueMetadata;
}

@end
