/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PegasusAPI.framework/PegasusAPI
 */

@interface _TtCV10PegasusAPI44Apple_Parsec_Siri_V2alpha_SiriPegasusRequestP33_E86396049AA3E19DB448939A42AE999613_StorageClass : _TtCs12_SwiftObject {
    void _featureFlag;
    void _isSiriInternalRequest;
    void _queries;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _queryContext;
    void _siriEnvironment;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _siriPegasusContext;
    void _userDataShareOptIn;
}

@end
