/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PegasusAPI.framework/PegasusAPI
 */

@interface _TtCV10PegasusAPI23Sportspb_CricketAthleteP33_2D9EC120613A55EFB3704F977DBD997B13_StorageClass : _TtCs12_SwiftObject {
    void _batStyle;
    void _debutODI;
    void _debutT20;
    void _debutTest;
    void _skillType;
    void _skillTypeStyle;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _statMetadata;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _stats;
}

@end
