/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PegasusAPI.framework/PegasusAPI
 */

@interface _TtCV10PegasusAPI22Sirikit_MediaItemValueP33_5E799D70FD8561074B8682897C002CEF13_StorageClass : _TtCs12_SwiftObject {
    void _artist;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _artwork;
    void _assetInfo;
    void _identifier;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _privateMediaItemValueData;
    void _title;
    void _type;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  _valueMetadata;
}

@end
