/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Catalyst.framework/Catalyst
 */

@interface CATConcreteIDSServiceConnectionDataAggregator : NSObject <CATIDSServiceConnectionDataAggregationDelegate, CATIDSServiceConnectionDataAggregator> {
    <CATIDSServiceConnectionDataAggregatorDelegate> * _delegate;
    NSMutableDictionary * mAggregationsByDataNumber;
    unsigned long long  mNextDeploymentNumber;
    NSObject<OS_dispatch_queue> * mWorkQueue;
}

@property (nonatomic) <CATIDSServiceConnectionDataAggregatorDelegate> *delegate;

- (void).cxx_destruct;
- (void)attemptToDeliverDataWithNumber:(unsigned long long)arg1;
- (void)dataAggregationCompleted:(id)arg1;
- (id)delegate;
- (id)description;
- (id)initWithWorkQueue:(id)arg1;
- (void)processNewDataWindowWithContent:(id)arg1;
- (void)receiveDataContent:(id)arg1;
- (void)setDelegate:(id)arg1;
- (void)updateExistingDataWindowWithContent:(id)arg1;

@end
