/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Catalyst.framework/Catalyst
 */

@interface CATIDSServiceConnectionInvitation : NSObject {
    NSUUID * _connectionIdentifier;
    <CATCancelable> * _networkPowerAssertion;
    NSString * _senderAddress;
    NSString * _senderAppleID;
    NSDictionary * _userInfo;
}

@property (nonatomic, readonly) NSUUID *connectionIdentifier;
@property (nonatomic, readonly) <CATCancelable> *networkPowerAssertion;
@property (nonatomic, readonly, copy) NSString *senderAddress;
@property (nonatomic, readonly, copy) NSString *senderAppleID;
@property (nonatomic, readonly, copy) NSDictionary *userInfo;

- (void).cxx_destruct;
- (id)connectionIdentifier;
- (id)initWithConnectionIdentifier:(id)arg1 senderAppleID:(id)arg2 senderAddress:(id)arg3 networkPowerAssertion:(id)arg4 userInfo:(id)arg5;
- (id)initWithSenderAppleID:(id)arg1 senderAddress:(id)arg2 networkPowerAssertion:(id)arg3 userInfo:(id)arg4;
- (id)networkPowerAssertion;
- (id)senderAddress;
- (id)senderAppleID;
- (id)userInfo;

@end
