/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Catalyst.framework/Catalyst
 */

@interface CATIDSServiceConnectionInvitationRequest : NSObject {
    NSString * _appleID;
    NSUUID * _invitationIdentifier;
    <CATCancelable> * _networkPowerAssertion;
    NSDictionary * _userInfo;
}

@property (nonatomic, readonly, copy) NSString *appleID;
@property (nonatomic, readonly) NSUUID *invitationIdentifier;
@property (nonatomic, readonly) <CATCancelable> *networkPowerAssertion;
@property (nonatomic, readonly, copy) NSDictionary *userInfo;

- (void).cxx_destruct;
- (id)appleID;
- (id)initWithInvitationIdentifier:(id)arg1 appleID:(id)arg2 networkPowerAssertion:(id)arg3 userInfo:(id)arg4;
- (id)invitationIdentifier;
- (id)networkPowerAssertion;
- (id)userInfo;

@end
