/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface _WKAuthenticatorAttestationResponse : _WKAuthenticatorResponse {
    NSData * _attestationObject;
}

@property (nonatomic, readonly) NSData *attestationObject;

- (id)attestationObject;
- (id)initWithRawId:(id)arg1 extensions:(struct RetainPtr<_WKAuthenticationExtensionsClientOutputs> { void *x1; }*)arg2 attestationObject:(id)arg3;

@end
