/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface _WKInspectorConfiguration : NSObject <NSCopying, WKObject> {
    struct ObjectStorage<API::InspectorConfiguration> { 
        struct type { 
            unsigned char __lx[32]; 
        } data; 
    }  _configuration;
}

@property (readonly) struct Object { int (**x1)(); id x2; }*_apiObject;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (struct Object { int (**x1)(); id x2; }*)_apiObject;
- (void)applyToWebViewConfiguration:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (void)dealloc;
- (id)init;
- (void)setURLSchemeHandler:(id)arg1 forURLScheme:(id)arg2;

@end
