/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKContactPicker : NSObject <CNContactPickerDelegate> {
    struct CompletionHandler<void (WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&)>="m_function"{Function<void (WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&)>="m_callableWrapper"{unique_ptr<WTF::Detail::CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&>, std::__1::default_delete<WTF::Detail::CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&>>>="__ptr_"{__compressed_pair<WTF::Detail::CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&> *, std::__1::default_delete<WTF::Detail::CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&>>>="__value_"^{CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&> {}  _completionHandler;
    struct RetainPtr<WKCNContactPickerDelegate> { 
        void *m_ptr; 
    }  _contactPickerDelegate;
    struct RetainPtr<CNContactPickerViewController> { 
        void *m_ptr; 
    }  _contactPickerViewController;
    struct WeakObjCPtr<id<WKContactPickerDelegate>> { 
        id m_weakReference; 
    }  _delegate;
    struct Vector<WebCore::ContactProperty, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { 
        unsigned char *m_buffer; 
        unsigned int m_capacity; 
        unsigned int m_size; 
    }  _properties;
    struct WeakObjCPtr<WKWebView> { 
        id m_weakReference; 
    }  _webView;
}

@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) <WKContactPickerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct ContactInfo { struct Vector<WTF::String, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct String {} *x_1_1_1; unsigned int x_1_1_2; unsigned int x_1_1_3; } x1; struct Vector<WTF::String, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct String {} *x_2_1_1; unsigned int x_2_1_2; unsigned int x_2_1_3; } x2; struct Vector<WTF::String, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct String {} *x_3_1_1; unsigned int x_3_1_2; unsigned int x_3_1_3; } x3; })_contactInfoFromCNContact:(id)arg1;
- (void)_contactPickerDidDismissWithContactInfo:(struct Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { struct ContactInfo {} *x1; unsigned int x2; unsigned int x3; }*)arg1;
- (id)_contactsFromJSContacts:(id)arg1;
- (void)contactPicker:(id)arg1 didSelectContact:(id)arg2;
- (void)contactPicker:(id)arg1 didSelectContacts:(id)arg2;
- (void)contactPickerDidCancel:(id)arg1;
- (id)delegate;
- (void)dismissWithContacts:(id)arg1;
- (id)initWithView:(id)arg1;
- (void)presentWithRequestData:(const struct ContactsRequestData { struct Vector<WebCore::ContactProperty, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc> { unsigned char *x_1_1_1; unsigned int x_1_1_2; unsigned int x_1_1_3; } x1; bool x2; struct String { struct RefPtr<WTF::StringImpl, WTF::RawPtrTraits<WTF::StringImpl>, WTF::DefaultRefDerefTraits<WTF::StringImpl>> { struct StringImpl {} *x_1_2_1; } x_3_1_1; } x3; }*)arg1 completionHandler:(struct CompletionHandler<void (WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&)>={Function<void (WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&)>={unique_ptr<WTF::Detail::CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&>, std::__1::default_delete<WTF::Detail::CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&>>>={__compressed_pair<WTF::Detail::CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&> *, std::__1::default_delete<WTF::Detail::CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&>>>=^{CallableWrapperBase<void, WTF::Optional<WTF::Vector<WebCore::ContactInfo, 0, WTF::CrashOnOverflow, 16, WTF::FastMalloc>> &&> {}*)arg2;
- (void)setDelegate:(id)arg1;

@end
