/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKDOMNode : NSObject {
    struct RefPtr<WebCore::Node, WTF::RawPtrTraits<WebCore::Node>, WTF::DefaultRefDerefTraits<WebCore::Node>> { 
        struct Node {} *m_ptr; 
    }  _impl;
}

@property (readonly) WKDOMDocument *document;
@property (readonly) WKDOMNode *firstChild;
@property (readonly) WKDOMNode *lastChild;
@property (readonly) WKDOMNode *nextSibling;
@property (readonly) WKDOMNode *parentNode;
@property (readonly) WKDOMNode *previousSibling;
@property (readonly) NSArray *textRects;

- (id).cxx_construct;
- (void).cxx_destruct;
- (struct OpaqueWKBundleNodeHandle { }*)_copyBundleNodeHandleRef;
- (id)_initWithImpl:(struct Node { int (**x1)(); struct Weak<WebCore::JSDOMObject> { struct WeakImpl {} *x_2_1_1; } x2; struct WeakPtrFactory<WebCore::Node, WTF::EmptyCounter> { struct RefPtr<WTF::WeakPtrImpl<WTF::EmptyCounter>, WTF::RawPtrTraits<WTF::WeakPtrImpl<WTF::EmptyCounter>>, WTF::DefaultRefDerefTraits<WTF::WeakPtrImpl<WTF::EmptyCounter>>> { struct WeakPtrImpl<WTF::EmptyCounter> {} *x_1_2_1; } x_3_1_1; } x3; unsigned int x4; struct OptionSet<WebCore::Node::NodeFlag> { unsigned int x_5_1_1; } x5; struct ContainerNode {} *x6; struct TreeScope {} *x7; struct Node {} *x8; struct Node {} *x9; struct CompactPointerTuple<WebCore::RenderObject *, unsigned short> { unsigned long long x_10_1_1; } x10; struct CompactUniquePtrTuple<WebCore::NodeRareData, unsigned short, WebCore::Node::NodeRareDataDeleter> { struct CompactPointerTuple<WebCore::NodeRareData *, unsigned short> { unsigned long long x_1_2_1; } x_11_1_1; } x11; }*)arg1;
- (void)appendChild:(id)arg1;
- (void)dealloc;
- (id)document;
- (id)firstChild;
- (void)insertNode:(id)arg1 before:(id)arg2;
- (id)lastChild;
- (id)nextSibling;
- (id)parentNode;
- (id)previousSibling;
- (void)removeChild:(id)arg1;
- (id)textRects;

@end
