/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKNFReaderSessionDelegate : NSObject <NFReaderSessionDelegate> {
    struct WeakPtr<WebKit::NfcConnection, WTF::EmptyCounter> { 
        struct RefPtr<WTF::WeakPtrImpl<WTF::EmptyCounter>, WTF::RawPtrTraits<WTF::WeakPtrImpl<WTF::EmptyCounter>>, WTF::DefaultRefDerefTraits<WTF::WeakPtrImpl<WTF::EmptyCounter>>> { 
            struct WeakPtrImpl<WTF::EmptyCounter> {} *m_ptr; 
        } m_impl; 
    }  _connection;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithConnection:(struct NfcConnection { unsigned int x1; struct WeakPtrFactory<WebKit::NfcConnection, WTF::EmptyCounter> { struct RefPtr<WTF::WeakPtrImpl<WTF::EmptyCounter>, WTF::RawPtrTraits<WTF::WeakPtrImpl<WTF::EmptyCounter>>, WTF::DefaultRefDerefTraits<WTF::WeakPtrImpl<WTF::EmptyCounter>>> { struct WeakPtrImpl<WTF::EmptyCounter> {} *x_1_2_1; } x_2_1_1; } x2; struct RetainPtr<NFReaderSession> { void *x_3_1_1; } x3; struct RetainPtr<WKNFReaderSessionDelegate> { void *x_4_1_1; } x4; struct WeakPtr<WebKit::NfcService, WTF::EmptyCounter> { struct RefPtr<WTF::WeakPtrImpl<WTF::EmptyCounter>, WTF::RawPtrTraits<WTF::WeakPtrImpl<WTF::EmptyCounter>>, WTF::DefaultRefDerefTraits<WTF::WeakPtrImpl<WTF::EmptyCounter>>> { struct WeakPtrImpl<WTF::EmptyCounter> {} *x_1_2_1; } x_5_1_1; } x5; struct Timer<WebKit::NfcConnection> { int (**x_6_1_1)(); struct Ref<WTF::RunLoop, WTF::RawPtrTraits<WTF::RunLoop>> { struct RunLoop {} *x_2_2_1; } x_6_1_2; struct RetainPtr<__CFRunLoopTimer *> { void *x_3_2_1; } x_6_1_3; struct Function<void ()>={unique_ptr<WTF::Detail::CallableWrapperBase<void>, std::__1::default_delete<WTF::Detail::CallableWrapperBase<void>>>={__compressed_pair<WTF::Detail::CallableWrapperBase<void> *, std::__1::default_delete<WTF::Detail::CallableWrapperBase<void>>>=^{CallableWrapperBase<void> {} x_6_1_4; } x6; }*)arg1;
- (void)readerSession:(id)arg1 didDetectTags:(id)arg2;

@end
