/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/WebKit.framework/WebKit
 */

@interface WKNSURLAuthenticationChallenge : WKObject

- (struct AuthenticationChallengeProxy { int (**x1)(); id x2; struct AuthenticationChallenge { bool x_3_1_1; struct ProtectionSpace { struct String { struct RefPtr<WTF::StringImpl, WTF::RawPtrTraits<WTF::StringImpl>, WTF::DefaultRefDerefTraits<WTF::StringImpl>> { struct StringImpl {} *x_1_4_1; } x_1_3_1; } x_2_2_1; int x_2_2_2; int x_2_2_3; struct String { struct RefPtr<WTF::StringImpl, WTF::RawPtrTraits<WTF::StringImpl>, WTF::DefaultRefDerefTraits<WTF::StringImpl>> { struct StringImpl {} *x_1_4_1; } x_4_3_1; } x_2_2_4; int x_2_2_5; bool x_2_2_6; struct RetainPtr<NSURLProtectionSpace> { void *x_7_3_1; } x_2_2_7; } x_3_1_2; struct Credential { struct String { struct RefPtr<WTF::StringImpl, WTF::RawPtrTraits<WTF::StringImpl>, WTF::DefaultRefDerefTraits<WTF::StringImpl>> { struct StringImpl {} *x_1_4_1; } x_1_3_1; } x_3_2_1; struct String { struct RefPtr<WTF::StringImpl, WTF::RawPtrTraits<WTF::StringImpl>, WTF::DefaultRefDerefTraits<WTF::StringImpl>> { struct StringImpl {} *x_1_4_1; } x_2_3_1; } x_3_2_2; int x_3_2_3; struct RetainPtr<NSURLCredential> { void *x_4_3_1; } x_3_2_4; } x_3_1_3; unsigned int x_3_1_4; } x3; }*)_web_authenticationChallengeProxy;
- (id)_web_createTarget;

@end
