/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SoftwareUpdateSettings.framework/SoftwareUpdateSettings
 */

@interface SUSSoftwareUpdateScanCell : PSTableCell {
    UIActivityIndicatorView * _checkingForUpdateSpinner;
    NSString * _currentVersion;
    int  _state;
    UILabel * _statusLabel;
    bool  _suPathsRestricted;
    UILabel * _subtitleLabel;
    bool  _updatesDeferred;
}

@property (nonatomic, retain) UIActivityIndicatorView *checkingForUpdateSpinner;
@property (nonatomic, retain) NSString *currentVersion;
@property (nonatomic) int state;
@property (nonatomic, retain) UILabel *statusLabel;
@property bool suPathsRestricted;
@property (nonatomic, retain) UILabel *subtitleLabel;
@property bool updatesDeferred;

+ (long long)cellStyle;

- (void).cxx_destruct;
- (id)checkingForUpdateSpinner;
- (id)currentVersion;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 specifier:(id)arg3;
- (void)layoutSubviews;
- (double)preferredHeightWithTable:(id)arg1;
- (void)setCheckingForUpdateSpinner:(id)arg1;
- (void)setCurrentVersion:(id)arg1;
- (void)setState:(int)arg1;
- (void)setStatusLabel:(id)arg1;
- (void)setSuPathsRestricted:(bool)arg1;
- (void)setSubtitleLabel:(id)arg1;
- (void)setUpdatesDeferred:(bool)arg1;
- (void)setupConstraints;
- (int)state;
- (id)statusLabel;
- (bool)suPathsRestricted;
- (id)subtitleLabel;
- (id)upToDateManagedText;
- (id)upToDateText;
- (id)upToDateWithAlternate;
- (bool)updatesDeferred;

@end
