/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HeartRhythmUI.framework/HeartRhythmUI
 */

@interface HRInstructionsForUseUtilities : NSObject

- (id)_atrialFibrillationHelpTopicIdForAlgorithmVersion:(id)arg1 countryCode:(id)arg2;
- (id)_electrocardiogramHelpTopicIdForAlgorithmVersion:(id)arg1 countryCode:(id)arg2;
- (id)_helpControllerForFeatureIdentifier:(id)arg1 algorithmVersion:(id)arg2 countryCode:(id)arg3 helpTopicId:(id)arg4 regionSpecificCountryCodes:(id)arg5;
- (id)_helpTopicIdForForAlgorithmVersion:(id)arg1 algorithmVersionToHelpTopicIdMap:(id)arg2;
- (id)atrialFibrillationHelpControllerForAlgorithmVersion:(id)arg1 countryCode:(id)arg2;
- (id)electrocardiogramHelpControllerForAlgorithmVersion:(id)arg1 countryCode:(id)arg2;

@end
