/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
 */

@interface WBSCloudKitOperationRetryManager : NSObject {
    NSDate * _dateRetryWasFirstRequested;
    unsigned long long  _numberOfRetries;
    double  _timeout;
}

@property (nonatomic) double timeout;

- (void).cxx_destruct;
- (id)init;
- (long long)scheduleRetryIfNeededForError:(id)arg1 usingBlock:(id /* block */)arg2;
- (void)setTimeout:(double)arg1;
- (double)timeout;

@end
