/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SafariShared.framework/SafariShared
 */

@interface WBSReaderAvailabilityCheckResult : NSObject <NSCopying, NSSecureCoding> {
    bool  _doesPageUseSearchEngineOptimizationMetadata;
    bool  _isSameDocumentNavigation;
    bool  _readerAvailable;
    NSArray * _textSamples;
}

@property (nonatomic) bool doesPageUseSearchEngineOptimizationMetadata;
@property (nonatomic) bool isSameDocumentNavigation;
@property (getter=isReaderAvailable, nonatomic) bool readerAvailable;
@property (nonatomic, copy) NSArray *textSamples;

+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (bool)doesPageUseSearchEngineOptimizationMetadata;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (bool)isReaderAvailable;
- (bool)isSameDocumentNavigation;
- (void)setDoesPageUseSearchEngineOptimizationMetadata:(bool)arg1;
- (void)setIsSameDocumentNavigation:(bool)arg1;
- (void)setReaderAvailable:(bool)arg1;
- (void)setTextSamples:(id)arg1;
- (id)textSamples;

@end
