/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Announce.framework/Announce
 */

@interface ANTonePlayerService : NSObject {
    NSXPCConnection * _connection;
}

@property (nonatomic, readonly) NSXPCConnection *connection;

- (void).cxx_destruct;
- (id)connection;
- (void)dealloc;
- (id)init;
- (void)invalidate;
- (void)playTone:(unsigned long long)arg1 endpointUUID:(id)arg2 completionHandler:(id /* block */)arg3;

@end
