/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/Announce.framework/Announce
 */

@interface ANTonePlayer : NSObject {
    AVAudioSession * _audioSession;
    NSUUID * _endpointUUID;
    id /* block */  _handler;
    NSObject<OS_os_log> * _log;
    AVPlayer * _player;
    AVPlayerItem * _playerItem;
}

@property (nonatomic, retain) AVAudioSession *audioSession;
@property (nonatomic, readonly) NSUUID *endpointUUID;
@property (nonatomic, copy) id /* block */ handler;
@property (nonatomic, readonly) NSObject<OS_os_log> *log;
@property (nonatomic, retain) AVPlayer *player;
@property (nonatomic, retain) AVPlayerItem *playerItem;

- (void).cxx_destruct;
- (bool)_activateAudioSessionForPlayer:(id)arg1 error:(id*)arg2;
- (void)_callHandler:(id)arg1;
- (void)_deactivateAudioSession;
- (void)_deregisterForNotificationsWithAudioSession:(id)arg1;
- (void)_handleFailure;
- (void)_handlePlayerItemFailedToPlayToEnd:(id)arg1;
- (void)_handlePlayerItemPlayedToEnd:(id)arg1;
- (void)_playFileURL:(id)arg1;
- (void)_playSystemSoundWithFileURL:(id)arg1;
- (void)_registerForNotificationsWithAudioSession:(id)arg1;
- (id)audioSession;
- (void)audioSessionInterruptionHandler:(id)arg1;
- (void)dealloc;
- (id)endpointUUID;
- (id /* block */)handler;
- (id)init;
- (id)initWithEndpointUUID:(id)arg1;
- (id)log;
- (void)playFileURL:(id)arg1 completionHandler:(id /* block */)arg2;
- (id)player;
- (id)playerItem;
- (void)playerRateChangedHandler:(id)arg1;
- (void)setAudioSession:(id)arg1;
- (void)setHandler:(id /* block */)arg1;
- (void)setPlayer:(id)arg1;
- (void)setPlayerItem:(id)arg1;
- (void)stop;

@end
