/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamKit.framework/ShazamKit
 */

@interface SHAudioMatchingRemoteStore : SHRemoteStore {
    <SHMatcher> * _proxyMatcher;
    bool  _sendNotifications;
}

@property (nonatomic, retain) <SHMatcher> *proxyMatcher;
@property (nonatomic) bool sendNotifications;

- (void).cxx_destruct;
- (id)_createMatcher;
- (id)initWithPartnerName:(id)arg1;
- (id)proxyMatcher;
- (bool)sendNotifications;
- (void)setProxyMatcher:(id)arg1;
- (void)setSendNotifications:(bool)arg1;
- (void)startMatching;
- (void)startMatchingUntilDeadline:(id)arg1;
- (void)startMatchingUntilResultFound;
- (void)startOneMatchAttempt;
- (void)stop;

@end
