/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamKit.framework/ShazamKit
 */

@interface SHRemoteStore : SHStore

+ (bool)_validateInstallationID:(id)arg1;
+ (bool)_validatePartnerName:(id)arg1;
+ (id)new;

- (id)_createMatcher;
- (id)init;
- (id)initWithPartnerName:(id)arg1;
- (id)initWithPartnerName:(id)arg1 installationID:(id)arg2;

@end
