/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamKit.framework/ShazamKit
 */

@interface SHRecognitionAssets : NSObject

+ (id)bundleURLFromInputURL:(id)arg1;
+ (bool)filePathIsBundle:(id)arg1;
+ (id)mediaItemsForSignatureName:(id)arg1 bundle:(id)arg2;
+ (id)plistHeader;
+ (id)referenceMatchesFromPath:(id)arg1 error:(id*)arg2;
+ (id)signaturePathsFromBundle:(id)arg1;
+ (bool)writePotentialMatches:(id)arg1 toURL:(id)arg2 error:(id*)arg3;

@end
