/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamKit.framework/ShazamKit
 */

@interface SHShazamXPCServiceProxyConnection : NSObject <SHXPCServiceProxy> {
    NSXPCConnection * _connection;
    id /* block */  _connectionErrorHandler;
    id  _delegate;
    id /* block */  _interruptionHandler;
    id /* block */  _invalidationHandler;
    <SHXPCServiceProxy> * _proxy;
}

@property (nonatomic, retain) NSXPCConnection *connection;
@property (nonatomic, copy) id /* block */ connectionErrorHandler;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) id delegate;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) id /* block */ interruptionHandler;
@property (nonatomic, copy) id /* block */ invalidationHandler;
@property (nonatomic, retain) <SHXPCServiceProxy> *proxy;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (void)attachDefaultConnectionHandlers;
- (id)connection;
- (id /* block */)connectionErrorHandler;
- (void)dealloc;
- (id)delegate;
- (id /* block */)interruptionHandler;
- (id /* block */)invalidationHandler;
- (void)mediaItemsForAppleMusicIDs:(id)arg1 withReply:(id /* block */)arg2;
- (void)mediaItemsForShazamIDs:(id)arg1 withReply:(id /* block */)arg2;
- (id)proxy;
- (void)setConnection:(id)arg1;
- (void)setConnectionErrorHandler:(id /* block */)arg1;
- (void)setDelegate:(id)arg1;
- (void)setInterruptionHandler:(id /* block */)arg1;
- (void)setInvalidationHandler:(id /* block */)arg1;
- (void)setProxy:(id)arg1;
- (void)shazamIDsFromAppleMusicIDs:(id)arg1 withReply:(id /* block */)arg2;
- (void)startRecognitionForRequest:(id)arg1;
- (oneway void)stop;
- (void)synchronizeChanges:(id)arg1;

@end
