/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ShazamKit.framework/ShazamKit
 */

@interface SHShazamKey : NSObject <NSCopying> {
    NSString * _validatedKey;
}

@property (nonatomic, readonly, copy) NSString *validatedKey;

+ (id)keyWithValue:(id)arg1;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)initWithKey:(id)arg1;
- (bool)isShazamKeyValid:(id)arg1;
- (id)validatedKey;

@end
