/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HealthDaemon.framework/HealthDaemon
 */

@interface HDWatchRemoteFeatureAvailabilityProvider : NSObject <HDRemoteFeatureAvailabilityProviding> {
    <HDRemoteFeatureAvailabilityProvidingDelegate> * _delegate;
    NSString * _featureIdentifier;
    NSObject<OS_os_log> * _loggingCategory;
    NRPairedDeviceRegistry * _pairedDeviceRegistry;
    NSUserDefaults * _remoteFeatureAvailabilityUserDefaults;
}

@property (nonatomic) <HDRemoteFeatureAvailabilityProvidingDelegate> *delegate;

- (void).cxx_destruct;
- (id)_activePairedDevice;
- (id)_disabledStateConditionIdentifier;
- (void)dealloc;
- (id)delegate;
- (id)initWithFeatureIdentifier:(id)arg1 loggingCategory:(id)arg2;
- (id)isRemoteDisabledForCountryCode:(id)arg1 device:(id)arg2 error:(id*)arg3;
- (id)isRemoteDisabledOnActivePairedDeviceForCountryCode:(id)arg1 error:(id*)arg2;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void*)arg4;
- (void)setDelegate:(id)arg1;
- (void)setPairedDeviceRegistry:(id)arg1;
- (void)setRemoteFeatureAvailabilityUserDefaults:(id)arg1;

@end
