/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DAEASOAuthFramework.framework/DAEASOAuthFramework
 */

@interface DAEASOAuthMigrationActivity : NSObject {
    NSBackgroundActivityScheduler * _scheduler;
}

@property (nonatomic, retain) NSBackgroundActivityScheduler *scheduler;

+ (bool)profileMigrationDisabled;
+ (bool)profileMigrationEnabled;

- (void).cxx_destruct;
- (bool)_isExchangeBasicAccount:(id)arg1;
- (void)_retrieveMigrationStatusFromConfigurationURI:(id)arg1 withCompletion:(id /* block */)arg2;
- (bool)_serverMigrationEnabled;
- (bool)_shouldMigrateExchangeAccountToOAuth:(id)arg1;
- (id /* block */)_triggerAccountMigration;
- (void)invalidateActivity;
- (void)scheduleActivity;
- (id)scheduler;
- (void)setScheduler:(id)arg1;

@end
