/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/WiFiKit.framework/WiFiKit
 */

@interface WFUserJoinEvent : NSObject <WFUIEvent> {
    NSDictionary * _eventDictionary;
    PBCodable * _metric;
    unsigned int  _metricIdentifier;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly) NSDictionary *eventDictionary;
@property (nonatomic, readonly) NSString *eventName;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) PBCodable *metric;
@property (nonatomic) unsigned int metricIdentifier;
@property (readonly) Class superclass;

+ (id)joinEventWithSecurity:(long long)arg1 error:(long long)arg2 sectionCounts:(id)arg3 sectionName:(id)arg4;
+ (id)joinEventWithType:(long long)arg1 security:(long long)arg2 error:(long long)arg3;

- (void).cxx_destruct;
- (id)_countMetricsFromSectionCounts:(id)arg1;
- (id)_eventTypeStringForType:(long long)arg1;
- (unsigned int)_metricIdForType:(long long)arg1;
- (id)_sectionCountsToJSONString:(id)arg1;
- (id)eventDictionary;
- (id)eventName;
- (id)initWithType:(long long)arg1 security:(long long)arg2 error:(long long)arg3 sectionCounts:(id)arg4 sectionName:(id)arg5;
- (id)metric;
- (unsigned int)metricIdentifier;
- (void)setMetric:(id)arg1;
- (void)setMetricIdentifier:(unsigned int)arg1;

@end
