/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWFigCaptureDeviceClient : NSObject {
    bool  _canStealFromClientsWithSamePriority;
    NSString * _clientDescription;
    int  _clientID;
    int  _clientPriority;
    id /* block */  _deviceAvailabilityChangedHandler;
    bool  _deviceSharingWithOtherClientsAllowed;
    int  _pid;
}

@property (nonatomic, readonly) bool canStealFromClientsWithSamePriority;
@property (nonatomic, readonly) NSString *clientDescription;
@property (nonatomic, readonly) int clientID;
@property (nonatomic, readonly) int clientPriority;
@property (nonatomic, copy) id /* block */ deviceAvailabilityChangedHandler;
@property (nonatomic, readonly) bool deviceSharingWithOtherClientsAllowed;
@property (nonatomic, readonly) int pid;

- (bool)canShareDeviceWithClientPID:(int)arg1 deviceAvailabilityChangedHandler:(id /* block */)arg2;
- (bool)canStealFromClientsWithSamePriority;
- (id)clientDescription;
- (int)clientID;
- (int)clientPriority;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id /* block */)deviceAvailabilityChangedHandler;
- (bool)deviceSharingWithOtherClientsAllowed;
- (id)initWithPID:(int)arg1 clientDescription:(id)arg2 clientPriority:(int)arg3 canStealFromClientsWithSamePriority:(bool)arg4 deviceSharingWithOtherClientsAllowed:(bool)arg5 deviceAvailabilityChangedHandler:(id /* block */)arg6;
- (bool)isEqual:(id)arg1;
- (int)pid;
- (void)setDeviceAvailabilityChangedHandler:(id /* block */)arg1;

@end
