/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWMovieFileOutputAnalyticsPayload : NSObject <BWCoreAnalyticsPayload> {
    NSDictionary * _APSModeByPortType;
    int  _activeDeviceMask;
    bool  _afDriverShortOccurred;
    NSString * _clientApplicationID;
    int  _devicePosition;
    int  _deviceType;
    double  _duration;
    double  _durationFront;
    double  _durationFrontSuperWide;
    double  _durationRearSuperWide;
    double  _durationRearTele;
    double  _durationRearWide;
    int  _height;
    float  _nominalFramerate;
    struct BWCoreAnalyticsMovieRecordingSphereAFStatistics { float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; float x17; float x18; float x19; float x20; float x21; float x22; float x23; float x24; float x25; unsigned int x26; unsigned int x27; unsigned int x28; unsigned int x29; unsigned int x30; unsigned int x31; unsigned int x32; unsigned int x33; unsigned int x34; unsigned int x35; unsigned int x36; unsigned int x37; unsigned int x38; unsigned int x39; unsigned int x40; } * _sphereAFStatistics;
    NSDictionary * _sphereModeByPortType;
    NSDictionary * _variableFrameRateStatistics;
    bool  _videoMirrored;
    int  _videoOrientation;
    int  _width;
}

@property (nonatomic, retain) NSDictionary *APSModeByPortType;
@property (nonatomic) int activeDeviceMask;
@property (nonatomic) bool afDriverShortOccurred;
@property (nonatomic, copy) NSString *clientApplicationID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic) int devicePosition;
@property (nonatomic) int deviceType;
@property (nonatomic) double duration;
@property (nonatomic) double durationFront;
@property (nonatomic) double durationFrontSuperWide;
@property (nonatomic) double durationRearSuperWide;
@property (nonatomic) double durationRearTele;
@property (nonatomic) double durationRearWide;
@property (readonly) unsigned long long hash;
@property (nonatomic) int height;
@property (nonatomic) float nominalFramerate;
@property (nonatomic) struct BWCoreAnalyticsMovieRecordingSphereAFStatistics { float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; float x17; float x18; float x19; float x20; float x21; float x22; float x23; float x24; float x25; unsigned int x26; unsigned int x27; unsigned int x28; unsigned int x29; unsigned int x30; unsigned int x31; unsigned int x32; unsigned int x33; unsigned int x34; unsigned int x35; unsigned int x36; unsigned int x37; unsigned int x38; unsigned int x39; unsigned int x40; }*sphereAFStatistics;
@property (nonatomic, retain) NSDictionary *sphereModeByPortType;
@property (readonly) Class superclass;
@property (nonatomic, retain) NSDictionary *variableFrameRateStatistics;
@property (nonatomic) bool videoMirrored;
@property (nonatomic) int videoOrientation;
@property (nonatomic) int width;

- (id)APSModeByPortType;
- (int)activeDeviceMask;
- (bool)afDriverShortOccurred;
- (id)clientApplicationID;
- (void)dealloc;
- (int)devicePosition;
- (int)deviceType;
- (double)duration;
- (double)durationFront;
- (double)durationFrontSuperWide;
- (double)durationRearSuperWide;
- (double)durationRearTele;
- (double)durationRearWide;
- (id)eventDictionary;
- (id)eventName;
- (int)height;
- (id)init;
- (float)nominalFramerate;
- (void)reset;
- (void)setAPSModeByPortType:(id)arg1;
- (void)setActiveDeviceMask:(int)arg1;
- (void)setAfDriverShortOccurred:(bool)arg1;
- (void)setClientApplicationID:(id)arg1;
- (void)setDevicePosition:(int)arg1;
- (void)setDeviceType:(int)arg1;
- (void)setDuration:(double)arg1;
- (void)setDurationFront:(double)arg1;
- (void)setDurationFrontSuperWide:(double)arg1;
- (void)setDurationRearSuperWide:(double)arg1;
- (void)setDurationRearTele:(double)arg1;
- (void)setDurationRearWide:(double)arg1;
- (void)setHeight:(int)arg1;
- (void)setNominalFramerate:(float)arg1;
- (void)setSphereAFStatistics:(struct BWCoreAnalyticsMovieRecordingSphereAFStatistics { float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; float x17; float x18; float x19; float x20; float x21; float x22; float x23; float x24; float x25; unsigned int x26; unsigned int x27; unsigned int x28; unsigned int x29; unsigned int x30; unsigned int x31; unsigned int x32; unsigned int x33; unsigned int x34; unsigned int x35; unsigned int x36; unsigned int x37; unsigned int x38; unsigned int x39; unsigned int x40; }*)arg1;
- (void)setSphereModeByPortType:(id)arg1;
- (void)setVariableFrameRateStatistics:(id)arg1;
- (void)setVideoMirrored:(bool)arg1;
- (void)setVideoOrientation:(int)arg1;
- (void)setWidth:(int)arg1;
- (struct BWCoreAnalyticsMovieRecordingSphereAFStatistics { float x1; float x2; float x3; float x4; float x5; float x6; float x7; float x8; float x9; float x10; float x11; float x12; float x13; float x14; float x15; float x16; float x17; float x18; float x19; float x20; float x21; float x22; float x23; float x24; float x25; unsigned int x26; unsigned int x27; unsigned int x28; unsigned int x29; unsigned int x30; unsigned int x31; unsigned int x32; unsigned int x33; unsigned int x34; unsigned int x35; unsigned int x36; unsigned int x37; unsigned int x38; unsigned int x39; unsigned int x40; }*)sphereAFStatistics;
- (id)sphereModeByPortType;
- (id)variableFrameRateStatistics;
- (bool)videoMirrored;
- (int)videoOrientation;
- (int)width;

@end
