/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface BWStereoDisparityProcessorControllerConfiguration : BWStillImageProcessorConfiguration {
    struct { 
        int width; 
        int height; 
    }  _disparityOutputDimensions;
    int  _fsdNetStereoImagesAlignment;
    struct { 
        int width; 
        int height; 
    }  _inputDimensions;
    bool  _shouldComputeDisparityWhenCalibrationFails;
}

@property (nonatomic) struct { int x1; int x2; } disparityOutputDimensions;
@property (nonatomic) int fsdNetStereoImagesAlignment;
@property (nonatomic) struct { int x1; int x2; } inputDimensions;
@property (nonatomic) bool shouldComputeDisparityWhenCalibrationFails;

- (struct { int x1; int x2; })disparityOutputDimensions;
- (int)fsdNetStereoImagesAlignment;
- (struct { int x1; int x2; })inputDimensions;
- (void)setDisparityOutputDimensions:(struct { int x1; int x2; })arg1;
- (void)setFsdNetStereoImagesAlignment:(int)arg1;
- (void)setInputDimensions:(struct { int x1; int x2; })arg1;
- (void)setShouldComputeDisparityWhenCalibrationFails:(bool)arg1;
- (bool)shouldComputeDisparityWhenCalibrationFails;

@end
