/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CMCapture.framework/CMCapture
 */

@interface FigCaptureStillImageUnifiedBracketingSinkPipeline : FigCaptureSinkPipeline <FigCaptureStillImageSinkPipeline> {
    unsigned int  _inferencePriority;
    unsigned int  _pipelineStagePriority;
    BWPortraitHDRStagingNode * _portraitHDRStagingNode;
    BWStillImageCoordinatorNode * _stillImageCoordinatorNode;
    BWDepthConverterNode * _stillImageDepthConverterNode;
    BWStillImageBravoDisparityNode * _stillImageDisparityNode;
    BWStillImageSampleBufferSinkNode * _stillImageSinkNode;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) NSArray *nodes;
@property (nonatomic, readonly) BWPortraitHDRStagingNode *portraitHDRStagingNode;
@property (nonatomic, readonly) NSString *sinkID;
@property (nonatomic, readonly) BWStillImageCoordinatorNode *stillImageCoordinatorNode;
@property (nonatomic, readonly) BWStillImageSampleBufferSinkNode *stillImageSinkNode;
@property (readonly) Class superclass;

+ (void)initialize;

- (int)_addLandmarksInferenceToNode:(id)arg1;
- (int)_addMattingInferenceToNode:(id)arg1 withVersion:(unsigned int)arg2 refinedDepthEnabled:(bool)arg3 downsamplingFactor:(int)arg4 enabledSemantics:(unsigned int)arg5 metalCommandQueue:(id)arg6 mattingsensorConfigurationsByPortType:(id)arg7 clientIsCameraOrDerivative:(bool)arg8;
- (int)_buildRedEyeReductionSubPipelineWithName:(id)arg1 pipelineStage:(id)arg2 graph:(id)arg3 sensorConfigurationsByPortType:(id)arg4 inferenceScheduler:(id)arg5 captureDevice:(id)arg6 subPipelineInputOut:(id*)arg7 subPipelineOutputOut:(id*)arg8;
- (int)_buildScaleAndEncodeSubPipelineWithName:(id)arg1 pipelineStage:(id)arg2 graph:(id)arg3 nodeConfiguration:(id)arg4 stillImageSinkPipelineWithConfiguration:(id)arg5 sensorConfigurationsByPortType:(id)arg6 supportsScaling:(bool)arg7 provideMeteorHeadroom:(bool)arg8 personSegmentationEnabled:(bool)arg9 providePostEncodeInferences:(bool)arg10 semanticDevelopmentVersion:(int)arg11 constituentPhotoDeliveryEnabled:(bool)arg12 demosaicedRawEnabled:(bool)arg13 inferenceMainImageDownscalingFactor:(float)arg14 inferenceAttachedMedia:(id)arg15 inferenceScheduler:(id)arg16 subPipelineInputOut:(id*)arg17 subPipelineOutputOut:(id*)arg18 captureDevice:(id)arg19;
- (int)_buildStillImageSinkPipelineWithConfiguration:(id)arg1 captureDevice:(id)arg2 sourceOutputsByPortType:(id)arg3 pointCloudCaptureDevice:(id)arg4 pointCloudSourceOutput:(id)arg5 captureStatusDelegate:(id)arg6 inferenceScheduler:(id)arg7 graph:(id)arg8;
- (void)dealloc;
- (void)enablePrepareTimeAllocationsForDeferredPrepare;
- (id)initWithConfiguration:(id)arg1 captureDevice:(id)arg2 sourceOutputsByPortType:(id)arg3 pointCloudCaptureDevice:(id)arg4 pointCloudSourceOutput:(id)arg5 captureStatusDelegate:(id)arg6 inferenceScheduler:(id)arg7 graph:(id)arg8 name:(id)arg9;
- (id)portraitHDRStagingNode;
- (id)stillImageCoordinatorNode;
- (id)stillImageSinkNode;

@end
