/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVAppInfoDonateTask : CKVDonateTask {
    CKVLaunchServicesBridge * _launchServicesBridge;
}

- (void).cxx_destruct;
- (void)donateAllAppInfoWithLanguageCode:(id)arg1 reason:(unsigned short)arg2 completion:(id /* block */)arg3;
- (id)initWithDonatorProvider:(id)arg1;
- (id)initWithDonatorProvider:(id)arg1 launchServicesBridge:(id)arg2;

@end
