/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVContactMapper : NSObject <CKVItemMapper>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (bool)_addLabeledFieldsOfType:(long long)arg1 labeledValues:(id)arg2 labelOnly:(bool)arg3 builder:(id)arg4 error:(id*)arg5;
+ (id)_flattenLabeledValue:(id)arg1;
+ (id)_itemBufferFromContact:(id)arg1 error:(id*)arg2;
+ (id)itemBufferFromExternalVocabularyItem:(id)arg1 error:(id*)arg2;
+ (long long)targetItemType;

@end
