/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVCustomTermMapper : NSObject <CKVItemMapper>

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

+ (id)_itemBufferFromCustomTerm:(id)arg1 error:(id*)arg2;
+ (id)customTermFromItem:(id)arg1 error:(id*)arg2;
+ (unsigned short)customTypeFromFieldType:(long long)arg1;
+ (long long)fieldTypeFromCustomType:(unsigned short)arg1;
+ (id)itemBufferFromExternalVocabularyItem:(id)arg1 error:(id*)arg2;
+ (long long)targetItemType;

@end
