/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVContactsDonateTask : CKVDonateTask {
    CKVContactStoreBridge * _contactStoreBridge;
}

- (void).cxx_destruct;
- (void)donateAllContacts:(unsigned short)arg1 completion:(id /* block */)arg2;
- (id)initWithDonatorProvider:(id)arg1;
- (id)initWithDonatorProvider:(id)arg1 contactStoreBridge:(id)arg2;

@end
