/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVDonatorFactory : NSObject <CKVDonatorProvider> {
    NSObject<CKVDonateAuthorization> * _authorization;
    NSObject<OS_dispatch_queue> * _donatorQueue;
    NSObject<CKVDonateServiceProvider> * _serviceProvider;
}

+ (id)sharedDonatorFactory;

- (void).cxx_destruct;
- (id)init;
- (id)initWithQueue:(id)arg1 serviceProvider:(id)arg2 authorization:(id)arg3;
- (id)makeDonatorForOriginApp:(id)arg1;

@end
