/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVDatabaseSelectBuilder : CKVDatabaseCommandBuilder {
    CKVSQLCommandOrder * _order;
}

- (void).cxx_destruct;
- (id)build;
- (id)initWithTableName:(id)arg1;
- (void)setCommandCriterion:(id)arg1;
- (void)setCommandOrder:(id)arg1;

@end
