/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVFilesystemBase : NSObject <NSCopying> {
    NSURL * _rootDirectory;
}

@property (nonatomic, readonly) NSURL *rootDirectory;

+ (id)baseURLWithTargetDirectoryPath:(id)arg1 relativeToDirectoryPath:(id)arg2;
+ (id)sharedInstance;

- (void).cxx_destruct;
- (bool)_isChildOfRootDirectory:(id)arg1;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (id)getOrCreateDirectoryWithRelativePath:(id)arg1;
- (unsigned long long)hash;
- (id)init;
- (id)initWithTargetDirectoryPath:(id)arg1 relativeToDirectoryPath:(id)arg2;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToFileManager:(id)arg1;
- (bool)removeItemAtURL:(id)arg1;
- (id)rootDirectory;

@end
