/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVIndexUpdater : NSObject {
    CKVIndexManager * _idxMgr;
    CKVSettings * _settings;
}

- (void).cxx_destruct;
- (bool)_deleteAllRecordsOfClass:(Class)arg1 originApp:(id)arg2 itemType:(long long)arg3 database:(id)arg4;
- (bool)_insertFTSRecordsFromItem:(id)arg1 originApp:(id)arg2 recordId:(id)arg3 database:(id)arg4;
- (id)_insertItemRecordWithItemBuffer:(id)arg1 originApp:(id)arg2 database:(id)arg3;
- (bool)_isValidDatabaseRecordClass:(Class)arg1;
- (bool)_updateDatabaseWithFullSetOfItems:(id)arg1 ofType:(long long)arg2 originApp:(id)arg3;
- (bool)applyFullSetVocabularyDonation:(id)arg1;
- (id)initWithIndexManager:(id)arg1 settings:(id)arg2;

@end
