/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVIntentVocabularyDonateTask : CKVDonateTask {
    CKVIntentVocabularyAuthorization * _vocabularyAuthorization;
    CKVIntentVocabularyStoreManager * _vocabularyStoreManager;
}

- (void).cxx_destruct;
- (id)_readAllVocabularyForApp:(id)arg1 withIntentSlots:(id)arg2;
- (void)_submitDonation:(id)arg1 completion:(id /* block */)arg2;
- (void)donateLatestVocabularyForAllApps:(unsigned short)arg1 completion:(id /* block */)arg2;
- (id)initWithDonatorProvider:(id)arg1;
- (id)initWithVocabularyStoreManager:(id)arg1 vocabularyAuthorization:(id)arg2 donatorProvider:(id)arg3;

@end
