/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVItemBuilder : NSObject {
    NSMutableArray * _fields;
    CKVMutableItem * _mutableItem;
}

- (void).cxx_destruct;
- (id)addFieldWithType:(long long)arg1 label:(id)arg2 value:(id)arg3 error:(id*)arg4;
- (id)addFieldWithType:(long long)arg1 value:(id)arg2 error:(id*)arg3;
- (id)buildBufferWithError:(id*)arg1;
- (id)init;
- (id)initWithItemType:(long long)arg1 itemId:(id)arg2 error:(id*)arg3;

@end
