/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVLaunchServicesBridge : NSObject

- (bool)_checkAppValidity:(id)arg1 options:(unsigned long long)arg2;
- (id)fetchAllInstalledApps:(unsigned long long)arg1 languageCode:(id)arg2;

@end
