/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVocabularyDonation : NSObject <NSCopying, NSSecureCoding> {
    long long  _itemType;
    CKVOriginApp * _originApp;
    NSArray * _serializedItems;
}

@property (nonatomic, readonly) long long itemType;
@property (nonatomic, readonly) CKVOriginApp *originApp;
@property (nonatomic, readonly) NSArray *serializedItems;

+ (id)builderWithOriginApp:(id)arg1 itemClass:(Class)arg2 error:(id*)arg3;
+ (bool)supportsSecureCoding;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithOriginApp:(id)arg1 serializedItems:(id)arg2 itemType:(long long)arg3;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToDonation:(id)arg1;
- (long long)itemType;
- (id)originApp;
- (id)serializedItems;

@end
