/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVPriorInfo : NSObject <NSCopying> {
    unsigned int  _ordinality;
    float  _prior;
}

@property (nonatomic, readonly) unsigned int ordinality;
@property (nonatomic, readonly) float prior;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (unsigned long long)hash;
- (id)init;
- (id)initWithOrdinality:(unsigned int)arg1 prior:(float)arg2;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToPriorInfo:(id)arg1;
- (unsigned int)ordinality;
- (float)prior;

@end
