/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVSettings : NSObject {
    bool  _isSandboxInstance;
    NSString * _siriLanguageCode;
}

@property (nonatomic, readonly) bool isSandboxInstance;
@property (retain) NSDictionary *simulatedPriors;
@property (readonly) NSString *siriLanguageCode;

+ (id)_languageCodeToLocaleIdentifierMap;
+ (id)_resolveSiriLanguageCode;
+ (id)defaultSandboxSettings;
+ (id)defaultSettings;
+ (id)sandboxSettingsWithLocale:(id)arg1;
+ (id)supportedLanguageCodeFromLocale:(id)arg1;
+ (id)supportedLocaleFromLanguageCode:(id)arg1;

- (void).cxx_destruct;
- (bool)_shouldDonateAll;
- (bool)_shouldOverrideDonationSettings;
- (id)initWithSiriLanguageCode:(id)arg1 isSandboxInstance:(bool)arg2;
- (bool)isSandboxInstance;
- (bool)isVocabularyDonationEnabled;
- (void)setSimulatedPriors:(id)arg1;
- (bool)shouldDonateAppInfo;
- (bool)shouldDonateContacts;
- (bool)shouldDonateCustomVocabulary;
- (id)simulatedPriors;
- (id)siriLanguageCode;
- (bool)updateSiriLanguage;

@end
