/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVSpanMatchFTS : NSObject <CKVSpanMatchSearchIndex> {
    CKVDatabaseSearcher * _databaseSearcher;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)_characterRangeFromTokenRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 inTokenChain:(id)arg2;
- (id)_findLongestSpansMatchingResult:(id)arg1 withTokenIndexes:(id)arg2 ofTokenChain:(id)arg3;
- (void)_mapSearchResults:(id)arg1 toTokenIndex:(unsigned long long)arg2 withMap:(id)arg3;
- (id)_searchFTSForToken:(id)arg1 error:(id*)arg2;
- (bool)_shouldMergeSpanWithRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 inTokenChain:(id)arg2 withSearchResult:(id)arg3;
- (id)init;
- (id)initWithDatabaseSearcher:(id)arg1;
- (id)searchIndexForTokenChain:(id)arg1;

@end
