/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVServiceConnection : NSObject {
    NSObject<OS_dispatch_queue> * _serviceQueue;
}

@property (nonatomic, readonly) NSObject<OS_dispatch_queue> *serviceQueue;

- (void).cxx_destruct;
- (id)init;
- (id)initWithServiceQueue:(id)arg1;
- (id)serviceQueue;

@end
