/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVSpanMatchMergedField : NSObject <CKVSpanMatch> {
    unsigned int  _editDistance;
    float  _matchScore;
    unsigned int  _maxTokenCount;
    NSArray * _mergedFields;
    NSString * _mergedValue;
    struct _NSRange { 
        unsigned long long location; 
        unsigned long long length; 
    }  _spanRange;
    unsigned int  _tokenMatchedCount;
}

@property (nonatomic, readonly) unsigned int editDistance;
@property (nonatomic, readonly) float matchScore;
@property (nonatomic, readonly) unsigned int maxTokenCount;
@property (nonatomic, readonly) NSArray *mergedFields;
@property (nonatomic, readonly) NSString *mergedValue;
@property (nonatomic, readonly) struct _NSRange { unsigned long long x1; unsigned long long x2; } spanRange;
@property (nonatomic, readonly) unsigned int tokenMatchedCount;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (unsigned int)editDistance;
- (unsigned long long)hash;
- (id)init;
- (id)initWithSpanRange:(struct _NSRange { unsigned long long x1; unsigned long long x2; })arg1 mergedValue:(id)arg2 mergedFields:(id)arg3 matchScore:(float)arg4 maxTokenCount:(unsigned int)arg5 tokenMatchedCount:(unsigned int)arg6 editDistance:(unsigned int)arg7;
- (bool)isEqual:(id)arg1;
- (bool)isEqualToSpanMatchingMergedFields:(id)arg1;
- (float)matchScore;
- (unsigned int)maxTokenCount;
- (id)mergedFields;
- (id)mergedValue;
- (struct _NSRange { unsigned long long x1; unsigned long long x2; })spanRange;
- (unsigned int)tokenMatchedCount;

@end
