/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVTemporaryFilesystemBase : CKVFilesystemBase

+ (id)_absoluteBasePathWithName:(id)arg1;
+ (id)_relativeBasePathWithName:(id)arg1;
+ (bool)removeTemporaryBaseWithName:(id)arg1;
+ (bool)temporaryBaseExistsWithName:(id)arg1;

- (id)initWithName:(id)arg1;
- (void)removeAllContents;

@end
