/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreKnowledge.framework/CoreKnowledge
 */

@interface CKVUserProfileTools : NSObject

+ (Class)_converterClassForItemClass:(Class)arg1;
+ (id)localeFromRawSpeechProfile:(id)arg1 error:(id*)arg2;
+ (id)mapItemIdsToPriorsFromMetadata:(id)arg1;
+ (id)parseRawSpeechProfileMetadata:(id)arg1 error:(id*)arg2;
+ (id)vocabularyItemsOfClass:(Class)arg1 fromRawSpeechProfile:(id)arg2 metadata:(id)arg3 error:(id*)arg4;

@end
