/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaRemote.framework/MediaRemote
 */

@interface MRNowPlayingPlayerResponse : NSObject <NSCopying> {
    NSDate * _deviceLastPlayingDate;
    MRPlaybackQueue * _playbackQueue;
    unsigned int  _playbackState;
    NSDate * _playerLastPlayingDate;
    MRPlayerPath * _playerPath;
    NSArray * _supportedCommands;
}

@property (nonatomic, readonly) bool deviceHasPlayedRecently;
@property (nonatomic, copy) NSDate *deviceLastPlayingDate;
@property (nonatomic, readonly) bool hasPlayedRecently;
@property (nonatomic, readonly) NSDate *lastPlayingDate;
@property (nonatomic, copy) MRPlaybackQueue *playbackQueue;
@property (nonatomic) unsigned int playbackState;
@property (nonatomic, readonly) bool playerHasPlayedRecently;
@property (nonatomic, copy) NSDate *playerLastPlayingDate;
@property (nonatomic, copy) MRPlayerPath *playerPath;
@property (nonatomic, copy) NSArray *supportedCommands;

- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)description;
- (bool)deviceHasPlayedRecently;
- (id)deviceLastPlayingDate;
- (id)dictionaryRepresentation;
- (bool)hasPlayedRecently;
- (id)lastPlayingDate;
- (id)playbackQueue;
- (unsigned int)playbackState;
- (bool)playerHasPlayedRecently;
- (id)playerLastPlayingDate;
- (id)playerPath;
- (void)setDeviceLastPlayingDate:(id)arg1;
- (void)setPlaybackQueue:(id)arg1;
- (void)setPlaybackState:(unsigned int)arg1;
- (void)setPlayerLastPlayingDate:(id)arg1;
- (void)setPlayerPath:(id)arg1;
- (void)setSupportedCommands:(id)arg1;
- (id)supportedCommands;

@end
