/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MLCompute.framework/MLCompute
 */

@interface _MLCANEPlistBuilder : NSObject

+ (bool)addInputs:(id)arg1 ofUnit:(id)arg2 ofOperation:(id)arg3 toProcedure:(id)arg4;
+ (bool)addOutputs:(id)arg1 ofOperation:(id)arg2 toProcedure:(id)arg3 toNetwork:(id)arg4;
+ (bool)addUnitsAndInputsAndOutpusOfLayer:(id)arg1 toNetwork:(id)arg2 toProcedure:(id)arg3 operationName:(id)arg4 liveInputs:(id)arg5 liveOutputs:(id)arg6;
+ (id)buildBiasParamsWithBiases:(id)arg1;
+ (id)createConstantTensorUnitWithTensor:(id)arg1;
+ (id)createReshapeUnitWithSourceTensor:(id)arg1 layer:(id)arg2 resultShape:(id)arg3;
+ (id)createUnitWithLayer:(id)arg1 unitParams:(id)arg2;
+ (void)unitBottomNamesWithSourceTensor:(id)arg1 liveInputs:(id)arg2 unitBottomNames:(id)arg3 sourceTensorsToLiveUp:(id)arg4;

@end
