/* Generated by RuntimeBrowser
   Image: /System/Library/Frameworks/MLCompute.framework/MLCompute
 */

@interface MLCDataHelper : NSObject

+ (bool)convertFp16toFp32:(unsigned long long)arg1 fp16Values:(/* Warning: Unrecognized filer type: ' ' using 'void*' */ void**)arg2 fp32Values:(float*)arg3;
+ (bool)convertFp32toFp16:(unsigned long long)arg1 fp32Values:(float*)arg2 fp16Values:(/* Warning: Unrecognized filer type: ' ' using 'void*' */ void**)arg3;
+ (bool)convertOIHWtoIOHW:(id)arg1 sourceOIHW:(const void*)arg2 resultIOHW:(void*)arg3 inputFeatureChannelCount:(unsigned long long)arg4 outputFeatureChannelCount:(unsigned long long)arg5;
+ (id)createDataWithFloatValue:(float)arg1 count:(unsigned long long)arg2;
+ (void)fillData:(id)arg1 withFloatValue:(float)arg2;

@end
