/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXAppModeEntityModelWeights : NSObject {
    double  _appCategoryScore;
    double  _appCategoryScore_v2;
    double  _bias;
    double  _classConditionalProbability;
    double  _entityOccurredGloballyOverLastNDays;
    double  _globalOccurrences;
    double  _globalPopularity;
    double  _modePopularity;
    unsigned long long  _numOfDays;
    double  _posteriorProbability;
}

@property (nonatomic) double appCategoryScore;
@property (nonatomic) double appCategoryScore_v2;
@property (nonatomic) double bias;
@property (nonatomic) double classConditionalProbability;
@property (nonatomic) double entityOccurredGloballyOverLastNDays;
@property (nonatomic) double globalOccurrences;
@property (nonatomic) double globalPopularity;
@property (nonatomic) double modePopularity;
@property (nonatomic) unsigned long long numOfDays;
@property (nonatomic) double posteriorProbability;

- (double)appCategoryScore;
- (double)appCategoryScore_v2;
- (double)bias;
- (double)classConditionalProbability;
- (double)entityOccurredGloballyOverLastNDays;
- (double)globalOccurrences;
- (double)globalPopularity;
- (id)init;
- (double)modePopularity;
- (unsigned long long)numOfDays;
- (double)posteriorProbability;
- (void)setAppCategoryScore:(double)arg1;
- (void)setAppCategoryScore_v2:(double)arg1;
- (void)setBias:(double)arg1;
- (void)setClassConditionalProbability:(double)arg1;
- (void)setEntityOccurredGloballyOverLastNDays:(double)arg1;
- (void)setGlobalOccurrences:(double)arg1;
- (void)setGlobalPopularity:(double)arg1;
- (void)setModePopularity:(double)arg1;
- (void)setNumOfDays:(unsigned long long)arg1;
- (void)setPosteriorProbability:(double)arg1;

@end
