/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXDefaultWidgetSuggester : NSObject {
    _ATXAppLaunchHistogramManager * _histogramManager;
}

- (void).cxx_destruct;
- (bool)_hasAppLaunchesForAppBudleId:(id)arg1 threshold:(unsigned long long)arg2;
- (bool)_hasIntentDonationsForActionKey:(id)arg1 threshold:(unsigned long long)arg2;
- (bool)_hasUpcomingMediaForAppBundleId:(id)arg1 isInternalApplication:(bool)arg2 threshold:(unsigned long long)arg3;
- (bool)_shouldSuggestAppBundleId:(id)arg1 actionKey:(id)arg2 isInternalApplication:(bool)arg3;
- (id)initWithHistogramManager:(id)arg1;
- (bool)shouldSuggestTV;

@end
