/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXInferredModeSessionBiomeInspector : NSObject

+ (void)retrieveInferredModeSessionsFromPublisherFromName:(id)arg1 startTime:(double)arg2 reply:(id /* block */)arg3;

@end
