/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppPredictionInternal.framework/AppPredictionInternal
 */

@interface ATXModeActivityMetricsLogger : NSObject {
    NSArray * _combinedEvents;
    NSDate * _endDate;
    NSDate * _startDate;
    NSNumber * _startingDNDState;
}

- (void).cxx_destruct;
- (id)_coalesceAndFilterDisplayOnIntervals:(id)arg1;
- (id)_coalesceAppLaunches:(id)arg1;
- (bool)_eventIsBeforeStartDate:(id)arg1;
- (id)_findStartingDNDStateFromTransitions:(id)arg1;
- (void)_populateCombinedEvents:(id)arg1;
- (bool)_shouldCoalesceLaunch:(id)arg1 nextLaunch:(id)arg2;
- (bool)_shouldCoalesceOnInterval:(id)arg1 nextInterval:(id)arg2;
- (id)init;
- (id)initWithAppLaunches:(id)arg1 dndTransitions:(id)arg2 modeTransitions:(id)arg3 notificationEvents:(id)arg4 displayOnIntervals:(id)arg5 startDate:(id)arg6 endDate:(id)arg7;
- (id)initWithStartDate:(id)arg1 endDate:(id)arg2;
- (void)logMetrics;
- (void)logMetricsWithXPCActivity:(id)arg1;

@end
