/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AppleDepth.framework/AppleDepth
 */

@interface ADJasperPointCloudFilterParamaters : ADJasperPointCloudFilterParameters

@end
