/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FMIPCore.framework/FMIPCore
 */

@interface FMIPCore.FMIPBeaconRefreshingController : _TtCs12_SwiftObject {
    void beacons;
    void callbackInterval;
    void defaultCallbackInterval;
    void delegate;
    void initialCallbackInterval;
    void isRefreshing;
    void isThrottled;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  lastActiveTimestamp;
    union { in /* Warning: Unrecognized filer type: 'u' using 'void*' */ void*x1; long x2; long x3; }  lastRefreshTime;
    void ownerSession;
    void refreshQueue;
    void refreshTimer;
    void unknownBeacons;
    void utAlertState;
}

- (void)handleBeaconsChanged;
- (void)handleUnknownBeaconsChanged;
- (void)refreshTimerFired;

@end
