/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SPOwner.framework/SPOwner
 */

@interface SPSecureLocationsManager : NSObject <SPSecureLocationsXPCProtocol> {
    <SPSecureLocationsXPCProtocol> * _proxy;
    NSObject<OS_dispatch_queue> * _queue;
    FMXPCServiceDescription * _serviceDescription;
    FMXPCSession * _session;
}

@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) <SPSecureLocationsXPCProtocol> *proxy;
@property (nonatomic, retain) NSObject<OS_dispatch_queue> *queue;
@property (nonatomic, retain) FMXPCServiceDescription *serviceDescription;
@property (nonatomic, retain) FMXPCSession *session;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)exportedInterface;
- (oneway void)fetchConfigFromServerWithCompletion:(id /* block */)arg1;
- (id)init;
- (void)interruptionHandler:(id)arg1;
- (void)invalidationHandler:(id)arg1;
- (oneway void)isLocationPublishingDeviceWithCompletion:(id /* block */)arg1;
- (oneway void)latestLocationFromCacheForId:(id)arg1 completion:(id /* block */)arg2;
- (oneway void)performKeyRollWithCompletion:(id /* block */)arg1;
- (id)proxy;
- (oneway void)publishLocation:(id)arg1 completion:(id /* block */)arg2;
- (id)queue;
- (oneway void)receivedLocationCommand:(id)arg1 completion:(id /* block */)arg2;
- (oneway void)receivedLocationPayload:(id)arg1 completion:(id /* block */)arg2;
- (id)remoteInterface;
- (id)serviceDescription;
- (id)session;
- (void)setProxy:(id)arg1;
- (void)setQueue:(id)arg1;
- (void)setServiceDescription:(id)arg1;
- (void)setSession:(id)arg1;
- (oneway void)shareCurrentKeyWithId:(id)arg1 completion:(id /* block */)arg2;
- (oneway void)shouldStartLocationMonitorWithCompletion:(id /* block */)arg1;
- (oneway void)subscribeAndFetchLocationForIds:(id)arg1 clientApp:(id)arg2 completion:(id /* block */)arg3;
- (oneway void)unsubscribeForId:(id)arg1 clientApp:(id)arg2 completion:(id /* block */)arg3;

@end
