/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NotesUI.framework/NotesUI
 */

@interface ICAbstractAttachmentViewController : UIViewController {
    bool  _forManualRendering;
    NSRegularExpression * _highlightPatternRegex;
    bool  _isInResponderChain;
}

@property (readonly) bool forManualRendering;
@property (nonatomic, retain) NSRegularExpression *highlightPatternRegex;
@property (nonatomic, readonly) bool isInResponderChain;

- (void).cxx_destruct;
- (void)contentSizeCategoryDidChange;
- (bool)forManualRendering;
- (id)highlightPatternRegex;
- (bool)isInResponderChain;
- (void)prepareForPrinting;
- (void)setHighlightPatternRegex:(id)arg1;
- (void)zoomFactorOrInsetsDidChange;

@end
