/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NotesUI.framework/NotesUI
 */

@interface ICInlineAttachmentView : UIView <ICAttachmentViewInitializing> {
    NSRegularExpression * _highlightPatternRegex;
    UILabel * _label;
    NSDictionary * _surroundingAttributes;
    ICInlineTextAttachment * _textAttachment;
}

@property (nonatomic, readonly) double baselineOffsetFromBottom;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (readonly) unsigned long long hash;
@property (nonatomic, retain) NSRegularExpression *highlightPatternRegex;
@property (nonatomic, readonly) UIImage *imageForPrinting;
@property (nonatomic, retain) UILabel *label;
@property (readonly) Class superclass;
@property (nonatomic, copy) NSDictionary *surroundingAttributes;
@property (nonatomic) ICInlineTextAttachment *textAttachment;

+ (id)filteredStyleAttributes:(id)arg1;

- (void).cxx_destruct;
- (id)accessibilityAttributedLabel;
- (void)attachmentDataChanged:(id)arg1;
- (id)attributesWithSurroundingAttributes:(id)arg1;
- (double)baselineOffsetFromBottom;
- (id)highlightPatternRegex;
- (id)imageForPrinting;
- (id)initWithTextAttachment:(id)arg1 forManualRendering:(bool)arg2;
- (bool)isAccessibilityElement;
- (id)label;
- (void)setHighlightPatternRegex:(id)arg1;
- (void)setLabel:(id)arg1;
- (void)setSurroundingAttributes:(id)arg1;
- (void)setTextAttachment:(id)arg1;
- (id)surroundingAttributes;
- (id)textAttachment;
- (void)updateLabel;
- (void)updateStyleWithAttributes:(id)arg1;

@end
