/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NotesUI.framework/NotesUI
 */

@interface ICInlineTextAttachment : ICAbstractTextAttachment

@property (nonatomic, retain) ICInlineAttachment *attachment;

+ (Class)textAttachmentClassForAttachment:(id)arg1;
+ (id)textAttachmentWithAttachment:(id)arg1;

- (id)altText;
- (id)attachmentIdentifier;
- (id)attachmentInContext:(id)arg1;
- (id)attachmentUTI;
- (Class)attachmentViewClass;
- (id)initWithAttachment:(id)arg1;
- (id)inlineAttachmentInContext:(id)arg1;
- (bool)isUnsupported;
- (id)newlyCreatedView;
- (id)printableTextContentForAppearanceType:(unsigned long long)arg1 styleAttributes:(id)arg2;

@end
