/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAI.framework/HomeAI
 */

@interface HMIAverageImage : HMFObject {
    CIImage * _currentAverage;
    float  _decay;
    long long  _numImages;
}

@property (retain) CIImage *currentAverage;
@property float decay;
@property long long numImages;

- (void).cxx_destruct;
- (void)addToAverage:(id)arg1;
- (id)currentAverage;
- (float)decay;
- (id)init;
- (id)initWithDecay:(float)arg1;
- (long long)numImages;
- (id)outputImage;
- (void)setCurrentAverage:(id)arg1;
- (void)setDecay:(float)arg1;
- (void)setNumImages:(long long)arg1;

@end
