/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAI.framework/HomeAI
 */

@interface HMIPackageCandidateDetectorConfiguration : HMFObject {
    HMIBoundingBoxExtractorConfiguration * _boundingBoxConfig;
    float  _deltaEThreshold;
    float  _densityMapScale;
    float  _densityThresholdPreAverage;
    float  _temporalAverageDecay;
    float  _temporalDensityThreshold;
}

@property (readonly) HMIBoundingBoxExtractorConfiguration *boundingBoxConfig;
@property (readonly) float deltaEThreshold;
@property (readonly) float densityMapScale;
@property (readonly) float densityThresholdPreAverage;
@property (readonly) float temporalAverageDecay;
@property (readonly) float temporalDensityThreshold;

+ (id)defaultConfig;

- (void).cxx_destruct;
- (id)boundingBoxConfig;
- (float)deltaEThreshold;
- (float)densityMapScale;
- (float)densityThresholdPreAverage;
- (id)initWithDeltaEThreshold:(float)arg1 densityThresholdPreAverage:(float)arg2 temporalDensityThreshold:(float)arg3 densityMapScale:(float)arg4 temporalAverageDecay:(float)arg5 boundingBoxConfig:(id)arg6;
- (float)temporalAverageDecay;
- (float)temporalDensityThreshold;

@end
