/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAI.framework/HomeAI
 */

@interface HMIVideoPackageAnalyzerDelegateAdapter : HMFObject <HMIVideoPackageAnalyzerDelegate> {
    id /* block */  _packageAnalyzerDidDetectPackages;
}

@property (copy) id /* block */ packageAnalyzerDidDetectPackages;

- (void).cxx_destruct;
- (void)packageAnalyzer:(id)arg1 didDetectPackages:(id)arg2 error:(id)arg3;
- (id /* block */)packageAnalyzerDidDetectPackages;
- (void)setPackageAnalyzerDidDetectPackages:(id /* block */)arg1;

@end
