/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/HomeAI.framework/HomeAI
 */

@interface HMIVideoPackageAnalyzer : HMIVideoProcessingNode <HMFLogging, HMIVideoFrameSamplerDelegate> {
    HMIAverageImage * _averageImage;
    HMIPackageCandidateDetectorConfiguration * _candidateConfig;
    HMIPackageCandidateDetector * _candidateDetector;
    int  _currentFrameIndex;
    <HMIVideoPackageAnalyzerDelegate> * _delegate;
    int  _detectionFps;
    double  _prerollLengthSeconds;
    HMIVideoFrameIntervalSampler * _sampler;
    CIFilter * _scaleFilter;
}

@property (readonly) HMIAverageImage *averageImage;
@property (retain) HMIPackageCandidateDetectorConfiguration *candidateConfig;
@property (retain) HMIPackageCandidateDetector *candidateDetector;
@property int currentFrameIndex;
@property (readonly, copy) NSString *debugDescription;
@property <HMIVideoPackageAnalyzerDelegate> *delegate;
@property (readonly, copy) NSString *description;
@property (readonly) int detectionFps;
@property (readonly) unsigned long long hash;
@property (readonly) double prerollLengthSeconds;
@property (readonly) HMIVideoFrameIntervalSampler *sampler;
@property (retain) CIFilter *scaleFilter;
@property (readonly) Class superclass;

+ (id)logCategory;

- (void).cxx_destruct;
- (id)averageImage;
- (id)candidateConfig;
- (id)candidateDetector;
- (int)currentFrameIndex;
- (id)delegate;
- (int)detectionFps;
- (void)frameSampler:(id)arg1 didSampleFrame:(struct opaqueCMSampleBuffer { }*)arg2;
- (void)handleSampleBuffer:(struct opaqueCMSampleBuffer { }*)arg1;
- (id)init;
- (id)initWithDetectionFps:(float)arg1 prerollLengthSeconds:(double)arg2;
- (double)prerollLengthSeconds;
- (id)sampler;
- (id)scaleFilter;
- (void)setCandidateConfig:(id)arg1;
- (void)setCandidateDetector:(id)arg1;
- (void)setCurrentFrameIndex:(int)arg1;
- (void)setDelegate:(id)arg1;
- (void)setScaleFilter:(id)arg1;

@end
