/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AdPlatformsCommonUI.framework/AdPlatformsCommonUI
 */

@interface APGreenTeaLogger : NSObject {
    struct ct_green_tea_logger_s { } * _logger;
}

@property (nonatomic, readonly) struct ct_green_tea_logger_s { }*logger;

- (void)dealloc;
- (id)init;
- (struct ct_green_tea_logger_s { }*)logger;
- (void)willAccessLocationForLanding;
- (void)willTransmitLocationForLanding;

@end
