/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SoftwareUpdateSettingsUI.framework/SoftwareUpdateSettingsUI
 */

@interface NonPromotedUpdateSpacerView : PSFooterHyperlinkView

- (id)initWithSpecifier:(id)arg1;
- (double)marginForContentSize:(id)arg1;
- (double)preferredHeightForWidth:(double)arg1 inTableView:(id)arg2;

@end
