/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SoftwareUpdateSettingsUI.framework/SoftwareUpdateSettingsUI
 */

@interface NonPromotedUpdateHeaderView : PSFooterHyperlinkView

- (id)initWithSpecifier:(id)arg1;

@end
