/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SoftwareUpdateSettingsUI.framework/SoftwareUpdateSettingsUI
 */

@interface SUSUISoftwareUpdateController : PSListController <DevicePINControllerDelegate, SUSUISoftwareUpdateManagerDelegate, SUSUISoftwareUpdatePaneDelegate, UITableViewDelegate> {
    SUSUISoftwareUpdatePane * _activeDownloadPane;
    SUSUISoftwareUpdatePane * _alternateUpdatePane;
    NSString * _devicePasscode;
    id /* block */  _devicePasscodeCompletion;
    id /* block */  _legacyDevicePasscodeCompletion;
    SUSUISoftwareUpdateManager * _manager;
    SUSUISoftwareUpdatePane * _primaryUpdatePane;
    NSError * _suError;
    UsageStorageController * _usageStorageController;
}

@property (nonatomic, retain) NSError *SUError;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, copy) id /* block */ devicePasscodeCompletion;
@property (readonly) unsigned long long hash;
@property (nonatomic, copy) id /* block */ legacyDevicePasscodeCompletion;
@property (readonly) Class superclass;

- (void).cxx_destruct;
- (id)SUError;
- (void)_downloadAndInstall:(id)arg1 installationType:(unsigned long long)arg2;
- (void)_downloadAndInstall:(id)arg1 installationType:(unsigned long long)arg2 setPaneToPrimary:(bool)arg3;
- (void)alternateSoftwareUpdatePaneDidAppear:(id)arg1;
- (void)alternateSoftwareUpdatePaneDidDisappear:(id)arg1;
- (bool)autoInstallArmed;
- (void)autoInstallCancel:(id)arg1;
- (id)automaticDownloadStatus;
- (id)automaticUpdateStatus;
- (void)dealloc;
- (void)detailedReleaseNotesDonePressed:(id)arg1;
- (void)devicePINControllerDidDismissPINPane:(id)arg1;
- (void)devicePINControllerDidDismissPINPane:(id)arg1 forUpdate:(id)arg2;
- (id /* block */)devicePasscodeCompletion;
- (void)didAcceptEnteredPIN:(id)arg1;
- (void)downloadAndInstall;
- (void)downloadAndInstallTonight;
- (void)downloadOnly;
- (id)init;
- (void)install:(id)arg1;
- (id /* block */)legacyDevicePasscodeCompletion;
- (void)loadView;
- (void)manager:(id)arg1 autoUpdateScheduledStatusChanged:(bool)arg2;
- (void)manager:(id)arg1 didTransitionToState:(int)arg2 fromState:(int)arg3;
- (void)manager:(id)arg1 download:(id)arg2 failedWithError:(id)arg3;
- (void)manager:(id)arg1 downloadDidStart:(id)arg2;
- (void)manager:(id)arg1 downloadProgressChanged:(id)arg2 displayStyle:(int)arg3;
- (void)manager:(id)arg1 promptForDevicePasscodeWithCompletion:(id /* block */)arg2;
- (void)manager:(id)arg1 promptForDevicePasscodeWithDescriptorCompletion:(id /* block */)arg2;
- (void)manager:(id)arg1 scanFoundUpdates:(id)arg2 error:(id)arg3;
- (void)movePaneToPrimary:(id)arg1;
- (void)nonPromotedSoftwareUpdatePaneDidDisappear:(id)arg1;
- (void)presentViewController:(id)arg1 animated:(bool)arg2 completion:(id /* block */)arg3;
- (void)refreshState;
- (id)selectSpecifier:(id)arg1;
- (void)setAutomaticDownloadFromUI:(id)arg1 forSpecifier:(id)arg2;
- (void)setAutomaticUpdatesFromUI:(id)arg1 forSpecifier:(id)arg2;
- (void)setDevicePasscodeCompletion:(id /* block */)arg1;
- (void)setLegacyDevicePasscodeCompletion:(id /* block */)arg1;
- (void)setSUError:(id)arg1;
- (void)softwareUpdatePane:(id)arg1 devicePINControllerDidDismissPINPane:(id)arg2;
- (void)softwareUpdatePane:(id)arg1 learnMoreButtonTapped:(id)arg2;
- (void)softwareUpdatePane:(id)arg1 presentConfirmationSpecifier:(id)arg2;
- (void)softwareUpdatePane:(id)arg1 readyToDownload:(unsigned long long)arg2;
- (void)softwareUpdatePane:(id)arg1 readyToDownloadAndReplacePreferredPaneWithPane:(unsigned long long)arg2;
- (void)softwareUpdatePane:(id)arg1 showPINSheet:(id)arg2;
- (void)softwareUpdatePane:(id)arg1 specifiersChanged:(id)arg2;
- (void)softwareUpdatePaneReadyToInstall:(id)arg1;
- (void)softwareUpdatePaneReadyToUpgradeToUserInitiatedDownloadAndReplacePreferredPaneWithPane:(id)arg1;
- (void)softwareUpdatePaneUpgradeToUserInitiatedDownload:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (Class)tableViewClass;
- (void)updateState;
- (void)updateTableFromState:(int)arg1;
- (void)upgradeDownloadToUserInitiated:(id)arg1 setPaneToPrimary:(bool)arg2;
- (void)viewDidAppear:(bool)arg1;
- (void)viewDidDisappear:(bool)arg1;
- (void)viewDidLoad;
- (void)viewWillAppear:(bool)arg1;
- (void)viewWillDisappear:(bool)arg1;
- (void)willEnterForeground;

@end
