/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/RespiratoryHealthDaemon.framework/RespiratoryHealthDaemon
 */

@interface HDRPFeatureAvailabilityManager : NSObject <HDFeatureAvailabilityExtension> {
    long long  __unitTest_currentOnboardingVersionOverride;
    <HDPairedDeviceCapabilityProviding> * _capabilityProvider;
    long long  _currentOnboardingVersion;
    NSString * _featureIdentifier;
    NSObject<OS_os_log> * _loggingCategory;
    HDFeatureAvailabilityManager * _manager;
    NSUUID * _pairedDeviceCapability;
    HDProfile * _profile;
    <HDRemoteFeatureAvailabilityProviding> * _remoteAvailabilityProvider;
    bool  _skipHardwareCheck;
    NSDictionary * _supportedCountries;
}

@property (nonatomic) long long _unitTest_currentOnboardingVersionOverride;
@property (nonatomic, readonly, copy) NSString *featureIdentifier;

- (void).cxx_destruct;
- (long long)_currentOnboardingVersion;
- (id)_determineSupportedStateWithOnboardingCompletions:(id)arg1 device:(id)arg2 error:(id*)arg3;
- (long long)_isRegionCodeFound:(id)arg1 availabilityWatch:(id)arg2 availabilityPhone:(id)arg3;
- (bool)_isRegionSupported:(id)arg1 device:(id)arg2 error:(id*)arg3;
- (bool)_isRegionSupported:(id)arg1 error:(id*)arg2;
- (id)_isRemoteDisabledForCountryCode:(id)arg1 device:(id)arg2 error:(id*)arg3;
- (id)_onboardingCompletionsForHighestVersionWithError:(id*)arg1;
- (id)_onboardingCompletionsForLowestVersionWithError:(id*)arg1;
- (id)_phoneAvailabilityForDevice:(id)arg1;
- (void)_resetOnboarding;
- (long long)_unitTest_currentOnboardingVersionOverride;
- (id)_watchAvailabilityForDevice:(id)arg1;
- (id)canCompleteOnboardingForCountryCode:(id)arg1 device:(id)arg2 error:(id*)arg3;
- (id)canCompleteOnboardingForCountryCode:(id)arg1 error:(id*)arg2;
- (id)description;
- (id)deviceForPairingID:(id)arg1;
- (id)earliestDateLowestOnboardingVersionCompletedWithError:(id*)arg1;
- (id)featureIdentifier;
- (id)highestOnboardingVersionCompletedWithError:(id*)arg1;
- (id)initWithProfile:(id)arg1;
- (id)initWithProfile:(id)arg1 featureIdentifier:(id)arg2 currentOnboardingVersion:(long long)arg3 supportedCountries:(id)arg4 pairedDeviceCapability:(id)arg5 loggingCategory:(id)arg6 skipHardwareCheck:(bool)arg7 pairedDeviceCapabilityProvider:(id)arg8 remoteAvailabilityProvider:(id)arg9;
- (id)initWithProfile:(id)arg1 supportedCountries:(id)arg2 pairedDeviceCapabilityProvider:(id)arg3 remoteAvailabilityProvider:(id)arg4;
- (void)isCurrentOnboardingVersionCompletedWithCompletion:(id /* block */)arg1;
- (id)isCurrentOnboardingVersionCompletedWithError:(id*)arg1;
- (id)isFeatureCapabilitySupportedOnActivePairedDeviceWithError:(id*)arg1;
- (id)isFeatureCapabilitySupportedOnDevice:(id)arg1 error:(id*)arg2;
- (id)onboardedCountryCodeSupportedStateForDevice:(id)arg1 error:(id*)arg2;
- (id)onboardedCountryCodeSupportedStateWithError:(id*)arg1;
- (void)registerObserver:(id)arg1 queue:(id)arg2;
- (void)resetOnboardingWithCompletion:(id /* block */)arg1;
- (void)setCurrentOnboardingVersionCompletedForCountryCode:(id)arg1 completion:(id /* block */)arg2;
- (void)set_unitTest_currentOnboardingVersionOverride:(long long)arg1;
- (void)unregisterObserver:(id)arg1;

@end
