/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/DataDetectorsUI.framework/DataDetectorsUI
 */

@interface DDShareAction : DDAction

- (id)icon;
- (int)interactionType;
- (id)localizedName;
- (void)performFromView:(id)arg1;
- (id)viewController;

@end
