/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface FLOWSchemaFLOWHomeAutomationContext : SISchemaInstrumentationMessage {
    NSArray * _homeKitServiceResponses;
}

@property (nonatomic, copy) NSArray *homeKitServiceResponses;
@property (nonatomic, readonly) NSData *jsonData;

- (void).cxx_destruct;
- (void)addHomeKitServiceResponse:(id)arg1;
- (void)clearHomeKitServiceResponse;
- (id)dictionaryRepresentation;
- (unsigned long long)hash;
- (id)homeKitServiceResponseAtIndex:(unsigned long long)arg1;
- (unsigned long long)homeKitServiceResponseCount;
- (id)homeKitServiceResponses;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setHomeKitServiceResponses:(id)arg1;
- (void)writeTo:(id)arg1;

@end
