/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface FLOWSchemaFLOWStep : SISchemaInstrumentationMessage {
    FLOWSchemaFLOWAppContext * _appContext;
    NSArray * _domainContexts;
    FLOWSchemaFLOWState * _flowState;
    struct { 
        unsigned int sequenceNum : 1; 
        unsigned int timestampMs : 1; 
    }  _has;
    bool  _hasAppContext;
    bool  _hasFlowState;
    unsigned int  _sequenceNum;
    long long  _timestampMs;
}

@property (nonatomic, retain) FLOWSchemaFLOWAppContext *appContext;
@property (nonatomic, copy) NSArray *domainContexts;
@property (nonatomic, retain) FLOWSchemaFLOWState *flowState;
@property (nonatomic) bool hasAppContext;
@property (nonatomic) bool hasFlowState;
@property (nonatomic) bool hasSequenceNum;
@property (nonatomic) bool hasTimestampMs;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic) unsigned int sequenceNum;
@property (nonatomic) long long timestampMs;

- (void).cxx_destruct;
- (void)addDomainContext:(id)arg1;
- (id)appContext;
- (void)clearDomainContext;
- (id)dictionaryRepresentation;
- (id)domainContextAtIndex:(unsigned long long)arg1;
- (unsigned long long)domainContextCount;
- (id)domainContexts;
- (id)flowState;
- (bool)hasAppContext;
- (bool)hasFlowState;
- (bool)hasSequenceNum;
- (bool)hasTimestampMs;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (unsigned int)sequenceNum;
- (void)setAppContext:(id)arg1;
- (void)setDomainContexts:(id)arg1;
- (void)setFlowState:(id)arg1;
- (void)setHasAppContext:(bool)arg1;
- (void)setHasFlowState:(bool)arg1;
- (void)setHasSequenceNum:(bool)arg1;
- (void)setHasTimestampMs:(bool)arg1;
- (void)setSequenceNum:(unsigned int)arg1;
- (void)setTimestampMs:(long long)arg1;
- (long long)timestampMs;
- (void)writeTo:(id)arg1;

@end
