/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriInstrumentation.framework/SiriInstrumentation
 */

@interface SUTSchemaTestContext : SISchemaInstrumentationMessage {
    struct { 
        unsigned int testType : 1; 
    }  _has;
    bool  _hasTestName;
    NSString * _testName;
    int  _testType;
}

@property (nonatomic) bool hasTestName;
@property (nonatomic) bool hasTestType;
@property (nonatomic, readonly) NSData *jsonData;
@property (nonatomic, copy) NSString *testName;
@property (nonatomic) int testType;

- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (bool)hasTestName;
- (bool)hasTestType;
- (unsigned long long)hash;
- (id)initWithDictionary:(id)arg1;
- (id)initWithJSON:(id)arg1;
- (bool)isEqual:(id)arg1;
- (id)jsonData;
- (bool)readFrom:(id)arg1;
- (void)setHasTestName:(bool)arg1;
- (void)setHasTestType:(bool)arg1;
- (void)setTestName:(id)arg1;
- (void)setTestType:(int)arg1;
- (id)testName;
- (int)testType;
- (void)writeTo:(id)arg1;

@end
