/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHCandidateRefinementStep : CHPostprocessingStep {
    CHRecognizer * _recognizer;
    bool  _shouldKeepAlternativeLengths;
    bool  _shouldKeepDuplicateTokenIDs;
    bool  _shouldKeepOriginalSpelling;
    bool  _shouldKeepOutOfLexiconAlternatives;
    bool  _shouldKeepOutOfPatternCandidates;
    bool  _shouldKeepSubstrings;
}

@property (nonatomic) CHRecognizer *recognizer;
@property (nonatomic) bool shouldKeepAlternativeLengths;
@property (nonatomic) bool shouldKeepDuplicateTokenIDs;
@property (nonatomic) bool shouldKeepOriginalSpelling;
@property (nonatomic) bool shouldKeepOutOfLexiconAlternatives;
@property (nonatomic) bool shouldKeepOutOfPatternCandidates;
@property (nonatomic) bool shouldKeepSubstrings;

- (id)initWithRecognizer:(id)arg1 shouldKeepOutOfPatternCandidates:(bool)arg2 shouldKeepDuplicateTokenIDs:(bool)arg3 shouldKeepOutOfLexiconAlternatives:(bool)arg4 shouldKeepAlternativeLengths:(bool)arg5 shouldKeepSubstrings:(bool)arg6 shouldKeepOriginalSpelling:(bool)arg7;
- (id)process:(id)arg1;
- (id)recognizer;
- (void)setRecognizer:(id)arg1;
- (void)setShouldKeepAlternativeLengths:(bool)arg1;
- (void)setShouldKeepDuplicateTokenIDs:(bool)arg1;
- (void)setShouldKeepOriginalSpelling:(bool)arg1;
- (void)setShouldKeepOutOfLexiconAlternatives:(bool)arg1;
- (void)setShouldKeepOutOfPatternCandidates:(bool)arg1;
- (void)setShouldKeepSubstrings:(bool)arg1;
- (bool)shouldKeepAlternativeLengths;
- (bool)shouldKeepDuplicateTokenIDs;
- (bool)shouldKeepOriginalSpelling;
- (bool)shouldKeepOutOfLexiconAlternatives;
- (bool)shouldKeepOutOfPatternCandidates;
- (bool)shouldKeepSubstrings;

@end
