/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHPostprocessingStep : NSObject

+ (id)applyTransform:(id /* block */)arg1 toAllTokens:(id)arg2;
+ (void)expandPathsWithCorrectedToken:(id)arg1 fromToken:(id)arg2 correctedTokenPath:(id)arg3 originalTokenPath:(id)arg4;

- (id)process:(id)arg1;

@end
