/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreHandwriting.framework/CoreHandwriting
 */

@interface CHRecognizerInferenceCache : NSObject {
    NSMutableDictionary * _cachedActivationMatrices;
    NSMutableDictionary * _cachedStrokeEndings;
    CHDrawing * _lastDrawing;
}

- (void)cacheActivationMatrix:(id)arg1 strokeEndings:(id)arg2 drawing:(id)arg3 recognitionEngineCachingKey:(id)arg4;
- (void)clearCache;
- (void)dealloc;
- (id)debugDescription;
- (id)description;
- (id)init;
- (id)retrieveActivationMatrixForDrawing:(id)arg1 recognitionEngineCachingKey:(id)arg2 outStrokeEndings:(id*)arg3;

@end
