/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.QuickLookPreviewItemFactory : NSObject <SXQuickLookPreviewItemFactory>

- (id)init;
- (id)makeItemForFile:(id)arg1;

@end
