/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ArticleRecirculationService : _TtCs12_SwiftObject {
    void articleProviderService;
    void articleRecirculationConfigFactory;
    void articleRecirculationConfigService;
    void endOfArticleQuotaSatisfierFactory;
    void endOfArticleResultFactory;
    void headlineService;
    void historyService;
    void personalizationService;
    void tagService;
}

@end
