/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/NewsArticles.framework/NewsArticles
 */

@interface NewsArticles.ArticleInteractor : _TtCs12_SwiftObject {
    void article;
    void articleAccess;
    void articleLoadingStateMachine;
    void articlePurchaseOffersProvider;
    void articleReadingHistoryRecorder;
    void contextBuilder;
    void coordinator;
    void dataManager;
    void delegate;
    void errorMessageFactory;
    void eventManager;
    void loadingIndicatorProvider;
    void loggingIdentifier;
    void offerManager;
    void paywallFactory;
    void paywallTypeProvider;
    void previewManager;
    void readingListObserver;
}

@end
