/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/ManagedConfiguration.framework/ManagedConfiguration
 */

@interface MCEDUModeUtilities : NSObject

+ (id)_configureQuotaSizeForSharedDeviceImmediately:(id)arg1;
+ (id)_configureResidentUsersNumberForSharedDeviceImmediately:(id)arg1;
+ (unsigned long long)_getDiskSize;
+ (unsigned long long)_previousQuotaSize;
+ (bool)_updateMultiUserDeviceConfigurationFileWithKey:(id)arg1 value:(id)arg2;
+ (id)configureQuotaSizeForSharedDevice:(id)arg1;
+ (id)configureResidentUsersNumberForSharedDevice:(id)arg1;
+ (bool)configureTemporarySessionOnly:(bool)arg1 restoreQuotaSize:(bool)arg2;
+ (bool)configureTemporarySessionTimeout:(double)arg1;
+ (id)configureToSharedDevice;
+ (bool)configureUserSessionTimeout:(double)arg1;
+ (unsigned long long)getDiskAvailableSize;
+ (bool)isEphemeralMultiUser;
+ (bool)isFirstSetupBuddyDone;
+ (bool)temporarySessionOnly;
+ (double)temporarySessionTimeout;
+ (double)userSessionTimeout;

@end
