/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRepairCore.framework/CoreRepairCore
 */

@interface CRAttestationDeviceGen3Handler : CRAttestationBaseDeviceHandler

+ (id)getDeviceHandlerForProductType:(int)arg1;
+ (bool)isD4_5xProductType:(int)arg1;

- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)init;

@end
