/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRepairCore.framework/CoreRepairCore
 */

@interface CRCCertificate : NSObject {
    long long  certifcateType;
    NSArray * certificates;
    struct __SecKey { } * referenceKey;
}

@property (nonatomic) long long certifcateType;
@property (nonatomic, retain) NSArray *certificates;
@property (nonatomic) struct __SecKey { }*referenceKey;

- (void).cxx_destruct;
- (long long)certifcateType;
- (id)certificates;
- (id)copyCertificatePEMWithError:(id*)arg1;
- (bool)evaluateTrustWithScrt:(bool)arg1 verifyIdentity:(bool)arg2 referenceDate:(id)arg3 error:(id*)arg4;
- (id)extractCAAAttestationOIDDataWithError:(id*)arg1;
- (id)init;
- (id)initWithRefKey:(struct __SecKey { }*)arg1 certificates:(id)arg2 certType:(long long)arg3;
- (struct __SecKey { }*)referenceKey;
- (void)setCertifcateType:(long long)arg1;
- (void)setCertificates:(id)arg1;
- (void)setReferenceKey:(struct __SecKey { }*)arg1;

@end
