/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRepairCore.framework/CoreRepairCore
 */

@interface CRFDRBaseDeviceHandler : NSObject {
    NSString * _KBBSerialNumber;
    NSString * _KGBSerialNumber;
    bool  allowFactoryReset;
    NSDictionary * currentProperties;
    bool  isServicePart;
    NSMutableArray * warnings;
}

@property (nonatomic, retain) NSString *KBBSerialNumber;
@property (nonatomic, retain) NSString *KGBSerialNumber;
@property bool allowFactoryReset;
@property (nonatomic, retain) NSDictionary *currentProperties;
@property bool isServicePart;
@property (nonatomic, retain) NSMutableArray *warnings;

+ (id)_getDataClassUsingComponentAuthName:(id)arg1;
+ (id)_populateSealingMapForCurrentDevice;
+ (id)_populateSealingMapProperties;
+ (id)copySealingManifestDataInstanceForComponent:(id)arg1;
+ (id)generateNewSealingMapFromOld:(id)arg1 ByRemove:(id)arg2;
+ (id)getDeviceHandlerForProductType:(int)arg1;
+ (id)getPropertyArrayFrom:(id)arg1;
+ (id)getRegisterChangeDictUsingComponentAuthName:(id)arg1;
+ (id)getSealingMap;
+ (void)initSealingMap;
+ (bool)isFDRDataClassSupported:(id)arg1;
+ (bool)isFDRPropertySupported:(id)arg1;

- (void).cxx_destruct;
- (id)KBBSerialNumber;
- (id)KGBSerialNumber;
- (bool)_addDataClassAndInstanceToMutableDictionary:(id)arg1 dataClass:(id)arg2 withError:(id*)arg3;
- (bool)_addPropertyToMutableDictionary:(id)arg1 property:(id)arg2 withError:(id*)arg3;
- (bool)allowFactoryReset;
- (id)copyWithZone:(struct _NSZone { }*)arg1;
- (id)currentProperties;
- (id)getClaimDataClassesAndInstancesWithPartSPC:(id)arg1 withError:(id*)arg2;
- (id)getCurrentManifestDataClassesAndInstancesWithPartSPC:(id)arg1 fdr:(struct __AMFDR { }*)arg2 properties:(id*)arg3 fdrError:(id*)arg4;
- (id)getDataClassesAndInstancesOfKBBWith:(struct __AMFDR { }*)arg1 propertiesDict:(id*)arg2 fdrError:(id*)arg3;
- (id)getMakeDataClassesAndInstancesWithPartSPC:(id)arg1 fdrRemote:(struct __AMFDR { }*)arg2 propertiesFromParam:(id)arg3 makePropertiesDict:(id*)arg4 fdrError:(id*)arg5;
- (id)init;
- (bool)isServicePart;
- (int)parseAMFDRUnderlyingError:(id)arg1;
- (void)setAllowFactoryReset:(bool)arg1;
- (void)setCurrentProperties:(id)arg1;
- (void)setIsServicePart:(bool)arg1;
- (void)setKBBSerialNumber:(id)arg1;
- (void)setKGBSerialNumber:(id)arg1;
- (void)setWarnings:(id)arg1;
- (bool)storeWarningStrings:(id)arg1;
- (bool)validateAndSetSerialNumbersUsingPartSPC:(id)arg1 KGBSerialNumber:(id)arg2 KBBSerialNumber:(id)arg3 withError:(id*)arg4;
- (id)warnings;

@end
