/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreRepairCore.framework/CoreRepairCore
 */

@interface CRUtils : NSObject

- (id)convertDataToHexInDictionary:(id)arg1;
- (bool)currentProcessHasEntitlement:(id)arg1;
- (id)getAPTicket;
- (bool)hasEntitlementBoolForTag:(unsigned int)arg1 inAPTicket:(id)arg2;

@end
