/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PeopleSuggester.framework/PeopleSuggester
 */

@interface _PSConstants : NSObject

+ (id)eligibleShareSheetTargets;
+ (id)inCallHeuristicReason;
+ (id)macCalendarBundleId;
+ (id)macFacetimeBundleId;
+ (id)macMailBundleId;
+ (id)macMessagesBundleId;
+ (id)mobileCalendarBundleId;
+ (id)mobileFacetimeBundleId;
+ (id)mobileMailBundleId;
+ (id)mobileMessagesBundleId;
+ (id)mobileMessagesComposeBundleId;
+ (id)mobilePhoneOrFacetimeBundleId;
+ (id)mobilePhotosBundleId;
+ (id)mobileSafariBundleId;
+ (id)photoAssetPresenceHeuristicReason;
+ (id)shareSheetTargetBundleIdMail;
+ (id)shareSheetTargetBundleIdMessages;

@end
