/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices
 */

@interface PLPersistentHistoryUtilities : NSObject

+ (id)_executePersistentHistoryChangeRequest:(id)arg1 withContext:(id)arg2;
+ (bool)deleteHistoryBeforeDate:(id)arg1 whenHistoryPercentageOfStoreIsGreaterThan:(unsigned long long)arg2 withContext:(id)arg3 error:(id*)arg4;
+ (bool)deleteHistoryBeforeDate:(id)arg1 withContext:(id)arg2 error:(id*)arg3;
+ (bool)deleteHistoryBeforeToken:(id)arg1 withContext:(id)arg2 error:(id*)arg3;
+ (long long)fetchApproximateHistoryRecordCountInLibrary:(id)arg1 error:(id*)arg2;
+ (id)fetchTransactionCountSinceToken:(id)arg1 withContext:(id)arg2 error:(id*)arg3;
+ (id)fetchTransactionsSinceToken:(id)arg1 withBatchSize:(unsigned long long)arg2 context:(id)arg3 error:(id*)arg4;
+ (id)fetchTransactionsSinceToken:(id)arg1 withContext:(id)arg2 error:(id*)arg3;
+ (id)fetchTransactionsSinceToken:(id)arg1 withFetchLimit:(unsigned long long)arg2 context:(id)arg3 error:(id*)arg4;
+ (id)newestTransactionWithContext:(id)arg1;
+ (id)oldestTransactionWithContext:(id)arg1;

@end
