/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/CoreBrightness.framework/CoreBrightness
 */

@interface CBFrameLink : NSObject {
    struct __Display { } * _display;
    CADisplayLink * _displayLink;
    id /* block */  _fadeCallbackBlock;
    NSObject<OS_os_log> * _logHandle;
    NSObject<OS_dispatch_queue> * _queue;
}

- (void)dealloc;
- (void)frameSync:(id)arg1;
- (id)initWithDisplay:(struct __Display { }*)arg1 andQueue:(id)arg2;
- (bool)isPaused;
- (void)pause;
- (void)resume;
- (void)setPreferredFramesPerSecond:(float)arg1;

@end
