/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaExperience.framework/MediaExperience
 */

@interface MXCoreSessionBase : NSObject <MXCoreSessionBaseConfigurationProtocol, MXCoreSessionBaseStateProtocol> {
    long long  _ID;
    NSString * _audioCategory;
    NSString * _audioMode;
    unsigned int  _audioSessionID;
    NSString * _clientName;
    int  _clientPID;
    int  _coreSessionType;
    NSString * _displayID;
    bool  _isActive;
    bool  _isPlaying;
    unsigned long long  _mxSessionIDCounter;
    NSString * _routingContextUUID;
}

@property (nonatomic) long long ID;
@property (nonatomic, retain) NSString *audioCategory;
@property (nonatomic, retain) NSString *audioMode;
@property (nonatomic) unsigned int audioSessionID;
@property (nonatomic, retain) NSString *clientName;
@property (nonatomic) int clientPID;
@property (nonatomic) int coreSessionType;
@property (nonatomic, retain) NSString *displayID;
@property (nonatomic) bool isActive;
@property (nonatomic) bool isPlaying;
@property (nonatomic) unsigned long long mxSessionIDCounter;
@property (nonatomic, retain) NSString *routingContextUUID;

- (long long)ID;
- (id)audioCategory;
- (id)audioMode;
- (unsigned int)audioSessionID;
- (id)clientName;
- (int)clientPID;
- (int)coreSessionType;
- (void)dealloc;
- (id)displayID;
- (id)info;
- (id)init;
- (bool)isActive;
- (bool)isPlaying;
- (unsigned long long)mxSessionIDCounter;
- (id)routingContextUUID;
- (void)setAudioCategory:(id)arg1;
- (void)setAudioMode:(id)arg1;
- (void)setAudioSessionID:(unsigned int)arg1;
- (void)setClientName:(id)arg1;
- (void)setClientPID:(int)arg1;
- (void)setCoreSessionType:(int)arg1;
- (void)setDisplayID:(id)arg1;
- (void)setID:(long long)arg1;
- (void)setIsActive:(bool)arg1;
- (void)setIsPlaying:(bool)arg1;
- (void)setMxSessionIDCounter:(unsigned long long)arg1;
- (void)setRoutingContextUUID:(id)arg1;

@end
