/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MediaExperience.framework/MediaExperience
 */

@interface MXSession : NSObject {
    int  mClientType;
    struct opaqueCMSession { } * mCoreSession;
    unsigned long long  mCoreSessionID;
    unsigned long long  mCoreSessionType;
    NSString * mDescription;
    bool  mDoesntActuallyPlayAudio;
    bool  mIAmPiP;
    unsigned long long  mID;
    bool  mIsMuted;
    bool  mIsPlaying;
    NSString * mMutePriority;
    NSString * mPreferredAudioHardwareFormat;
    unsigned int  mPreferredNumberOfOutputChannels;
    double  mPreferredOutputSampleRate;
}

+ (bool)_audioQueueOptionsForMute:(unsigned long long)arg1;
+ (bool)audioQueueOptionsForMute:(unsigned long long)arg1;
+ (id)copyMXSessionForID:(unsigned long long)arg1;
+ (unsigned int)getResolvedPreferredNumberOfOutputChannels:(struct opaqueCMSession { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct { struct opaqueCMSession {} *x_2_1_1; } x2; long long x3; int x4; struct __SecTask {} *x5; struct opaqueCMSessionConfig { struct __CFString {} *x_6_1_1; unsigned int x_6_1_2; unsigned int x_6_1_3; struct __CFString {} *x_6_1_4; struct __CFString {} *x_6_1_5; unsigned int x_6_1_6; unsigned int x_6_1_7; unsigned char x_6_1_8; unsigned int x_6_1_9; unsigned char x_6_1_10; unsigned char x_6_1_11; double x_6_1_12; double x_6_1_13; unsigned char x_6_1_14; unsigned char x_6_1_15; struct __CFString {} *x_6_1_16; int x_6_1_17; int x_6_1_18; int x_6_1_19; float x_6_1_20; struct __CFDictionary {} *x_6_1_21; struct __CFDictionary {} *x_6_1_22; unsigned int x_6_1_23; unsigned char x_6_1_24; struct __CFString {} *x_6_1_25; unsigned char x_6_1_26; unsigned char x_6_1_27; struct __CFArray {} *x_6_1_28; struct __CFArray {} *x_6_1_29; struct __CFArray {} *x_6_1_30; struct __CFArray {} *x_6_1_31; struct __CFArray {} *x_6_1_32; struct __CFString {} *x_6_1_33; int x_6_1_34; int x_6_1_35; void *x_6_1_36; void *x_6_1_37; struct __CFDictionary {} *x_6_1_38; unsigned char x_6_1_39; float x_6_1_40; float x_6_1_41; float x_6_1_42; float x_6_1_43; unsigned char x_6_1_44; } x6; }*)arg1;
+ (bool)isCoreSessionFormatValidForMaxOutputChannels:(id)arg1;
+ (int)updateDoesntActuallyPlayAudio:(struct opaqueCMSession { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct { struct opaqueCMSession {} *x_2_1_1; } x2; long long x3; int x4; struct __SecTask {} *x5; struct opaqueCMSessionConfig { struct __CFString {} *x_6_1_1; unsigned int x_6_1_2; unsigned int x_6_1_3; struct __CFString {} *x_6_1_4; struct __CFString {} *x_6_1_5; unsigned int x_6_1_6; unsigned int x_6_1_7; unsigned char x_6_1_8; unsigned int x_6_1_9; unsigned char x_6_1_10; unsigned char x_6_1_11; double x_6_1_12; double x_6_1_13; unsigned char x_6_1_14; unsigned char x_6_1_15; struct __CFString {} *x_6_1_16; int x_6_1_17; int x_6_1_18; int x_6_1_19; float x_6_1_20; struct __CFDictionary {} *x_6_1_21; struct __CFDictionary {} *x_6_1_22; unsigned int x_6_1_23; unsigned char x_6_1_24; struct __CFString {} *x_6_1_25; unsigned char x_6_1_26; unsigned char x_6_1_27; struct __CFArray {} *x_6_1_28; struct __CFArray {} *x_6_1_29; struct __CFArray {} *x_6_1_30; struct __CFArray {} *x_6_1_31; struct __CFArray {} *x_6_1_32; struct __CFString {} *x_6_1_33; int x_6_1_34; int x_6_1_35; void *x_6_1_36; void *x_6_1_37; struct __CFDictionary {} *x_6_1_38; unsigned char x_6_1_39; float x_6_1_40; float x_6_1_41; float x_6_1_42; float x_6_1_43; unsigned char x_6_1_44; } x6; }*)arg1;
+ (int)updateIsPlaying:(struct opaqueCMSession { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct { struct opaqueCMSession {} *x_2_1_1; } x2; long long x3; int x4; struct __SecTask {} *x5; struct opaqueCMSessionConfig { struct __CFString {} *x_6_1_1; unsigned int x_6_1_2; unsigned int x_6_1_3; struct __CFString {} *x_6_1_4; struct __CFString {} *x_6_1_5; unsigned int x_6_1_6; unsigned int x_6_1_7; unsigned char x_6_1_8; unsigned int x_6_1_9; unsigned char x_6_1_10; unsigned char x_6_1_11; double x_6_1_12; double x_6_1_13; unsigned char x_6_1_14; unsigned char x_6_1_15; struct __CFString {} *x_6_1_16; int x_6_1_17; int x_6_1_18; int x_6_1_19; float x_6_1_20; struct __CFDictionary {} *x_6_1_21; struct __CFDictionary {} *x_6_1_22; unsigned int x_6_1_23; unsigned char x_6_1_24; struct __CFString {} *x_6_1_25; unsigned char x_6_1_26; unsigned char x_6_1_27; struct __CFArray {} *x_6_1_28; struct __CFArray {} *x_6_1_29; struct __CFArray {} *x_6_1_30; struct __CFArray {} *x_6_1_31; struct __CFArray {} *x_6_1_32; struct __CFString {} *x_6_1_33; int x_6_1_34; int x_6_1_35; void *x_6_1_36; void *x_6_1_37; struct __CFDictionary {} *x_6_1_38; unsigned char x_6_1_39; float x_6_1_40; float x_6_1_41; float x_6_1_42; float x_6_1_43; unsigned char x_6_1_44; } x6; }*)arg1;
+ (int)updatePreferredAudioHardwareFormat:(struct opaqueCMSession { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct { struct opaqueCMSession {} *x_2_1_1; } x2; long long x3; int x4; struct __SecTask {} *x5; struct opaqueCMSessionConfig { struct __CFString {} *x_6_1_1; unsigned int x_6_1_2; unsigned int x_6_1_3; struct __CFString {} *x_6_1_4; struct __CFString {} *x_6_1_5; unsigned int x_6_1_6; unsigned int x_6_1_7; unsigned char x_6_1_8; unsigned int x_6_1_9; unsigned char x_6_1_10; unsigned char x_6_1_11; double x_6_1_12; double x_6_1_13; unsigned char x_6_1_14; unsigned char x_6_1_15; struct __CFString {} *x_6_1_16; int x_6_1_17; int x_6_1_18; int x_6_1_19; float x_6_1_20; struct __CFDictionary {} *x_6_1_21; struct __CFDictionary {} *x_6_1_22; unsigned int x_6_1_23; unsigned char x_6_1_24; struct __CFString {} *x_6_1_25; unsigned char x_6_1_26; unsigned char x_6_1_27; struct __CFArray {} *x_6_1_28; struct __CFArray {} *x_6_1_29; struct __CFArray {} *x_6_1_30; struct __CFArray {} *x_6_1_31; struct __CFArray {} *x_6_1_32; struct __CFString {} *x_6_1_33; int x_6_1_34; int x_6_1_35; void *x_6_1_36; void *x_6_1_37; struct __CFDictionary {} *x_6_1_38; unsigned char x_6_1_39; float x_6_1_40; float x_6_1_41; float x_6_1_42; float x_6_1_43; unsigned char x_6_1_44; } x6; }*)arg1 withMaxOutputChannels:(unsigned int)arg2 andCalledFromDealloc:(bool)arg3;
+ (int)updatePreferredNumberOfOutputChannels:(struct opaqueCMSession { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct { struct opaqueCMSession {} *x_2_1_1; } x2; long long x3; int x4; struct __SecTask {} *x5; struct opaqueCMSessionConfig { struct __CFString {} *x_6_1_1; unsigned int x_6_1_2; unsigned int x_6_1_3; struct __CFString {} *x_6_1_4; struct __CFString {} *x_6_1_5; unsigned int x_6_1_6; unsigned int x_6_1_7; unsigned char x_6_1_8; unsigned int x_6_1_9; unsigned char x_6_1_10; unsigned char x_6_1_11; double x_6_1_12; double x_6_1_13; unsigned char x_6_1_14; unsigned char x_6_1_15; struct __CFString {} *x_6_1_16; int x_6_1_17; int x_6_1_18; int x_6_1_19; float x_6_1_20; struct __CFDictionary {} *x_6_1_21; struct __CFDictionary {} *x_6_1_22; unsigned int x_6_1_23; unsigned char x_6_1_24; struct __CFString {} *x_6_1_25; unsigned char x_6_1_26; unsigned char x_6_1_27; struct __CFArray {} *x_6_1_28; struct __CFArray {} *x_6_1_29; struct __CFArray {} *x_6_1_30; struct __CFArray {} *x_6_1_31; struct __CFArray {} *x_6_1_32; struct __CFString {} *x_6_1_33; int x_6_1_34; int x_6_1_35; void *x_6_1_36; void *x_6_1_37; struct __CFDictionary {} *x_6_1_38; unsigned char x_6_1_39; float x_6_1_40; float x_6_1_41; float x_6_1_42; float x_6_1_43; unsigned char x_6_1_44; } x6; }*)arg1;
+ (int)updatePreferredOutputSampleRate:(struct opaqueCMSession { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct { struct opaqueCMSession {} *x_2_1_1; } x2; long long x3; int x4; struct __SecTask {} *x5; struct opaqueCMSessionConfig { struct __CFString {} *x_6_1_1; unsigned int x_6_1_2; unsigned int x_6_1_3; struct __CFString {} *x_6_1_4; struct __CFString {} *x_6_1_5; unsigned int x_6_1_6; unsigned int x_6_1_7; unsigned char x_6_1_8; unsigned int x_6_1_9; unsigned char x_6_1_10; unsigned char x_6_1_11; double x_6_1_12; double x_6_1_13; unsigned char x_6_1_14; unsigned char x_6_1_15; struct __CFString {} *x_6_1_16; int x_6_1_17; int x_6_1_18; int x_6_1_19; float x_6_1_20; struct __CFDictionary {} *x_6_1_21; struct __CFDictionary {} *x_6_1_22; unsigned int x_6_1_23; unsigned char x_6_1_24; struct __CFString {} *x_6_1_25; unsigned char x_6_1_26; unsigned char x_6_1_27; struct __CFArray {} *x_6_1_28; struct __CFArray {} *x_6_1_29; struct __CFArray {} *x_6_1_30; struct __CFArray {} *x_6_1_31; struct __CFArray {} *x_6_1_32; struct __CFString {} *x_6_1_33; int x_6_1_34; int x_6_1_35; void *x_6_1_36; void *x_6_1_37; struct __CFDictionary {} *x_6_1_38; unsigned char x_6_1_39; float x_6_1_40; float x_6_1_41; float x_6_1_42; float x_6_1_43; unsigned char x_6_1_44; } x6; }*)arg1;

- (int)_copyPropertyForKey:(id)arg1 valueOut:(id*)arg2;
- (void)_dealloc;
- (id)_initWithSession:(struct opaqueCMSession { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct { struct opaqueCMSession {} *x_2_1_1; } x2; long long x3; int x4; struct __SecTask {} *x5; struct opaqueCMSessionConfig { struct __CFString {} *x_6_1_1; unsigned int x_6_1_2; unsigned int x_6_1_3; struct __CFString {} *x_6_1_4; struct __CFString {} *x_6_1_5; unsigned int x_6_1_6; unsigned int x_6_1_7; unsigned char x_6_1_8; unsigned int x_6_1_9; unsigned char x_6_1_10; unsigned char x_6_1_11; double x_6_1_12; double x_6_1_13; unsigned char x_6_1_14; unsigned char x_6_1_15; struct __CFString {} *x_6_1_16; int x_6_1_17; int x_6_1_18; int x_6_1_19; float x_6_1_20; struct __CFDictionary {} *x_6_1_21; struct __CFDictionary {} *x_6_1_22; unsigned int x_6_1_23; unsigned char x_6_1_24; struct __CFString {} *x_6_1_25; unsigned char x_6_1_26; unsigned char x_6_1_27; struct __CFArray {} *x_6_1_28; struct __CFArray {} *x_6_1_29; struct __CFArray {} *x_6_1_30; struct __CFArray {} *x_6_1_31; struct __CFArray {} *x_6_1_32; struct __CFString {} *x_6_1_33; int x_6_1_34; int x_6_1_35; void *x_6_1_36; void *x_6_1_37; struct __CFDictionary {} *x_6_1_38; unsigned char x_6_1_39; float x_6_1_40; float x_6_1_41; float x_6_1_42; float x_6_1_43; unsigned char x_6_1_44; } x6; }*)arg1;
- (int)_setPropertyForKey:(id)arg1 value:(const void*)arg2;
- (int)copyPropertyForKey:(id)arg1 valueOut:(id*)arg2;
- (void)dealloc;
- (id)description;
- (void)dumpInfo;
- (bool)getActuallyPlaysAudio;
- (int)getClientType;
- (id)getClientTypeAsString;
- (struct opaqueCMSession { struct __CFRuntimeBase { unsigned long long x_1_1_1; _Atomic unsigned long long x_1_1_2; } x1; struct { struct opaqueCMSession {} *x_2_1_1; } x2; long long x3; int x4; struct __SecTask {} *x5; struct opaqueCMSessionConfig { struct __CFString {} *x_6_1_1; unsigned int x_6_1_2; unsigned int x_6_1_3; struct __CFString {} *x_6_1_4; struct __CFString {} *x_6_1_5; unsigned int x_6_1_6; unsigned int x_6_1_7; unsigned char x_6_1_8; unsigned int x_6_1_9; unsigned char x_6_1_10; unsigned char x_6_1_11; double x_6_1_12; double x_6_1_13; unsigned char x_6_1_14; unsigned char x_6_1_15; struct __CFString {} *x_6_1_16; int x_6_1_17; int x_6_1_18; int x_6_1_19; float x_6_1_20; struct __CFDictionary {} *x_6_1_21; struct __CFDictionary {} *x_6_1_22; unsigned int x_6_1_23; unsigned char x_6_1_24; struct __CFString {} *x_6_1_25; unsigned char x_6_1_26; unsigned char x_6_1_27; struct __CFArray {} *x_6_1_28; struct __CFArray {} *x_6_1_29; struct __CFArray {} *x_6_1_30; struct __CFArray {} *x_6_1_31; struct __CFArray {} *x_6_1_32; struct __CFString {} *x_6_1_33; int x_6_1_34; int x_6_1_35; void *x_6_1_36; void *x_6_1_37; struct __CFDictionary {} *x_6_1_38; unsigned char x_6_1_39; float x_6_1_40; float x_6_1_41; float x_6_1_42; float x_6_1_43; unsigned char x_6_1_44; } x6; }*)getCoreSession;
- (long long)getCoreSessionID;
- (bool)getDoesntActuallyPlayAudio;
- (bool)getIAmPiP;
- (unsigned long long)getID;
- (bool)getIsMuted;
- (bool)getIsPlaying;
- (id)getMutePriority;
- (id)getPreferredAudioHardwareFormat;
- (unsigned int)getPreferredNumberOfOutputChannels;
- (double)getPreferredOutputSampleRate;
- (id)info;
- (id)initWithSession:(struct opaqueCMSession { }*)arg1;
- (void)mute;
- (void)postIsMutedDidChange;
- (int)setClientType:(int)arg1;
- (int)setDoesntActuallyPlayAudio:(bool)arg1;
- (int)setIAmPiP:(bool)arg1;
- (int)setID:(unsigned long long)arg1;
- (int)setIsMuted:(bool)arg1;
- (int)setIsPlaying:(bool)arg1;
- (int)setMutePriority:(id)arg1;
- (int)setPreferredAudioHardwareFormat:(id)arg1;
- (int)setPreferredNumberOfOutputChannels:(unsigned int)arg1;
- (int)setPreferredOutputSampleRate:(double)arg1;
- (int)setPropertyForKey:(id)arg1 value:(const void*)arg2;
- (void)unmute;

@end
