/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/GeoServices.framework/GeoServices
 */

@interface GEOPlaceQuestionnaire : NSObject {
    bool  _alwaysPositionInitialRatingCtaTowardsTop;
    NSArray * _ratingCategories;
    GEOPDScorecardLayout * _scorecardLayout;
    NSString * _version;
}

@property (nonatomic, readonly) bool alwaysPositionInitialRatingCtaTowardsTop;
@property (nonatomic, readonly) NSArray *ratingCategories;
@property (nonatomic, readonly, copy) NSString *version;

- (void).cxx_destruct;
- (bool)alwaysPositionInitialRatingCtaTowardsTop;
- (id)initWithGEOPDPlaceQuestionnaire:(id)arg1;
- (id)ratingCategories;
- (id)version;

@end
