/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriClientFlow.framework/SiriClientFlow
 */

@interface CFPreferences : NSObject

+ (id)_clientFlowUserDefaults;
+ (id)_valueFromCKKnowledgeStoreWithKey:(id)arg1;
+ (id)baseScriptExecutorCacheKey;
+ (id)defaultWarmupScriptsExtension;
+ (bool)hasMarkedScriptCacheAsPurgeable;
+ (bool)isByteCodeCacheEnabled;
+ (id)scripterInactivityTimerInSeconds;
+ (void)setMarkedScriptCacheAsPurgeable:(bool)arg1;
+ (bool)shouldOverrideScripts;
+ (bool)shouldRunNodeFlow:(bool)arg1;
+ (bool)shouldSkipUpdateScriptsOnBoot;
+ (id)warmupModularScriptIdentifiers;
+ (id)warmupScriptIdentifiers;

@end
