/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafari.framework/MobileSafari
 */

@interface _SFPasswordTouchIconCache : WBSTouchIconCache

- (id)_operationWithRequest:(id)arg1 completionHandler:(id /* block */)arg2;
- (bool)canHandleRequest:(id)arg1;

@end
