/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafari.framework/MobileSafari
 */

@interface _SFTouchIconCache : WBSTouchIconCache

+ (id)_generateDefaultFavoritesIcon;
+ (id)_monogramConfiguration;
+ (id)defaultBackgroundColor;

- (id)_operationWithRequest:(id)arg1 completionHandler:(id /* block */)arg2;
- (bool)canHandleRequest:(id)arg1;

@end
