/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/MobileSafari.framework/MobileSafari
 */

@interface SFBookmarksLockCoordinator : NSObject {
    NSTimer * _bookmarkLockTimer;
    bool  _haveBookmarksLock;
}

@property (nonatomic, readonly) bool hasBookmarksLock;

+ (id)sharedCoordinator;
+ (void)showLockedDatabaseAlertForAction:(long long)arg1 fromViewController:(id)arg2;

- (void).cxx_destruct;
- (void)_clearBookmarkLockTimer;
- (void)_unlockBookmarksNow;
- (void)dealloc;
- (bool)hasBookmarksLock;
- (bool)lockBookmarks;
- (void)unlockBookmarksIfNeeded;
- (void)unlockBookmarksSoon;

@end
