/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/TextInputCore.framework/TextInputCore
 */

@interface TIDPUnknownTokenRecorder : TIDPRecorder

- (id)delegate;
- (id)initWithTypingSession:(id)arg1 aligned:(id)arg2 inputManager:(id)arg3;
- (id)recordingKey;
- (id)records;
- (bool)report;

@end
