/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/PromotedContentUI.framework/PromotedContentUI
 */

@interface APPCMetricsView : UIView <APPCMetricRegister, ASCAdLockupViewDelegate, NewsTransparencyViewControllerDelegate> {
    void _isCollapsed;
    void appView;
    void contentView;
    void context;
    void currentlyViewable;
    void debugOverlay;
    void debugView;
    void forcedReadiness;
    void frameObserver;
    void interactionPresentationDelegate;
    void isBackgrounded;
    void lastTimeVisibilityCheckFrame;
    void needToSendOnScreen;
    void offsetObserver;
    void promotedContent;
    void promotedContentInfo;
    void readinessObserver;
    void ready;
    void readyDelegate;
    void startsCollapsed;
    void timingTracking;
    void viewCollapsedState;
    void visbilityCheckingView;
    void visibilityChecker;
    void visibleThresholds;
    void wasTapped;
}

@property (nonatomic, readonly) <APPCDiagnosticMetricsHelping> *diagnosticMetricHelper;
@property (nonatomic) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } frame;
@property (nonatomic) <APPCMetricsInteractionPresentationDelegate> *interactionPresentationDelegate;
@property (nonatomic, readonly) struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; } privacyMarkerFrame;
@property (nonatomic, readonly) APPrivacyMarker *privacyMarkerView;
@property (nonatomic, retain) APPCPromotedContentInfo *promotedContentInfo;
@property (nonatomic) bool ready;
@property (nonatomic) <APPCMetricsViewReadyDelegate> *readyDelegate;

- (void).cxx_destruct;
- (void)adLockupView:(id)arg1 didFailRequestWithError:(id)arg2;
- (void)adLockupView:(id)arg1 didSelectOfferWithState:(id)arg2;
- (void)adLockupViewDidCancelScreenshotsFetchRequest:(id)arg1;
- (void)adLockupViewDidFinishRequest:(id)arg1;
- (void)adLockupViewDidFinishScreenshotsFetchRequest:(id)arg1;
- (void)adLockupViewDidSelectAdMarker:(id)arg1;
- (void)appBackgrounded:(id)arg1;
- (void)appForegrounded:(id)arg1;
- (void)appWillResignActive:(id)arg1;
- (void)collapse;
- (void)dealloc;
- (id)diagnosticMetricHelper;
- (void)didMoveToSuperview;
- (void)didMoveToWindow;
- (void)expand;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })frame;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (id)interactionPresentationDelegate;
- (id)metricsActivityForAdLockupView:(id)arg1 toPerformActionOfOffer:(id)arg2 inState:(id)arg3;
- (id)metricsActivityForPresentingProductDetailsOfAdLockupView:(id)arg1 inState:(id)arg2;
- (void)newsTransparencyViewControllerDidDismiss:(id)arg1;
- (id)presentingViewControllerForAdLockupView:(id)arg1;
- (struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })privacyMarkerFrame;
- (id)privacyMarkerView;
- (id)promotedContentInfo;
- (bool)ready;
- (id)readyDelegate;
- (void)registerHandlerForAllMetricsWithClosure:(id /* block */)arg1;
- (void)removeHandler;
- (bool)safeCollapseAndReturnError:(id*)arg1;
- (bool)safeExpandAndReturnError:(id*)arg1;
- (void)setFrame:(struct CGRect { struct CGPoint { double x_1_1_1; double x_1_1_2; } x1; struct CGSize { double x_2_1_1; double x_2_1_2; } x2; })arg1;
- (void)setInteractionPresentationDelegate:(id)arg1;
- (void)setPromotedContentInfo:(id)arg1;
- (void)setReady:(bool)arg1;
- (void)setReadyDelegate:(id)arg1;
- (void)traitCollectionDidChange:(id)arg1;
- (void)unloadAdViewIfRequired;
- (void)willEnterforeground;
- (void)willMoveToSuperview:(id)arg1;

@end
