/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.PersonalRequestActivityNotificationFlow : _TtCs12_SwiftObject {
    void actifityPreferenceProvider;
    void deviceState;
    void notificationHeaderProviding;
    void notificationService;
    void strategy;
}

@end
