/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/SiriKitFlow.framework/SiriKitFlow
 */

@interface SiriKitFlow.PersonalDomainCheckFlow : _TtCs12_SwiftObject {
    void deviceState;
    void notificationFlowProvider;
    void outputPublisher;
    void state;
    void strategy;
}

@end
